	.align 2
gUnknown_081438F4:
	.incbin "sound/direct_sound_samples/081438F4.bin"

	.align 2
gUnknown_081495C8:
	.incbin "sound/direct_sound_samples/081495C8.bin"

	.align 2
gUnknown_08149FCC:
	.incbin "sound/direct_sound_samples/08149FCC.bin"

	.align 2
gUnknown_0814A050:
	.incbin "sound/direct_sound_samples/0814A050.bin"

	.align 2
gUnknown_0814AA34:
	.incbin "sound/direct_sound_samples/0814AA34.bin"

	.align 2
gUnknown_0814B228:
	.incbin "sound/direct_sound_samples/0814B228.bin"

	.align 2
gUnknown_0814C94C:
	.incbin "sound/direct_sound_samples/0814C94C.bin"

	.align 2
gUnknown_0814FBE0:
	.incbin "sound/direct_sound_samples/0814FBE0.bin"

	.align 2
gUnknown_08153AE4:
	.incbin "sound/direct_sound_samples/08153AE4.bin"

	.align 2
gUnknown_081541C8:
	.incbin "sound/direct_sound_samples/081541C8.bin"

	.align 2
gUnknown_0815568C:
	.incbin "sound/direct_sound_samples/0815568C.bin"

	.align 2
gUnknown_08155C10:
	.incbin "sound/direct_sound_samples/08155C10.bin"

	.align 2
gUnknown_08157464:
	.incbin "sound/direct_sound_samples/08157464.bin"

	.align 2
gUnknown_08159468:
	.incbin "sound/direct_sound_samples/08159468.bin"

	.align 2
gUnknown_0815A01C:
	.incbin "sound/direct_sound_samples/0815A01C.bin"

	.align 2
gUnknown_0815A0A0:
	.incbin "sound/direct_sound_samples/0815A0A0.bin"

	.align 2
gUnknown_0815A124:
	.incbin "sound/direct_sound_samples/0815A124.bin"

	.align 2
gUnknown_0815A488:
	.incbin "sound/direct_sound_samples/0815A488.bin"

	.align 2
gUnknown_0815A9BC:
	.incbin "sound/direct_sound_samples/0815A9BC.bin"

	.align 2
gUnknown_0815BB70:
	.incbin "sound/direct_sound_samples/0815BB70.bin"

	.align 2
gUnknown_0815BBF4:
	.incbin "sound/direct_sound_samples/0815BBF4.bin"

	.align 2
gUnknown_0815CBA8:
	.incbin "sound/direct_sound_samples/0815CBA8.bin"

	.align 2
gUnknown_0815D72C:
	.incbin "sound/direct_sound_samples/0815D72C.bin"
	
	@why does this cause a random LOAD section when its a .align 4
	.byte 0,0,0
