	.align 2
	.global gMPlayTable
gMPlayTable:	@ 0x08142B5C
	music_player gUnknown_0203FD00, gUnknown_0203F140, 8, 0
	music_player gUnknown_0203FD80, gUnknown_0203F3C0, 2, 0
	music_player gUnknown_0203FDC0, gUnknown_0203F460, 1, 0
	music_player gUnknown_0203FE90, gUnknown_0203F4B0, 1, 0
	music_player gUnknown_0203FE00, gUnknown_0203F500, 2, 0
	music_player gUnknown_0203FC80, gUnknown_0203F5A0, 2, 0
	music_player gUnknown_0203FCC0, gUnknown_0203F640, 2, 0
	music_player gUnknown_0203FD40, gUnknown_0203F6E0, 2, 0
	music_player gUnknown_0203FE50, gUnknown_0203F780, 16, 0
