	.align 2
gUnknown_08142AEC:
	.incbin "sound/programmable_wave_samples/08142AEC.pcm"

	.align 2
gUnknown_08142AFC:
	.incbin "sound/programmable_wave_samples/08142AFC.pcm"

	.align 2
gUnknown_08142B0C:
	.incbin "sound/programmable_wave_samples/08142B0C.pcm"

	.align 2
gUnknown_08142B1C:
	.incbin "sound/programmable_wave_samples/08142B1C.pcm"

	.align 2
gUnknown_08142B2C:
	.incbin "sound/programmable_wave_samples/08142B2C.pcm"

	.align 2
gUnknown_08142B3C:
	.incbin "sound/programmable_wave_samples/08142B3C.pcm"

	.align 2
gUnknown_08142B4C:
	.incbin "sound/programmable_wave_samples/08142B4C.pcm"
