    .global gUnknown_08210764
gUnknown_08210764:
    .string "{END}"

    .global gUnknown_08210765
gUnknown_08210765:
    .string "Dogen{END}"

    .global gUnknown_0821076B
gUnknown_0821076B:
    .string "Nanai{END}"

    .global gUnknown_08210771
gUnknown_08210771:
    .string "Winlan{END}"

    .global gUnknown_08210778
gUnknown_08210778:
    .string "Romero{END}"

    .global gUnknown_0821077F
gUnknown_0821077F:
    .string "Gust{END}"

    .global gUnknown_08210784
gUnknown_08210784:
    .string "Camlon{END}"

    .global gUnknown_0821078B
gUnknown_0821078B:
    .string "Nada{END}"

    .global gUnknown_08210790
gUnknown_08210790:
    .string "Tantar{END}"

    .global gUnknown_08210797
gUnknown_08210797:
    .string "Tuntar{END}"

    .global gUnknown_0821079E
gUnknown_0821079E:
    .string "Agua{END}"

    .global gUnknown_082107A3
gUnknown_082107A3:
    .string "Auria{END}"

    .global gUnknown_082107A9
gUnknown_082107A9:
    .string "Bleak{END}"

    .global gUnknown_082107AF
gUnknown_082107AF:
    .string "Arad{END}"

    .global gUnknown_082107B4
gUnknown_082107B4:
    .string "Spring{END}"

    .global gUnknown_082107BB
gUnknown_082107BB:
    .string "Tunlan{END}"

    .global gUnknown_082107C2
gUnknown_082107C2:
    .string "Gant{END}"

    .global gUnknown_082107C7
gUnknown_082107C7:
    .string "Scande{END}"

    .global gUnknown_082107CE
gUnknown_082107CE:
    .string "Carmen{END}"

    .global gUnknown_082107D5
gUnknown_082107D5:
    .string "Gramor{END}"

    .global gUnknown_082107DC
gUnknown_082107DC:
    .string "Wisdon{END}"

    .global gUnknown_082107E3
gUnknown_082107E3:
    .string "Karma{END}"

    .global gUnknown_082107E9
gUnknown_082107E9:
    .string "Prima{END}"

    .global gUnknown_082107EF
gUnknown_082107EF:
    .string "Krypt{END}"

    .global gUnknown_082107F5
gUnknown_082107F5:
    .string "Nabal{END}"

    .global gUnknown_082107FB
gUnknown_082107FB:
    .string "Tock{END}"

    .global gUnknown_08210800
gUnknown_08210800:
    .string "Spyre{END}"

    .global gUnknown_08210806
gUnknown_08210806:
    .string "Obelisk{END}"

    .global gUnknown_0821080E
gUnknown_0821080E:
    .string "Pagoda{END}"

