    .global gUnknown_08210363
gUnknown_08210363:
    .string "Robe{END}"

    .global gUnknown_08210368
gUnknown_08210368:
    .string "WLdrCP{END}"

    .global gUnknown_0821036F
gUnknown_0821036F:
    .string "Kleid{END}"

    .global gUnknown_08210375
gUnknown_08210375:
    .string "MetlRÜ{END}"

    .global gUnknown_0821037C
gUnknown_0821037C:
    .string "SeidHS{END}"

    .global gUnknown_08210383
gUnknown_08210383:
    .string "Kldng{END}"

    .global gUnknown_08210389
gUnknown_08210389:
    .string "LichtKL{END}"

    .global gUnknown_08210391
gUnknown_08210391:
    .string "Talar{END}"

    .global gUnknown_08210397
gUnknown_08210397:
    .string "ArmSchtz{END}"

    .global gUnknown_082103A0
gUnknown_082103A0:
    .string "Wolffell{END}"

    .global gUnknown_082103A9
gUnknown_082103A9:
    .string "RangerVT{END}"

    .global gUnknown_082103B2
gUnknown_082103B2:
    .string "BronzRÜ{END}"

    .global gUnknown_082103BA
gUnknown_082103BA:
    .string "PnzerRÜ{END}"

    .global gUnknown_082103C2
gUnknown_082103C2:
    .string "Dummy{END}"

    .global gUnknown_082103C8
gUnknown_082103C8:
    .string "FlammRÜ{END}"

    .global gUnknown_082103D0
gUnknown_082103D0:
    .string "KerkrKL{END}"

    .global gUnknown_082103D8
gUnknown_082103D8:
    .string "SRüstng{END}"

    .global gUnknown_082103E0
gUnknown_082103E0:
    .string "EisRÜ{END}"

    .global gUnknown_082103E6
gUnknown_082103E6:
    .string "WeltHR{END}"

    .global gUnknown_082103ED
gUnknown_082103ED:
    .string "Dummy{END}"

    .global gUnknown_082103F3
gUnknown_082103F3:
    .string "StchlKL{END}"

    .global gUnknown_082103FB
gUnknown_082103FB:
    .string "HeldRÜ{END}"

    .global gUnknown_08210402
gUnknown_08210402:
    .string "TeuflRB{END}"

    .global gUnknown_0821040A
gUnknown_0821040A:
    .string "WLedrGN{END}"

    .global gUnknown_08210412
gUnknown_08210412:
    .string "WLedrRÜ{END}"

    .global gUnknown_0821041A
gUnknown_0821041A:
    .string "KettnHD{END}"

    .global gUnknown_08210422
gUnknown_08210422:
    .string "EisnHR{END}"

    .global gUnknown_08210429
gUnknown_08210429:
    .string "WollRB{END}"

    .global gUnknown_08210430
gUnknown_08210430:
    .string "WLedrRB{END}"

    .global gUnknown_08210438
gUnknown_08210438:
    .string "LebensRÜ{END}"

    .global gUnknown_08210441
gUnknown_08210441:
    .string "PowerRÜ{END}"

    .global gUnknown_08210449
gUnknown_08210449:
    .string "QuartzRÜ{END}"

    .global gUnknown_08210452
gUnknown_08210452:
    .string "EngelsRÜ{END}"

    .global gUnknown_0821045B
gUnknown_0821045B:
    .string "Dummy{END}"

    .global gUnknown_08210461
gUnknown_08210461:
    .string "GuruCT{END}"

    .global gUnknown_08210468
gUnknown_08210468:
    .string "Dummy{END}"

    .global gUnknown_0821046E
gUnknown_0821046E:
    .string "Dummy{END}"

    .global gUnknown_08210474
gUnknown_08210474:
    .string "WeltRÜ{END}"

    .global gUnknown_0821047B
gUnknown_0821047B:
    .string "SagenHR{END}"

    .global gUnknown_08210483
gUnknown_08210483:
    .string "Dummy{END}"

    .global gUnknown_08210489
gUnknown_08210489:
    .string "MystRB{END}"

    .global gUnknown_08210490
gUnknown_08210490:
    .string "ErdRB{END}"

    .global gUnknown_08210496
gUnknown_08210496:
    .string "Dummy{END}"

    .global gUnknown_0821049C
gUnknown_0821049C:
    .string "AgileRÜ{END}"

    .global gUnknown_082104A4
gUnknown_082104A4:
    .string "Dummy{END}"

    .global gUnknown_082104AA
gUnknown_082104AA:
    .string "JagdKL{END}"

    .global gUnknown_082104B1
gUnknown_082104B1:
    .string "GltteKL{END}"

    .global gUnknown_082104B9
gUnknown_082104B9:
    .string "Dummy{END}"

    .global gUnknown_082104BF
gUnknown_082104BF:
    .string "HolzSH{END}"

    .global gUnknown_082104C6
gUnknown_082104C6:
    .string "PzHdsch{END}"

    .global gUnknown_082104CE
gUnknown_082104CE:
    .string "WLedrSH{END}"

    .global gUnknown_082104D6
gUnknown_082104D6:
    .string "WachSH{END}"

    .global gUnknown_082104DD
gUnknown_082104DD:
    .string "Armband{END}"

    .global gUnknown_082104E5
gUnknown_082104E5:
    .string "EisnSH{END}"

    .global gUnknown_082104EC
gUnknown_082104EC:
    .string "BronzSH{END}"

    .global gUnknown_082104F4
gUnknown_082104F4:
    .string "MetllSH{END}"

    .global gUnknown_082104FC
gUnknown_082104FC:
    .string "FlammSH{END}"

    .global gUnknown_08210504
gUnknown_08210504:
    .string "Dummy{END}"

    .global gUnknown_0821050A
gUnknown_0821050A:
    .string "SSchld{END}"

    .global gUnknown_08210511
gUnknown_08210511:
    .string "EisnSL{END}"

    .global gUnknown_08210518
gUnknown_08210518:
    .string "MetllSL{END}"

    .global gUnknown_08210520
gUnknown_08210520:
    .string "Dummy{END}"

    .global gUnknown_08210526
gUnknown_08210526:
    .string "Armband{END}"

    .global gUnknown_0821052E
gUnknown_0821052E:
    .string "EisSH{END}"

    .global gUnknown_08210534
gUnknown_08210534:
    .string "ProSH{END}"

    .global gUnknown_0821053A
gUnknown_0821053A:
    .string "LiebeAB{END}"

    .global gUnknown_08210542
gUnknown_08210542:
    .string "WindAB{END}"

    .global gUnknown_08210549
gUnknown_08210549:
    .string "RubinRG{END}"

    .global gUnknown_08210551
gUnknown_08210551:
    .string "Dummy{END}"

    .global gUnknown_08210557
gUnknown_08210557:
    .string "DnklAB{END}"

    .global gUnknown_0821055E
gUnknown_0821055E:
    .string "Dummy{END}"

    .global gUnknown_08210564
gUnknown_08210564:
    .string "MystSH{END}"

    .global gUnknown_0821056B
gUnknown_0821056B:
    .string "Hndschuh{END}"

    .global gUnknown_08210574
gUnknown_08210574:
    .string "Dummy{END}"

    .global gUnknown_0821057A
gUnknown_0821057A:
    .string "FllSchtz{END}"

    .global gUnknown_08210583
gUnknown_08210583:
    .string "LichtSH{END}"

    .global gUnknown_0821058B
gUnknown_0821058B:
    .string "MagieRG{END}"

    .global gUnknown_08210593
gUnknown_08210593:
    .string "Bandage{END}"

    .global gUnknown_0821059B
gUnknown_0821059B:
    .string "Dummy{END}"

    .global gUnknown_082105A1
gUnknown_082105A1:
    .string "SilberAB{END}"

    .global gUnknown_082105AA
gUnknown_082105AA:
    .string "Dummy{END}"

    .global gUnknown_082105B0
gUnknown_082105B0:
    .string "KaltSH{END}"

    .global gUnknown_082105B7
gUnknown_082105B7:
    .string "JagdHS{END}"

    .global gUnknown_082105BE
gUnknown_082105BE:
    .string "MaskenSH{END}"

    .global gUnknown_082105C7
gUnknown_082105C7:
    .string "DrachnSH{END}"

    .global gUnknown_082105D0
gUnknown_082105D0:
    .string "Dummy{END}"

    .global gUnknown_082105D6
gUnknown_082105D6:
    .string "LavaSH{END}"

    .global gUnknown_082105DD
gUnknown_082105DD:
    .string "Dummy{END}"

    .global gUnknown_082105E3
gUnknown_082105E3:
    .string "WLdrHM{END}"

    .global gUnknown_082105EA
gUnknown_082105EA:
    .string "Visier{END}"

    .global gUnknown_082105F1
gUnknown_082105F1:
    .string "HaarBand{END}"

    .global gUnknown_082105FA
gUnknown_082105FA:
    .string "Diadem{END}"

    .global gUnknown_08210601
gUnknown_08210601:
    .string "KttnHM{END}"

    .global gUnknown_08210608
gUnknown_08210608:
    .string "GDiadm{END}"

    .global gUnknown_0821060F
gUnknown_0821060F:
    .string "EchoHM{END}"

    .global gUnknown_08210616
gUnknown_08210616:
    .string "EisnMask{END}"

    .global gUnknown_0821061F
gUnknown_0821061F:
    .string "Dummy{END}"

    .global gUnknown_08210625
gUnknown_08210625:
    .string "Dummy{END}"

    .global gUnknown_0821062B
gUnknown_0821062B:
    .string "SteinHM{END}"

    .global gUnknown_08210633
gUnknown_08210633:
    .string "GoldHM{END}"

    .global gUnknown_0821063A
gUnknown_0821063A:
    .string "GesMask{END}"

    .global gUnknown_08210642
gUnknown_08210642:
    .string "AgilHM{END}"

    .global gUnknown_08210649
gUnknown_08210649:
    .string "SchönHM{END}"

    .global gUnknown_08210651
gUnknown_08210651:
    .string "MystAM{END}"

    .global gUnknown_08210658
gUnknown_08210658:
    .string "TauchHM{END}"

    .global gUnknown_08210660
gUnknown_08210660:
    .string "GaiaMask{END}"

    .global gUnknown_08210669
gUnknown_08210669:
    .string "Helm{END}"

    .global gUnknown_0821066E
gUnknown_0821066E:
    .string "VerflHM{END}"

    .global gUnknown_08210676
gUnknown_08210676:
    .string "MschlHM{END}"

    .global gUnknown_0821067E
gUnknown_0821067E:
    .string "StrohHM{END}"

    .global gUnknown_08210686
gUnknown_08210686:
    .string "EisnHM{END}"

    .global gUnknown_0821068D
gUnknown_0821068D:
    .string "Dummy{END}"

    .global gUnknown_08210693
gUnknown_08210693:
    .string "TideHM{END}"

    .global gUnknown_0821069A
gUnknown_0821069A:
    .string "SchdlHM{END}"

    .global gUnknown_082106A2
gUnknown_082106A2:
    .string "PowerHM{END}"

    .global gUnknown_082106AA
gUnknown_082106AA:
    .string "Domino{END}"

    .global gUnknown_082106B1
gUnknown_082106B1:
    .string "HornHM{END}"

    .global gUnknown_082106B8
gUnknown_082106B8:
    .string "BTuch{END}"

    .global gUnknown_082106BE
gUnknown_082106BE:
    .string "Turban{END}"

    .global gUnknown_082106C5
gUnknown_082106C5:
    .string "Dummy{END}"

    .global gUnknown_082106CB
gUnknown_082106CB:
    .string "LiebeHM{END}"

    .global gUnknown_082106D3
gUnknown_082106D3:
    .string "Dummy{END}"

    .global gUnknown_082106D9
gUnknown_082106D9:
    .string "Dummy{END}"

    .global gUnknown_082106DF
gUnknown_082106DF:
    .string "Dummy{END}"

    .global gUnknown_082106E5
gUnknown_082106E5:
    .string "BronzHM{END}"

    .global gUnknown_082106ED
gUnknown_082106ED:
    .string "SHelm{END}"

    .global gUnknown_082106F3
gUnknown_082106F3:
    .string "SonnHM{END}"

    .global gUnknown_082106FA
gUnknown_082106FA:
    .string "WolfHM{END}"

    .global gUnknown_08210701
gUnknown_08210701:
    .string "EisHM{END}"

    .global gUnknown_08210707
gUnknown_08210707:
    .string "Dummy{END}"

    .global gUnknown_0821070D
gUnknown_0821070D:
    .string "Dummy{END}"

    .global gUnknown_08210713
gUnknown_08210713:
    .string "Dummy{END}"

    .global gUnknown_08210719
gUnknown_08210719:
    .string "SternSH{END}"

    .global gUnknown_08210721
gUnknown_08210721:
    .string "Dummy{END}"

    .global gUnknown_08210727
gUnknown_08210727:
    .string "SchdlRG{END}"

    .global gUnknown_0821072F
gUnknown_0821072F:
    .string "HimmlSH{END}"

    .global gUnknown_08210737
gUnknown_08210737:
    .string "Dummy{END}"

    .global gUnknown_0821073D
gUnknown_0821073D:
    .string "Dummy{END}"

    .global gUnknown_08210743
gUnknown_08210743:
    .string "DrachnHM{END}"

    .global gUnknown_0821074C
gUnknown_0821074C:
    .string "DrachnRÜ{END}"

    .global gUnknown_08210755
gUnknown_08210755:
    .string "ClvrRG{END}"

    .global gUnknown_0821075C
gUnknown_0821075C:
    .string "TraumRG{END}"

