    .global gUnknown_0820F0C8
gUnknown_0820F0C8:
    .string "Frosch{END}"

    .global gUnknown_0820F0CF
gUnknown_0820F0CF:
    .string "Ritter{END}"

    .global gUnknown_0820F0D6
gUnknown_0820F0D6:
    .string "Zaubr {END}"

    .global gUnknown_0820F0DD
gUnknown_0820F0DD:
    .string "Zaubr{END}"

    .global gUnknown_0820F0E3
gUnknown_0820F0E3:
    .string "Zaubr{END}"

    .global gUnknown_0820F0E9
gUnknown_0820F0E9:
    .string "Floh{END}"

    .global gUnknown_0820F0EE
gUnknown_0820F0EE:
    .string "EisGrm{END}"

    .global gUnknown_0820F0F5
gUnknown_0820F0F5:
    .string "Stumpf{END}"

    .global gUnknown_0820F0FC
gUnknown_0820F0FC:
    .string "Schädel{END}"

    .global gUnknown_0820F104
gUnknown_0820F104:
    .string "Schnabl{END}"

    .global gUnknown_0820F10C
gUnknown_0820F10C:
    .string "Blop{END}"

    .global gUnknown_0820F111
gUnknown_0820F111:
    .string "Lurch{END}"

    .global gUnknown_0820F117
gUnknown_0820F117:
    .string "Morte{END}"

    .global gUnknown_0820F11D
gUnknown_0820F11D:
    .string "Mortea{END}"

    .global gUnknown_0820F124
gUnknown_0820F124:
    .string "Kralle{END}"

    .global gUnknown_0820F12B
gUnknown_0820F12B:
    .string "Wut{END}"

    .global gUnknown_0820F12F
gUnknown_0820F12F:
    .string "General{END}"

    .global gUnknown_0820F137
gUnknown_0820F137:
    .string "Gremlin{END}"

    .global gUnknown_0820F13F
gUnknown_0820F13F:
    .string "Fetz{END}"

    .global gUnknown_0820F144
gUnknown_0820F144:
    .string "Pog{END}"

    .global gUnknown_0820F148
gUnknown_0820F148:
    .string "Zombie{END}"

    .global gUnknown_0820F14F
gUnknown_0820F14F:
    .string "Schleim{END}"

    .global gUnknown_0820F157
gUnknown_0820F157:
    .string "SReiter{END}"

    .global gUnknown_0820F15F
gUnknown_0820F15F:
    .string "Blurb{END}"

    .global gUnknown_0820F165
gUnknown_0820F165:
    .string "Pikenier{END}"

    .global gUnknown_0820F16E
gUnknown_0820F16E:
    .string "Schütze{END}"

    .global gUnknown_0820F176
gUnknown_0820F176:
    .string "Ruga{END}"

    .global gUnknown_0820F17B
gUnknown_0820F17B:
    .string "KSchwein{END}"

    .global gUnknown_0820F184
gUnknown_0820F184:
    .string "Amöblob{END}"

    .global gUnknown_0820F18C
gUnknown_0820F18C:
    .string "Bulla{END}"

    .global gUnknown_0820F192
gUnknown_0820F192:
    .string "Schabe{END}"

    .global gUnknown_0820F199
gUnknown_0820F199:
    .string "GFliege{END}"

    .global gUnknown_0820F1A1
gUnknown_0820F1A1:
    .string "AugApf{END}"

    .global gUnknown_0820F1A8
gUnknown_0820F1A8:
    .string "Okto{END}"

    .global gUnknown_0820F1AD
gUnknown_0820F1AD:
    .string "Krake{END}"

    .global gUnknown_0820F1B3
gUnknown_0820F1B3:
    .string "SandWurm{END}"

    .global gUnknown_0820F1BC
gUnknown_0820F1BC:
    .string "TGeist{END}"

    .global gUnknown_0820F1C3
gUnknown_0820F1C3:
    .string "SSkorp{END}"

    .global gUnknown_0820F1CA
gUnknown_0820F1CA:
    .string "Magier{END}"

    .global gUnknown_0820F1D1
gUnknown_0820F1D1:
    .string "Stachel{END}"

    .global gUnknown_0820F1D9
gUnknown_0820F1D9:
    .string "BSchütz{END}"

    .global gUnknown_0820F1E1
gUnknown_0820F1E1:
    .string "Fliege{END}"

    .global gUnknown_0820F1E8
gUnknown_0820F1E8:
    .string "LTraeger{END}"

    .global gUnknown_0820F1F1
gUnknown_0820F1F1:
    .string "Kreon{END}"

    .global gUnknown_0820F1F7
gUnknown_0820F1F7:
    .string "Ritter{END}"

    .global gUnknown_0820F1FE
gUnknown_0820F1FE:
    .string "Mothro{END}"

    .global gUnknown_0820F205
gUnknown_0820F205:
    .string "Mote{END}"

    .global gUnknown_0820F20A
gUnknown_0820F20A:
    .string "Soldat{END}"

    .global gUnknown_0820F211
gUnknown_0820F211:
    .string "GrimFlgl{END}"

    .global gUnknown_0820F21A
gUnknown_0820F21A:
    .string "Krabbe{END}"

    .global gUnknown_0820F221
gUnknown_0820F221:
    .string "SchleimX{END}"

    .global gUnknown_0820F22A
gUnknown_0820F22A:
    .string "Myst{END}"

    .global gUnknown_0820F22F
gUnknown_0820F22F:
    .string "RSchleim{END}"

    .global gUnknown_0820F238
gUnknown_0820F238:
    .string "Fisch{END}"

    .global gUnknown_0820F23E
gUnknown_0820F23E:
    .string "ZcknBrsch{END}"

    .global gUnknown_0820F248
gUnknown_0820F248:
    .string "Zwerg{END}"

    .global gUnknown_0820F24E
gUnknown_0820F24E:
    .string "Tronk{END}"

    .global gUnknown_0820F254
gUnknown_0820F254:
    .string "SandBlp{END}"

    .global gUnknown_0820F25C
gUnknown_0820F25C:
    .string "Tentakel{END}"

    .global gUnknown_0820F265
gUnknown_0820F265:
    .string "MSkorp{END}"

    .global gUnknown_0820F26C
gUnknown_0820F26C:
    .string "RugaX{END}"

    .global gUnknown_0820F272
gUnknown_0820F272:
    .string "PikenierX{END}"

    .global gUnknown_0820F27C
gUnknown_0820F27C:
    .string "SchützeX{END}"

    .global gUnknown_0820F285
gUnknown_0820F285:
    .string "Geist{END}"

    .global gUnknown_0820F28B
gUnknown_0820F28B:
    .string "RugaX{END}"

    .global gUnknown_0820F291
gUnknown_0820F291:
    .string "BlumeX{END}"

    .global gUnknown_0820F298
gUnknown_0820F298:
    .string "HornKröte{END}"

    .global gUnknown_0820F2A2
gUnknown_0820F2A2:
    .string "Mote{END}"

    .global gUnknown_0820F2A7
gUnknown_0820F2A7:
    .string "Zerl{END}"

    .global gUnknown_0820F2AC
gUnknown_0820F2AC:
    .string "Mothro{END}"

    .global gUnknown_0820F2B3
gUnknown_0820F2B3:
    .string "PKäfer{END}"

    .global gUnknown_0820F2BA
gUnknown_0820F2BA:
    .string "Chimäre{END}"

    .global gUnknown_0820F2C2
gUnknown_0820F2C2:
    .string "Fungus{END}"

    .global gUnknown_0820F2C9
gUnknown_0820F2C9:
    .string "G-Zwerg{END}"

    .global gUnknown_0820F2D1
gUnknown_0820F2D1:
    .string "KSchabe{END}"

    .global gUnknown_0820F2D9
gUnknown_0820F2D9:
    .string "Phoenix{END}"

    .global gUnknown_0820F2E1
gUnknown_0820F2E1:
    .string "Snsnmann{END}"

    .global gUnknown_0820F2EA
gUnknown_0820F2EA:
    .string "Zauberer{END}"

    .global gUnknown_0820F2F3
gUnknown_0820F2F3:
    .string "Kröte{END}"

    .global gUnknown_0820F2F9
gUnknown_0820F2F9:
    .string "Schrat{END}"

    .global gUnknown_0820F300
gUnknown_0820F300:
    .string "Goda{END}"

    .global gUnknown_0820F305
gUnknown_0820F305:
    .string "Zog{END}"

    .global gUnknown_0820F309
gUnknown_0820F309:
    .string "Jade{END}"

    .global gUnknown_0820F30E
gUnknown_0820F30E:
    .string "Göttin{END}"

    .global gUnknown_0820F315
gUnknown_0820F315:
    .string "Göttin{END}"

    .global gUnknown_0820F31C
gUnknown_0820F31C:
    .string "Sara{END}"

    .global gUnknown_0820F321
gUnknown_0820F321:
    .string "Zaubr{END}"

    .global gUnknown_0820F327
gUnknown_0820F327:
    .string "Zoom{END}"

    .global gUnknown_0820F32C
gUnknown_0820F32C:
    .string "Gargyl{END}"

    .global gUnknown_0820F333
gUnknown_0820F333:
    .string "GRitter{END}"

    .global gUnknown_0820F33B
gUnknown_0820F33B:
    .string "Schatten{END}"

    .global gUnknown_0820F344
gUnknown_0820F344:
    .string "GeistX{END}"

    .global gUnknown_0820F34B
gUnknown_0820F34B:
    .string "Spinne{END}"

    .global gUnknown_0820F352
gUnknown_0820F352:
    .string "Lodern{END}"

    .global gUnknown_0820F359
gUnknown_0820F359:
    .string "GGesp{END}"

    .global gUnknown_0820F35F
gUnknown_0820F35F:
    .string "EKiste{END}"

    .global gUnknown_0820F366
gUnknown_0820F366:
    .string "Göttin{END}"

    .global gUnknown_0820F36D
gUnknown_0820F36D:
    .string "DFloh{END}"

    .global gUnknown_0820F373
gUnknown_0820F373:
    .string "Krabbe{END}"

    .global gUnknown_0820F37A
gUnknown_0820F37A:
    .string "Blume{END}"

    .global gUnknown_0820F380
gUnknown_0820F380:
    .string "GSchleim{END}"

    .global gUnknown_0820F389
gUnknown_0820F389:
    .string "MSchleim{END}"

    .global gUnknown_0820F392
gUnknown_0820F392:
    .string "Buzzer{END}"

    .global gUnknown_0820F399
gUnknown_0820F399:
    .string "Krcher{END}"

    .global gUnknown_0820F3A0
gUnknown_0820F3A0:
    .string "Ruga{END}"

    .global gUnknown_0820F3A5
gUnknown_0820F3A5:
    .string "Ronk{END}"

    .global gUnknown_0820F3AA
gUnknown_0820F3AA:
    .string "HundshaiX{END}"

    .global gUnknown_0820F3B4
gUnknown_0820F3B4:
    .string "LodernX{END}"

    .global gUnknown_0820F3BC
gUnknown_0820F3BC:
    .string "AmeblobX{END}"

    .global gUnknown_0820F3C5
gUnknown_0820F3C5:
    .string "Nautulis{END}"

    .global gUnknown_0820F3CE
gUnknown_0820F3CE:
    .string "Witwe{END}"

    .global gUnknown_0820F3D4
gUnknown_0820F3D4:
    .string "MFloh{END}"

    .global gUnknown_0820F3DA
gUnknown_0820F3DA:
    .string "KrcherX{END}"

    .global gUnknown_0820F3E2
gUnknown_0820F3E2:
    .string "Mimikri{END}"

    .global gUnknown_0820F3EA
gUnknown_0820F3EA:
    .string "KSchweinX{END}"

    .global gUnknown_0820F3F4
gUnknown_0820F3F4:
    .string "FeuerKopf{END}"

    .global gUnknown_0820F3FE
gUnknown_0820F3FE:
    .string "Bully{END}"

    .global gUnknown_0820F404
gUnknown_0820F404:
    .string "Klaue{END}"

    .global gUnknown_0820F40A
gUnknown_0820F40A:
    .string "KrabbeX{END}"

    .global gUnknown_0820F412
gUnknown_0820F412:
    .string "KreonX{END}"

    .global gUnknown_0820F419
gUnknown_0820F419:
    .string "Bain{END}"

    .global gUnknown_0820F41E
gUnknown_0820F41E:
    .string "DReiter{END}"

    .global gUnknown_0820F426
gUnknown_0820F426:
    .string "Ghul{END}"

    .global gUnknown_0820F42B
gUnknown_0820F42B:
    .string "Kaktus{END}"

    .global gUnknown_0820F432
gUnknown_0820F432:
    .string "KaktusX{END}"

    .global gUnknown_0820F43A
gUnknown_0820F43A:
    .string "ICU{END}"

    .global gUnknown_0820F43E
gUnknown_0820F43E:
    .string "Wesen{END}"

    .global gUnknown_0820F444
gUnknown_0820F444:
    .string "DRitter{END}"

