    .align 2
    .global gUnknown_08214330
gUnknown_08214330:
    .word gUnknown_0820EA00 @ 0 / 0x0
    .word gUnknown_0820EAB0 @ 1 / 0x1
    .word gUnknown_0820EB42 @ 2 / 0x2
    .word gUnknown_0820EBE3 @ 3 / 0x3
    .word gUnknown_0820EC39 @ 4 / 0x4
    .word gUnknown_0820ECA0 @ 5 / 0x5
    .word gUnknown_0820ECF2 @ 6 / 0x6
    .word gUnknown_0820ED4F @ 7 / 0x7
    .word gUnknown_0820EDB3 @ 8 / 0x8
    .word gUnknown_0820EE1C @ 9 / 0x9
    .word gUnknown_0820EE68 @ 10 / 0xA
    .word gUnknown_0820EE9F @ 11 / 0xB
    .word gUnknown_0820EEE7 @ 12 / 0xC
    .word gUnknown_0820EF3D @ 13 / 0xD
    .word gUnknown_0820EFA4 @ 14 / 0xE
    .word gUnknown_0820EFE4 @ 15 / 0xF
    .word gUnknown_0820F02B @ 16 / 0x10
    .word gUnknown_0820F053 @ 17 / 0x11
    .word gUnknown_0820F072 @ 18 / 0x12
    .word gUnknown_0820F09C @ 19 / 0x13
