    .global gUnknown_0820FD96
gUnknown_0820FD96:
    .string "70G{END}"

    .global gUnknown_0820FD9A
gUnknown_0820FD9A:
    .string "150G{END}"

    .global gUnknown_0820FD9F
gUnknown_0820FD9F:
    .string "300G{END}"

    .global gUnknown_0820FDA4
gUnknown_0820FDA4:
    .string "650G{END}"

    .global gUnknown_0820FDA9
gUnknown_0820FDA9:
    .string "900G{END}"

    .global gUnknown_0820FDAE
gUnknown_0820FDAE:
    .string "1200G{END}"

    .global gUnknown_0820FDB4
gUnknown_0820FDB4:
    .string "2000G{END}"

    .global gUnknown_0820FDBA
gUnknown_0820FDBA:
    .string "3000G{END}"

    .global gUnknown_0820FDC0
gUnknown_0820FDC0:
    .string "Kraut{END}"

    .global gUnknown_0820FDC6
gUnknown_0820FDC6:
    .string "Heil{END}"

    .global gUnknown_0820FDCB
gUnknown_0820FDCB:
    .string "Ggngft{END}"

    .global gUnknown_0820FDD2
gUnknown_0820FDD2:
    .string "Eichel{END}"

    .global gUnknown_0820FDD9
gUnknown_0820FDD9:
    .string "MTraen{END}"

    .global gUnknown_0820FDE0
gUnknown_0820FDE0:
    .string "VTraen{END}"

    .global gUnknown_0820FDE7
gUnknown_0820FDE7:
    .string "Charm{END}"

    .global gUnknown_0820FDED
gUnknown_0820FDED:
    .string "Lebn2{END}"

    .global gUnknown_0820FDF3
gUnknown_0820FDF3:
    .string "TTref1{END}"

    .global gUnknown_0820FDFA
gUnknown_0820FDFA:
    .string "TTref2{END}"

    .global gUnknown_0820FE01
gUnknown_0820FE01:
    .string "Nebel{END}"

    .global gUnknown_0820FE07
gUnknown_0820FE07:
    .string "Whskrs{END}"

    .global gUnknown_0820FE0E
gUnknown_0820FE0E:
    .string "Wurm{END}"

    .global gUnknown_0820FE13
gUnknown_0820FE13:
    .string "Wurm2{END}"

    .global gUnknown_0820FE19
gUnknown_0820FE19:
    .string "Schrmp{END}"

    .global gUnknown_0820FE20
gUnknown_0820FE20:
    .string "SIgel{END}"

    .global gUnknown_0820FE26
gUnknown_0820FE26:
    .string "Mschl{END}"

    .global gUnknown_0820FE2C
gUnknown_0820FE2C:
    .string "Apfel{END}"

    .global gUnknown_0820FE32
gUnknown_0820FE32:
    .string "ProtnA{END}"

    .global gUnknown_0820FE39
gUnknown_0820FE39:
    .string "Geweih{END}"

    .global gUnknown_0820FE40
gUnknown_0820FE40:
    .string "WFlsch{END}"

    .global gUnknown_0820FE47
gUnknown_0820FE47:
    .string "Leben{END}"

    .global gUnknown_0820FE4D
gUnknown_0820FE4D:
    .string "Nägel{END}"

    .global gUnknown_0820FE53
gUnknown_0820FE53:
    .string "Flsch{END}"

    .global gUnknown_0820FE59
gUnknown_0820FE59:
    .string "BStn{END}"

    .global gUnknown_0820FE5E
gUnknown_0820FE5E:
    .string "FStn{END}"

    .global gUnknown_0820FE63
gUnknown_0820FE63:
    .string "CStn{END}"

    .global gUnknown_0820FE68
gUnknown_0820FE68:
    .string "Rauch{END}"

    .global gUnknown_0820FE6E
gUnknown_0820FE6E:
    .string "TdKuss{END}"

    .global gUnknown_0820FE75
gUnknown_0820FE75:
    .string "Heil2{END}"

    .global gUnknown_0820FE7B
gUnknown_0820FE7B:
    .string "ProtnB{END}"

    .global gUnknown_0820FE82
gUnknown_0820FE82:
    .string "Schrp{END}"

    .global gUnknown_0820FE88
gUnknown_0820FE88:
    .string "WTrnk{END}"

    .global gUnknown_0820FE8E
gUnknown_0820FE8E:
    .string "STrnk{END}"

    .global gUnknown_0820FE94
gUnknown_0820FE94:
    .string "StGlas{END}"

    .global gUnknown_0820FE9B
gUnknown_0820FE9B:
    .string "ExpKfr{END}"

    .global gUnknown_0820FEA2
gUnknown_0820FEA2:
    .string "Slab{END}"

    .global gUnknown_0820FEA7
gUnknown_0820FEA7:
    .string "LFnger{END}"

    .global gUnknown_0820FEAE
gUnknown_0820FEAE:
    .string "ESchl{END}"

    .global gUnknown_0820FEB4
gUnknown_0820FEB4:
    .string "RWssr{END}"

    .global gUnknown_0820FEBA
gUnknown_0820FEBA:
    .string "Kutsch{END}"

    .global gUnknown_0820FEC1
gUnknown_0820FEC1:
    .string "HSchuh{END}"

    .global gUnknown_0820FEC8
gUnknown_0820FEC8:
    .string "ATrnk{END}"

    .global gUnknown_0820FECE
gUnknown_0820FECE:
    .string "GTrnk{END}"

    .global gUnknown_0820FED4
gUnknown_0820FED4:
    .string "ETrnk{END}"

    .global gUnknown_0820FEDA
gUnknown_0820FEDA:
    .string "DrSoul{END}"

    .global gUnknown_0820FEE1
gUnknown_0820FEE1:
    .string "DrWarp{END}"

    .global gUnknown_0820FEE8
gUnknown_0820FEE8:
    .string "PlceBo{END}"

    .global gUnknown_0820FEEF
gUnknown_0820FEEF:
    .string "Ggmttl{END}"

    .global gUnknown_0820FEF6
gUnknown_0820FEF6:
    .string "WsKrg{END}"

    .global gUnknown_0820FEFC
gUnknown_0820FEFC:
    .string "Säge{END}"

    .global gUnknown_0820FF01
gUnknown_0820FF01:
    .string "Tafel{END}"

    .global gUnknown_0820FF07
gUnknown_0820FF07:
    .string "Ring{END}"

    .global gUnknown_0820FF0C
gUnknown_0820FF0C:
    .string "WsKrg{END}"

    .global gUnknown_0820FF12
gUnknown_0820FF12:
    .string "RSSchl{END}"

    .global gUnknown_0820FF19
gUnknown_0820FF19:
    .string "Papier{END}"

    .global gUnknown_0820FF20
gUnknown_0820FF20:
    .string "Schwur{END}"

    .global gUnknown_0820FF27
gUnknown_0820FF27:
    .string "GBeutl{END}"

    .global gUnknown_0820FF2E
gUnknown_0820FF2E:
    .string "SwPlvr{END}"

    .global gUnknown_0820FF35
gUnknown_0820FF35:
    .string "LSchl{END}"

    .global gUnknown_0820FF3B
gUnknown_0820FF3B:
    .string "DkSchl{END}"

    .global gUnknown_0820FF42
gUnknown_0820FF42:
    .string "Spiegl{END}"

    .global gUnknown_0820FF49
gUnknown_0820FF49:
    .string "Buch{END}"

    .global gUnknown_0820FF4E
gUnknown_0820FF4E:
    .string "Srdine{END}"

    .global gUnknown_0820FF55
gUnknown_0820FF55:
    .string "Makrl{END}"

    .global gUnknown_0820FF5B
gUnknown_0820FF5B:
    .string "SeeZng{END}"

    .global gUnknown_0820FF62
gUnknown_0820FF62:
    .string "Forlle{END}"

    .global gUnknown_0820FF69
gUnknown_0820FF69:
    .string "KFsch{END}"

    .global gUnknown_0820FF6F
gUnknown_0820FF6F:
    .string "Schnp{END}"

    .global gUnknown_0820FF75
gUnknown_0820FF75:
    .string "Thunf{END}"

    .global gUnknown_0820FF7B
gUnknown_0820FF7B:
    .string "Puffer{END}"

    .global gUnknown_0820FF82
gUnknown_0820FF82:
    .string "Rute1{END}"

    .global gUnknown_0820FF88
gUnknown_0820FF88:
    .string "Rute2{END}"

    .global gUnknown_0820FF8E
gUnknown_0820FF8E:
    .string "Rute3{END}"

    .global gUnknown_0820FF94
gUnknown_0820FF94:
    .string "Rute4{END}"

    .global gUnknown_0820FF9A
gUnknown_0820FF9A:
    .string "Rute5{END}"

    .global gUnknown_0820FFA0
gUnknown_0820FFA0:
    .string "EErz{END}"

    .global gUnknown_0820FFA5
gUnknown_0820FFA5:
    .string "Shlssl{END}"

    .global gUnknown_0820FFAC
gUnknown_0820FFAC:
    .string "Vitamn{END}"

    .global gUnknown_0820FFB3
gUnknown_0820FFB3:
    .string "Statue{END}"

    .global gUnknown_0820FFBA
gUnknown_0820FFBA:
    .string "AltEi{END}"

    .global gUnknown_0820FFC0
gUnknown_0820FFC0:
    .string "Güter{END}"

    .global gUnknown_0820FFC6
gUnknown_0820FFC6:
    .string "Ei{END}"

    .global gUnknown_0820FFC9
gUnknown_0820FFC9:
    .string "Sphäre{END}"

    .global gUnknown_0820FFD0
gUnknown_0820FFD0:
    .string "Kiemen{END}"

    .global gUnknown_0820FFD7
gUnknown_0820FFD7:
    .string "GBar{END}"

    .global gUnknown_0820FFDC
gUnknown_0820FFDC:
    .string "Eiszpf{END}"

    .global gUnknown_0820FFE3
gUnknown_0820FFE3:
    .string "Flöte{END}"

    .global gUnknown_0820FFE9
gUnknown_0820FFE9:
    .string "Pass{END}"

    .global gUnknown_0820FFEE
gUnknown_0820FFEE:
    .string "KTeile{END}"

    .global gUnknown_0820FFF5
gUnknown_0820FFF5:
    .string "Teile{END}"

    .global gUnknown_0820FFFB
gUnknown_0820FFFB:
    .string "DHrz{END}"

    .global gUnknown_08210000
gUnknown_08210000:
    .string "Karte{END}"

    .global gUnknown_08210006
gUnknown_08210006:
    .string "Liste{END}"

    .global gUnknown_0821000C
gUnknown_0821000C:
    .string "Wasnds{END}"

    .global gUnknown_08210013
gUnknown_08210013:
    .string "Notiz1{END}"

    .global gUnknown_0821001A
gUnknown_0821001A:
    .string "Notiz2{END}"

    .global gUnknown_08210021
gUnknown_08210021:
    .string "EKlaue{END}"

    .global gUnknown_08210028
gUnknown_08210028:
    .string "ZSchl{END}"

    .global gUnknown_0821002E
gUnknown_0821002E:
    .string "BRang{END}"

    .global gUnknown_08210034
gUnknown_08210034:
    .string "HmSchl{END}"

    .global gUnknown_0821003B
gUnknown_0821003B:
    .string "Bblfsh{END}"

    .global gUnknown_08210042
gUnknown_08210042:
    .string "Kissen{END}"

    .global gUnknown_08210049
gUnknown_08210049:
    .string "Maestro{END}"

    .global gUnknown_08210051
gUnknown_08210051:
    .string "GFlge{END}"

    .global gUnknown_08210057
gUnknown_08210057:
    .string "Öl{END}"

    .global gUnknown_0821005A
gUnknown_0821005A:
    .string "MHeil{END}"

    .global gUnknown_08210060
gUnknown_08210060:
    .string "Melone{END}"

    .global gUnknown_08210067
gUnknown_08210067:
    .string "Früchte{END}"

    .global gUnknown_0821006F
gUnknown_0821006F:
    .string "PFisch{END}"

    .global gUnknown_08210076
gUnknown_08210076:
    .string "Wurzel{END}"

    .global gUnknown_0821007D
gUnknown_0821007D:
    .string "KNuss{END}"

    .global gUnknown_08210083
gUnknown_08210083:
    .string "WGew{END}"

    .global gUnknown_08210088
gUnknown_08210088:
    .string "Elixier{END}"

    .global gUnknown_08210090
gUnknown_08210090:
    .string "Kraut  X9{END}"

    .global gUnknown_0821009A
gUnknown_0821009A:
    .string "Ggift  X9{END}"

    .global gUnknown_082100A4
gUnknown_082100A4:
    .string "Tropf  X9{END}"

    .global gUnknown_082100AE
gUnknown_082100AE:
    .string "Chrm   X9{END}"

    .global gUnknown_082100B8
gUnknown_082100B8:
    .string "Heil   X9{END}"

    .global gUnknown_082100C2
gUnknown_082100C2:
    .string "Eichl  X9{END}"

