    .global gUnknown_0820FB58
gUnknown_0820FB58:
    .string "Wo?{END}"

    .global gUnknown_0820FB5C
gUnknown_0820FB5C:
    .string "Dogen{END}"

    .global gUnknown_0820FB62
gUnknown_0820FB62:
    .string "Nanai{END}"

    .global gUnknown_0820FB68
gUnknown_0820FB68:
    .string "Winlan{END}"

    .global gUnknown_0820FB6F
gUnknown_0820FB6F:
    .string "Romero{END}"

    .global gUnknown_0820FB76
gUnknown_0820FB76:
    .string "Gust{END}"

    .global gUnknown_0820FB7B
gUnknown_0820FB7B:
    .string "Camlon{END}"

    .global gUnknown_0820FB82
gUnknown_0820FB82:
    .string "Nada{END}"

    .global gUnknown_0820FB87
gUnknown_0820FB87:
    .string "Tantar{END}"

    .global gUnknown_0820FB8E
gUnknown_0820FB8E:
    .string "Tuntar{END}"

    .global gUnknown_0820FB95
gUnknown_0820FB95:
    .string "Agua{END}"

    .global gUnknown_0820FB9A
gUnknown_0820FB9A:
    .string "Auria{END}"

    .global gUnknown_0820FBA0
gUnknown_0820FBA0:
    .string "Bleak{END}"

    .global gUnknown_0820FBA6
gUnknown_0820FBA6:
    .string "Arad{END}"

    .global gUnknown_0820FBAB
gUnknown_0820FBAB:
    .string "Spring{END}"

    .global gUnknown_0820FBB2
gUnknown_0820FBB2:
    .string "Tunlan{END}"

    .global gUnknown_0820FBB9
gUnknown_0820FBB9:
    .string "Gant{END}"

    .global gUnknown_0820FBBE
gUnknown_0820FBBE:
    .string "Scande{END}"

    .global gUnknown_0820FBC5
gUnknown_0820FBC5:
    .string "Carmen{END}"

    .global gUnknown_0820FBCC
gUnknown_0820FBCC:
    .string "Gramor{END}"

    .global gUnknown_0820FBD3
gUnknown_0820FBD3:
    .string "Wisdon{END}"

    .global gUnknown_0820FBDA
gUnknown_0820FBDA:
    .string "Karma{END}"

    .global gUnknown_0820FBE0
gUnknown_0820FBE0:
    .string "Prima{END}"

    .global gUnknown_0820FBE6
gUnknown_0820FBE6:
    .string "Krypt{END}"

    .global gUnknown_0820FBEC
gUnknown_0820FBEC:
    .string "Nabal{END}"

    .global gUnknown_0820FBF2
gUnknown_0820FBF2:
    .string "Tock{END}"

    .global gUnknown_0820FBF7
gUnknown_0820FBF7:
    .string "Spyre{END}"

    .global gUnknown_0820FBFD
gUnknown_0820FBFD:
    .string "Obelisk{END}"

    .global gUnknown_0820FC05
gUnknown_0820FC05:
    .string "Pagode{END}"

    .global gUnknown_0820FC0C
gUnknown_0820FC0C:
    .string "DrachnPalast{END}"

    .global gUnknown_0820FC19
gUnknown_0820FC19:
    .string "DrachenTmpl{END}"

    .global gUnknown_0820FC25
gUnknown_0820FC25:
    .string "Ramui-Wald{END}"

    .global gUnknown_0820FC30
gUnknown_0820FC30:
    .string "Aura-Höhle{END}"

    .global gUnknown_0820FC3B
gUnknown_0820FC3B:
    .string "Lament-Wald{END}"

    .global gUnknown_0820FC47
gUnknown_0820FC47:
    .string "Gaia-Tempel{END}"

    .global gUnknown_0820FC53
gUnknown_0820FC53:
    .string "Höhlen-See{END}"

    .global gUnknown_0820FC5E
gUnknown_0820FC5E:
    .string "Schrein-See{END}"

    .global gUnknown_0820FC6A
gUnknown_0820FC6A:
    .string "Höhlenkap{END}"

    .global gUnknown_0820FC74
gUnknown_0820FC74:
    .string "Ruhige Höhle{END}"

    .global gUnknown_0820FC81
gUnknown_0820FC81:
    .string "GrimFowl Wld{END}"

    .global gUnknown_0820FC8E
gUnknown_0820FC8E:
    .string "DunkleD Fort{END}"

    .global gUnknown_0820FC9B
gUnknown_0820FC9B:
    .string "Geheimbasis{END}"

    .global gUnknown_0820FCA7
gUnknown_0820FCA7:
    .string "Stein-Robot{END}"

    .global gUnknown_0820FCB3
gUnknown_0820FCB3:
    .string "DunkleD Schf{END}"

    .global gUnknown_0820FCC0
gUnknown_0820FCC0:
    .string "L & D Höhle{END}"

    .global gUnknown_0820FCCC
gUnknown_0820FCCC:
    .string "Verst. Fort{END}"

    .global gUnknown_0820FCD8
gUnknown_0820FCD8:
    .string "L & D Turm{END}"

    .global gUnknown_0820FCE3
gUnknown_0820FCE3:
    .string "Meeresvulkan{END}"

    .global gUnknown_0820FCF0
gUnknown_0820FCF0:
    .string "Teufelsturm{END}"

    .global gUnknown_0820FCFC
gUnknown_0820FCFC:
    .string "Wildnis{END}"

    .global gUnknown_0820FD04
gUnknown_0820FD04:
    .string "AmazonDung{END}"

    .global gUnknown_0820FD0F
gUnknown_0820FD0F:
    .string "Feenwald{END}"

    .global gUnknown_0820FD18
gUnknown_0820FD18:
    .string "AmazonStadt{END}"

    .global gUnknown_0820FD24
gUnknown_0820FD24:
    .string "Lab{END}"

    .global gUnknown_0820FD28
gUnknown_0820FD28:
    .string "Mauseloch{END}"

    .global gUnknown_0820FD32
gUnknown_0820FD32:
    .string "Froschhöhle{END}"

    .global gUnknown_0820FD3E
gUnknown_0820FD3E:
    .string "Südhöhle{END}"

    .global gUnknown_0820FD47
gUnknown_0820FD47:
    .string "Südl. Burg{END}"

    .global gUnknown_0820FD52
gUnknown_0820FD52:
    .string "Traumstadt{END}"

    .global gUnknown_0820FD5D
gUnknown_0820FD5D:
    .string "W-Sammler{END}"

    .global gUnknown_0820FD67
gUnknown_0820FD67:
    .string "W-Sammlerin{END}"

    .global gUnknown_0820FD73
gUnknown_0820FD73:
    .string "Wüstenhöhle{END}"

    .global gUnknown_0820FD7F
gUnknown_0820FD7F:
    .string "Winterhöhle{END}"

    .global gUnknown_0820FD8B
gUnknown_0820FD8B:
    .string "Geheimraum{END}"

