    .global gUnknown_08210815
gUnknown_08210815:
    .string "Cura1{END}"

    .global gUnknown_0821081B
gUnknown_0821081B:
    .string "Vert{END}"

    .global gUnknown_08210820
gUnknown_08210820:
    .string "Inakt{END}"

    .global gUnknown_08210826
gUnknown_08210826:
    .string "PlGl{END}"

    .global gUnknown_0821082B
gUnknown_0821082B:
    .string "PlAng{END}"

    .global gUnknown_08210831
gUnknown_08210831:
    .string "Cura2{END}"

    .global gUnknown_08210837
gUnknown_08210837:
    .string "Halt{END}"

    .global gUnknown_0821083C
gUnknown_0821083C:
    .string "PlAgi{END}"

    .global gUnknown_08210842
gUnknown_08210842:
    .string "TEng1{END}"

    .global gUnknown_08210848
gUnknown_08210848:
    .string "Cura3{END}"

    .global gUnknown_0821084E
gUnknown_0821084E:
    .string "Erwach{END}"

    .global gUnknown_08210855
gUnknown_08210855:
    .string "Heil{END}"

    .global gUnknown_0821085A
gUnknown_0821085A:
    .string "Schild{END}"

    .global gUnknown_08210861
gUnknown_08210861:
    .string "Cura4{END}"

    .global gUnknown_08210867
gUnknown_08210867:
    .string "TEng2{END}"

    .global gUnknown_0821086D
gUnknown_0821086D:
    .string "VertX{END}"

    .global gUnknown_08210873
gUnknown_08210873:
    .string "ZBann{END}"

    .global gUnknown_08210879
gUnknown_08210879:
    .string "Entzau{END}"

    .global gUnknown_08210880
gUnknown_08210880:
    .string "ErwchX{END}"

    .global gUnknown_08210887
gUnknown_08210887:
    .string "CuraX{END}"

    .global gUnknown_0821088D
gUnknown_0821088D:
    .string "Wand{END}"

    .global gUnknown_08210892
gUnknown_08210892:
    .string "TEngX{END}"

    .global gUnknown_08210898
gUnknown_08210898:
    .string "Licht{END}"

    .global gUnknown_0821089E
gUnknown_0821089E:
    .string "Funke{END}"

    .global gUnknown_082108A4
gUnknown_082108A4:
    .string "Kälte{END}"

    .global gUnknown_082108AA
gUnknown_082108AA:
    .string "35{END}"

    .global gUnknown_082108AD
gUnknown_082108AD:
    .string "Para{END}"

    .global gUnknown_082108B2
gUnknown_082108B2:
    .string "TSaug{END}"

    .global gUnknown_082108B8
gUnknown_082108B8:
    .string "TStrf{END}"

    .global gUnknown_082108BE
gUnknown_082108BE:
    .string "Flamm{END}"

    .global gUnknown_082108C4
gUnknown_082108C4:
    .string "Röst{END}"

    .global gUnknown_082108C9
gUnknown_082108C9:
    .string "Frost{END}"

    .global gUnknown_082108CF
gUnknown_082108CF:
    .string "55{END}"

    .global gUnknown_082108D2
gUnknown_082108D2:
    .string "FBall{END}"

    .global gUnknown_082108D8
gUnknown_082108D8:
    .string "LSturm{END}"

    .global gUnknown_082108DF
gUnknown_082108DF:
    .string "Chill{END}"

    .global gUnknown_082108E5
gUnknown_082108E5:
    .string "95{END}"

    .global gUnknown_082108E8
gUnknown_082108E8:
    .string "DSturm{END}"

    .global gUnknown_082108EF
gUnknown_082108EF:
    .string "Eis{END}"

    .global gUnknown_082108F3
gUnknown_082108F3:
    .string "FDra{END}"

    .global gUnknown_082108F8
gUnknown_082108F8:
    .string "EisX{END}"

    .global gUnknown_082108FD
gUnknown_082108FD:
    .string "FeuerX{END}"

    .global gUnknown_08210904
gUnknown_08210904:
    .string "BolzX{END}"

    .global gUnknown_0821090A
gUnknown_0821090A:
    .string "ASaug{END}"

    .global gUnknown_08210910
gUnknown_08210910:
    .string "???1{END}"

    .global gUnknown_08210915
gUnknown_08210915:
    .string "Komet{END}"

    .global gUnknown_0821091B
gUnknown_0821091B:
    .string "???2{END}"

    .global gUnknown_08210920
gUnknown_08210920:
    .string "???3{END}"

    .global gUnknown_08210925
gUnknown_08210925:
    .string "???4{END}"

    .global gUnknown_0821092A
gUnknown_0821092A:
    .string "???5{END}"

    .global gUnknown_0821092F
gUnknown_0821092F:
    .string "???6{END}"

    .global gUnknown_08210934
gUnknown_08210934:
    .string "???7{END}"

    .global gUnknown_08210939
gUnknown_08210939:
    .string "Cura1{END}"

    .global gUnknown_0821093F
gUnknown_0821093F:
    .string "ErwchX{END}"

    .global gUnknown_08210946
gUnknown_08210946:
    .string "Edd{END}"

    .global gUnknown_0821094A
gUnknown_0821094A:
    .string "EddX{END}"

    .global gUnknown_0821094F
gUnknown_0821094F:
    .string "Eco{END}"

    .global gUnknown_08210953
gUnknown_08210953:
    .string "EcoX{END}"

    .global gUnknown_08210958
gUnknown_08210958:
    .string "???8{END}"

    .global gUnknown_0821095D
gUnknown_0821095D:
    .string "???9{END}"

    .global gUnknown_08210962
gUnknown_08210962:
    .string "???10{END}"

    .global gUnknown_08210968
gUnknown_08210968:
    .string "???12{END}"

    .global gUnknown_0821096E
gUnknown_0821096E:
    .string "???13{END}"

    .global gUnknown_08210974
gUnknown_08210974:
    .string "???14{END}"

    .global gUnknown_0821097A
gUnknown_0821097A:
    .string "???15{END}"

    .global gUnknown_08210980
gUnknown_08210980:
    .string "???16{END}"

    .global gUnknown_08210986
gUnknown_08210986:
    .string "???17{END}"

    .global gUnknown_0821098C
gUnknown_0821098C:
    .string "TEngX{END}"

    .global gUnknown_08210992
gUnknown_08210992:
    .string "???18{END}"

    .global gUnknown_08210998
gUnknown_08210998:
    .string "???19{END}"

    .global gUnknown_0821099E
gUnknown_0821099E:
    .string "Bomb{END}"

    .global gUnknown_082109A3
gUnknown_082109A3:
    .string "Boom{END}"

    .global gUnknown_082109A8
gUnknown_082109A8:
    .string "Warp{END}"

    .global gUnknown_082109AD
gUnknown_082109AD:
    .string "Flucht{END}"

    .global gUnknown_082109B4
gUnknown_082109B4:
    .string "Blast{END}"

    .global gUnknown_082109BA
gUnknown_082109BA:
    .string "Ausg{END}"

    .global gUnknown_082109BF
gUnknown_082109BF:
    .string "Nova{END}"

    .global gUnknown_082109C4
gUnknown_082109C4:
    .string "NovaX{END}"

    .global gUnknown_082109CA
gUnknown_082109CA:
    .string "???20{END}"

    .global gUnknown_082109D0
gUnknown_082109D0:
    .string "???21{END}"

