    .global gUnknown_0820F44C
gUnknown_0820F44C:
    .string "Stellt 50 HP wieder her{END}"

    .global gUnknown_0820F464
gUnknown_0820F464:
    .string "Kurz bessere Verteidigung{END}"

    .global gUnknown_0820F47E
gUnknown_0820F47E:
    .string "Verlangsamt Gegner{END}"

    .global gUnknown_0820F491
gUnknown_0820F491:
    .string "Kurz mehr Glück{END}"

    .global gUnknown_0820F4A1
gUnknown_0820F4A1:
    .string "Kurz mehr Angriffskraft{END}"

    .global gUnknown_0820F4B9
gUnknown_0820F4B9:
    .string "Stellt 100 HP wieder her{END}"

    .global gUnknown_0820F4D2
gUnknown_0820F4D2:
    .string "Hält Gegnerbewegung an{END}"

    .global gUnknown_0820F4E9
gUnknown_0820F4E9:
    .string "Kurz bessere Agilität{END}"

    .global gUnknown_0820F4FF
gUnknown_0820F4FF:
    .string "T-Engel LV1 Einzelner Feind{END}"

    .global gUnknown_0820F51B
gUnknown_0820F51B:
    .string "Stellt 250 HP wieder her{END}"

    .global gUnknown_0820F534
gUnknown_0820F534:
    .string "Heilt Status “Btbt“ HP1{END}"

    .global gUnknown_0820F54C
gUnknown_0820F54C:
    .string "Heilt jeden abnormen Status{END}"

    .global gUnknown_0820F568
gUnknown_0820F568:
    .string "Weniger Schaden durch Magie{END}"

    .global gUnknown_0820F584
gUnknown_0820F584:
    .string "Heilt HP vollständig{END}"

    .global gUnknown_0820F599
gUnknown_0820F599:
    .string "T-Engel LV2 Einzelner Feind{END}"

    .global gUnknown_0820F5B5
gUnknown_0820F5B5:
    .string "Bessere Verteidigung Gruppe{END}"

    .global gUnknown_0820F5D1
gUnknown_0820F5D1:
    .string "Versiegelt kurz GegnerMagie{END}"

    .global gUnknown_0820F5ED
gUnknown_0820F5ED:
    .string "Verhindert 1 Mal Gegnermagie{END}"

    .global gUnknown_0820F60A
gUnknown_0820F60A:
    .string "Heilt Status “Btbt“ vollständig{END}"

    .global gUnknown_0820F62A
gUnknown_0820F62A:
    .string "Heilt Gruppen-HP um 250 Pkte{END}"

    .global gUnknown_0820F647
gUnknown_0820F647:
    .string "Reflektiert Gegnermagie 1 Mal{END}"

    .global gUnknown_0820F665
gUnknown_0820F665:
    .string "T-Engel LV3 Gegnergruppe{END}"

    .global gUnknown_0820F67E
gUnknown_0820F67E:
    .string "Feuer LV1 Einzelner Feind{END}"

    .global gUnknown_0820F698
gUnknown_0820F698:
    .string "Blitz LV1 Einzelner Feind{END}"

    .global gUnknown_0820F6B2
gUnknown_0820F6B2:
    .string "Eis LV1 Einzelner Feind{END}"

    .global gUnknown_0820F6CA
gUnknown_0820F6CA:
    .string "Beben LV1 Gegnergruppe{END}"

    .global gUnknown_0820F6E1
gUnknown_0820F6E1:
    .string "Stoppt Zeit des Gegners{END}"

    .global gUnknown_0820F6F9
gUnknown_0820F6F9:
    .string "Absorbiert HP vom Gegner{END}"

    .global gUnknown_0820F712
gUnknown_0820F712:
    .string "Todesstrafe Einzelner Feind{END}"

    .global gUnknown_0820F72E
gUnknown_0820F72E:
    .string "Feuer LV2 Einzelner Feind{END}"

    .global gUnknown_0820F748
gUnknown_0820F748:
    .string "Blitz LV2 Einzelner Feind{END}"

    .global gUnknown_0820F762
gUnknown_0820F762:
    .string "Eis LV2 Einzelner Feind{END}"

    .global gUnknown_0820F77A
gUnknown_0820F77A:
    .string "Beben LV2 Gegnergruppe{END}"

    .global gUnknown_0820F791
gUnknown_0820F791:
    .string "Feuer LV3 Einzelner Feind{END}"

    .global gUnknown_0820F7AB
gUnknown_0820F7AB:
    .string "Blitz LV4 Gegnergruppe{END}"

    .global gUnknown_0820F7C2
gUnknown_0820F7C2:
    .string "Eis LV3 Gegnergruppe{END}"

    .global gUnknown_0820F7D7
gUnknown_0820F7D7:
    .string "Beben LV3 Gegnergruppe{END}"

    .global gUnknown_0820F7EE
gUnknown_0820F7EE:
    .string "Blitz LV5 Gegnergruppe{END}"

    .global gUnknown_0820F805
gUnknown_0820F805:
    .string "Eis LV4 Gegnergruppe{END}"

    .global gUnknown_0820F81A
gUnknown_0820F81A:
    .string "Feuer LV5 Gegnergruppe{END}"

    .global gUnknown_0820F831
gUnknown_0820F831:
    .string "Eis LV5 Einzelner Feind{END}"

    .global gUnknown_0820F849
gUnknown_0820F849:
    .string "Feuer LV4 Einzelner Feind{END}"

    .global gUnknown_0820F863
gUnknown_0820F863:
    .string "Blitz LV3 Einzelner Feind{END}"

    .global gUnknown_0820F87D
gUnknown_0820F87D:
    .string "Absorbiert AP vom Gegner{END}"

    .global gUnknown_0820F896
gUnknown_0820F896:
    .string "Dummy{END}"

    .global gUnknown_0820F89C
gUnknown_0820F89C:
    .string "Meteoritensturm Gegnergruppe{END}"

    .global gUnknown_0820F8B9
gUnknown_0820F8B9:
    .string "Dummy{END}"

    .global gUnknown_0820F8BF
gUnknown_0820F8BF:
    .string "Dummy{END}"

    .global gUnknown_0820F8C5
gUnknown_0820F8C5:
    .string "Dummy{END}"

    .global gUnknown_0820F8CB
gUnknown_0820F8CB:
    .string "Dummy{END}"

    .global gUnknown_0820F8D1
gUnknown_0820F8D1:
    .string "Dummy{END}"

    .global gUnknown_0820F8D7
gUnknown_0820F8D7:
    .string "Dummy{END}"

    .global gUnknown_0820F8DD
gUnknown_0820F8DD:
    .string "Dummy{END}"

    .global gUnknown_0820F8E3
gUnknown_0820F8E3:
    .string "Heilt Status “Btbt“ vollständig{END}"

    .global gUnknown_0820F903
gUnknown_0820F903:
    .string "Unter Wasser im Kampf benutzt{END}"

    .global gUnknown_0820F921
gUnknown_0820F921:
    .string "Unter Wasser im Kampf benutzt{END}"

    .global gUnknown_0820F93F
gUnknown_0820F93F:
    .string "Unter Wasser im Kampf benutzt{END}"

    .global gUnknown_0820F95D
gUnknown_0820F95D:
    .string "Unter Wasser im Kampf benutzt{END}"

    .global gUnknown_0820F97B
gUnknown_0820F97B:
    .string "Dummy{END}"

    .global gUnknown_0820F981
gUnknown_0820F981:
    .string "Dummy{END}"

    .global gUnknown_0820F987
gUnknown_0820F987:
    .string "Dummy{END}"

    .global gUnknown_0820F98D
gUnknown_0820F98D:
    .string "Dummy{END}"

    .global gUnknown_0820F993
gUnknown_0820F993:
    .string "Dummy{END}"

    .global gUnknown_0820F999
gUnknown_0820F999:
    .string "Dummy{END}"

    .global gUnknown_0820F99F
gUnknown_0820F99F:
    .string "Dummy{END}"

    .global gUnknown_0820F9A5
gUnknown_0820F9A5:
    .string "Dummy{END}"

    .global gUnknown_0820F9AB
gUnknown_0820F9AB:
    .string "Dummy{END}"

    .global gUnknown_0820F9B1
gUnknown_0820F9B1:
    .string "Engel LV3 Gegnergruppe{END}"

    .global gUnknown_0820F9C8
gUnknown_0820F9C8:
    .string "Dummy{END}"

    .global gUnknown_0820F9CE
gUnknown_0820F9CE:
    .string "Dummy{END}"

    .global gUnknown_0820F9D4
gUnknown_0820F9D4:
    .string "Explosion LV1 Einzelner Feind{END}"

    .global gUnknown_0820F9F2
gUnknown_0820F9F2:
    .string "Explosion LV2 Gegnergruppe{END}"

    .global gUnknown_0820FA0D
gUnknown_0820FA0D:
    .string "Zu einer Stadt warpen{END}"

    .global gUnknown_0820FA23
gUnknown_0820FA23:
    .string "Aus dem Kampf fliehen{END}"

    .global gUnknown_0820FA39
gUnknown_0820FA39:
    .string "Explosion LV3 Einzelner Feind{END}"

    .global gUnknown_0820FA57
gUnknown_0820FA57:
    .string "Aus einem Dungeon fliehen{END}"

    .global gUnknown_0820FA71
gUnknown_0820FA71:
    .string "Explosion LV4 Gegnergruppe{END}"

    .global gUnknown_0820FA8C
gUnknown_0820FA8C:
    .string "Explosion LV5 Einzelner Feind{END}"

    .global gUnknown_0820FAAA
gUnknown_0820FAAA:
    .string "Dummy{END}"

    .global gUnknown_0820FAB0
gUnknown_0820FAB0:
    .string "Dummy{END}"

    .global gUnknown_0820FAB6
gUnknown_0820FAB6:
    .string "Gräbt Tunnel aus Kampf{END}"

    .global gUnknown_0820FACD
gUnknown_0820FACD:
    .string "Im Kampf benutzt{END}"

    .global gUnknown_0820FADE
gUnknown_0820FADE:
    .string "Charaktere fusionieren{END}"

    .global gUnknown_0820FAF5
gUnknown_0820FAF5:
    .string "Verfügbar unter Wasser{END}"

    .global gUnknown_0820FB0C
gUnknown_0820FB0C:
    .string "Verfügbar auf dem Land{END}"

    .global gUnknown_0820FB23
gUnknown_0820FB23:
    .string "Charaktere fusionieren{END}"

    .global gUnknown_0820FB3A
gUnknown_0820FB3A:
    .string "Fusion aufheben{END}"

    .global gUnknown_0820FB4A
gUnknown_0820FB4A:
    .string "Wieder Mensch{END}"

