    .global gUnknown_082100CC
gUnknown_082100CC:
    .string "Dolch{END}"

    .global gUnknown_082100D2
gUnknown_082100D2:
    .string "BronzSW{END}"

    .global gUnknown_082100DA
gUnknown_082100DA:
    .string "Säbel{END}"

    .global gUnknown_082100E0
gUnknown_082100E0:
    .string "Sense{END}"

    .global gUnknown_082100E6
gUnknown_082100E6:
    .string "LangSW{END}"

    .global gUnknown_082100ED
gUnknown_082100ED:
    .string "DrchnSW{END}"

    .global gUnknown_082100F5
gUnknown_082100F5:
    .string "PowerSW{END}"

    .global gUnknown_082100FD
gUnknown_082100FD:
    .string "FlügelSW{END}"

    .global gUnknown_08210106
gUnknown_08210106:
    .string "ImperSW{END}"

    .global gUnknown_0821010E
gUnknown_0821010E:
    .string "ZerbrSW{END}"

    .global gUnknown_08210116
gUnknown_08210116:
    .string "Dummy{END}"

    .global gUnknown_0821011C
gUnknown_0821011C:
    .string "FlammSW{END}"

    .global gUnknown_08210124
gUnknown_08210124:
    .string "Sichel{END}"

    .global gUnknown_0821012B
gUnknown_0821012B:
    .string "BreitSW{END}"

    .global gUnknown_08210133
gUnknown_08210133:
    .string "MystSW{END}"

    .global gUnknown_0821013A
gUnknown_0821013A:
    .string "SWaff{END}"

    .global gUnknown_08210140
gUnknown_08210140:
    .string "KurzRP{END}"

    .global gUnknown_08210147
gUnknown_08210147:
    .string "Rapier{END}"

    .global gUnknown_0821014E
gUnknown_0821014E:
    .string "EisnRP{END}"

    .global gUnknown_08210155
gUnknown_08210155:
    .string "GiftRP{END}"

    .global gUnknown_0821015C
gUnknown_0821015C:
    .string "LichtRP{END}"

    .global gUnknown_08210164
gUnknown_08210164:
    .string "Dummy{END}"

    .global gUnknown_0821016A
gUnknown_0821016A:
    .string "FlammRP{END}"

    .global gUnknown_08210172
gUnknown_08210172:
    .string "FlüglRP{END}"

    .global gUnknown_0821017A
gUnknown_0821017A:
    .string "BronzRP{END}"

    .global gUnknown_08210182
gUnknown_08210182:
    .string "TeuflRP{END}"

    .global gUnknown_0821018A
gUnknown_0821018A:
    .string "BlitzRP{END}"

    .global gUnknown_08210192
gUnknown_08210192:
    .string "Dummy{END}"

    .global gUnknown_08210198
gUnknown_08210198:
    .string "LoyalRP{END}"

    .global gUnknown_082101A0
gUnknown_082101A0:
    .string "PowerRP{END}"

    .global gUnknown_082101A8
gUnknown_082101A8:
    .string "EisnHR{END}"

    .global gUnknown_082101AF
gUnknown_082101AF:
    .string "StchlHR{END}"

    .global gUnknown_082101B7
gUnknown_082101B7:
    .string "Keule{END}"

    .global gUnknown_082101BD
gUnknown_082101BD:
    .string "RiesnHR{END}"

    .global gUnknown_082101C5
gUnknown_082101C5:
    .string "FlammHR{END}"

    .global gUnknown_082101CD
gUnknown_082101CD:
    .string "Dummy{END}"

    .global gUnknown_082101D3
gUnknown_082101D3:
    .string "WutHR{END}"

    .global gUnknown_082101D9
gUnknown_082101D9:
    .string "Dummy{END}"

    .global gUnknown_082101DF
gUnknown_082101DF:
    .string "Hammer{END}"

    .global gUnknown_082101E6
gUnknown_082101E6:
    .string "StrnHR{END}"

    .global gUnknown_082101ED
gUnknown_082101ED:
    .string "Stock{END}"

    .global gUnknown_082101F3
gUnknown_082101F3:
    .string "Prügel{END}"

    .global gUnknown_082101FA
gUnknown_082101FA:
    .string "KnchnPR{END}"

    .global gUnknown_08210202
gUnknown_08210202:
    .string "TeuflPR{END}"

    .global gUnknown_0821020A
gUnknown_0821020A:
    .string "Dummy{END}"

    .global gUnknown_08210210
gUnknown_08210210:
    .string "EisPR{END}"

    .global gUnknown_08210216
gUnknown_08210216:
    .string "Dummy{END}"

    .global gUnknown_0821021C
gUnknown_0821021C:
    .string "GlutPR{END}"

    .global gUnknown_08210223
gUnknown_08210223:
    .string "Dummy{END}"

    .global gUnknown_08210229
gUnknown_08210229:
    .string "Stab{END}"

    .global gUnknown_0821022E
gUnknown_0821022E:
    .string "Spieß{END}"

    .global gUnknown_08210234
gUnknown_08210234:
    .string "Speer{END}"

    .global gUnknown_0821023A
gUnknown_0821023A:
    .string "AltSP{END}"

    .global gUnknown_08210240
gUnknown_08210240:
    .string "HeldSP{END}"

    .global gUnknown_08210247
gUnknown_08210247:
    .string "Drzck{END}"

    .global gUnknown_0821024D
gUnknown_0821024D:
    .string "Dummy{END}"

    .global gUnknown_08210253
gUnknown_08210253:
    .string "Schlfr{END}"

    .global gUnknown_0821025A
gUnknown_0821025A:
    .string "Dummy{END}"

    .global gUnknown_08210260
gUnknown_08210260:
    .string "GrabKR{END}"

    .global gUnknown_08210267
gUnknown_08210267:
    .string "RostKR{END}"

    .global gUnknown_0821026E
gUnknown_0821026E:
    .string "EisnKR{END}"

    .global gUnknown_08210275
gUnknown_08210275:
    .string "EisKR{END}"

    .global gUnknown_0821027B
gUnknown_0821027B:
    .string "Dummy{END}"

    .global gUnknown_08210281
gUnknown_08210281:
    .string "MystKR{END}"

    .global gUnknown_08210288
gUnknown_08210288:
    .string "Dummy{END}"

    .global gUnknown_0821028E
gUnknown_0821028E:
    .string "WurfDL{END}"

    .global gUnknown_08210295
gUnknown_08210295:
    .string "Dolch{END}"

    .global gUnknown_0821029B
gUnknown_0821029B:
    .string "WSpieß{END}"

    .global gUnknown_082102A2
gUnknown_082102A2:
    .string "DrzkDL{END}"

    .global gUnknown_082102A9
gUnknown_082102A9:
    .string "PowerDL{END}"

    .global gUnknown_082102B1
gUnknown_082102B1:
    .string "FlammDL{END}"

    .global gUnknown_082102B9
gUnknown_082102B9:
    .string "SilberDL{END}"

    .global gUnknown_082102C2
gUnknown_082102C2:
    .string "Dummy{END}"

    .global gUnknown_082102C8
gUnknown_082102C8:
    .string "Dummy{END}"

    .global gUnknown_082102CE
gUnknown_082102CE:
    .string "EisDL{END}"

    .global gUnknown_082102D4
gUnknown_082102D4:
    .string "Dummy{END}"

    .global gUnknown_082102DA
gUnknown_082102DA:
    .string "DnklDL{END}"

    .global gUnknown_082102E1
gUnknown_082102E1:
    .string "Dummy{END}"

    .global gUnknown_082102E7
gUnknown_082102E7:
    .string "BronzBG{END}"

    .global gUnknown_082102EF
gUnknown_082102EF:
    .string "KurzBG{END}"

    .global gUnknown_082102F6
gUnknown_082102F6:
    .string "LangBG{END}"

    .global gUnknown_082102FD
gUnknown_082102FD:
    .string "StahlBG{END}"

    .global gUnknown_08210305
gUnknown_08210305:
    .string "GiftBG{END}"

    .global gUnknown_0821030C
gUnknown_0821030C:
    .string "SharfBG{END}"

    .global gUnknown_08210314
gUnknown_08210314:
    .string "MondBG{END}"

    .global gUnknown_0821031B
gUnknown_0821031B:
    .string "JadeBG{END}"

    .global gUnknown_08210322
gUnknown_08210322:
    .string "DrzkBG{END}"

    .global gUnknown_08210329
gUnknown_08210329:
    .string "Dummy{END}"

    .global gUnknown_0821032F
gUnknown_0821032F:
    .string "Dummy{END}"

    .global gUnknown_08210335
gUnknown_08210335:
    .string "Dummy{END}"

    .global gUnknown_0821033B
gUnknown_0821033B:
    .string "ZwrgBG{END}"

    .global gUnknown_08210342
gUnknown_08210342:
    .string "HeldBG{END}"

    .global gUnknown_08210349
gUnknown_08210349:
    .string "Dummy{END}"

    .global gUnknown_0821034F
gUnknown_0821034F:
    .string "BRang{END}"

    .global gUnknown_08210355
gUnknown_08210355:
    .string "WurfKl{END}"

    .global gUnknown_0821035C
gUnknown_0821035C:
    .string "DrRang{END}"

