    .global gUnknown_0820E76E
gUnknown_0820E76E:
    .string "{END}"

    .global gUnknown_0820E76F
gUnknown_0820E76F:
    .string "Drogen{END}"

    .global gUnknown_0820E776
gUnknown_0820E776:
    .string "Nanaï{END}"

    .global gUnknown_0820E77C
gUnknown_0820E77C:
    .string "Winlan{END}"

    .global gUnknown_0820E783
gUnknown_0820E783:
    .string "Roméro{END}"

    .global gUnknown_0820E78A
gUnknown_0820E78A:
    .string "Gust{END}"

    .global gUnknown_0820E78F
gUnknown_0820E78F:
    .string "Camlon{END}"

    .global gUnknown_0820E796
gUnknown_0820E796:
    .string "Nada{END}"

    .global gUnknown_0820E79B
gUnknown_0820E79B:
    .string "Tantar{END}"

    .global gUnknown_0820E7A2
gUnknown_0820E7A2:
    .string "Tuntar{END}"

    .global gUnknown_0820E7A9
gUnknown_0820E7A9:
    .string "Agua{END}"

    .global gUnknown_0820E7AE
gUnknown_0820E7AE:
    .string "Auria{END}"

    .global gUnknown_0820E7B4
gUnknown_0820E7B4:
    .string "Tryste{END}"

    .global gUnknown_0820E7BB
gUnknown_0820E7BB:
    .string "Arad{END}"

    .global gUnknown_0820E7C0
gUnknown_0820E7C0:
    .string "Prntemps{END}"

    .global gUnknown_0820E7C9
gUnknown_0820E7C9:
    .string "Tunlan{END}"

    .global gUnknown_0820E7D0
gUnknown_0820E7D0:
    .string "Gant{END}"

    .global gUnknown_0820E7D5
gUnknown_0820E7D5:
    .string "Scande{END}"

    .global gUnknown_0820E7DC
gUnknown_0820E7DC:
    .string "Carmen{END}"

    .global gUnknown_0820E7E3
gUnknown_0820E7E3:
    .string "Gramor{END}"

    .global gUnknown_0820E7EA
gUnknown_0820E7EA:
    .string "Wisdon{END}"

    .global gUnknown_0820E7F1
gUnknown_0820E7F1:
    .string "Karma{END}"

    .global gUnknown_0820E7F7
gUnknown_0820E7F7:
    .string "Prima{END}"

    .global gUnknown_0820E7FD
gUnknown_0820E7FD:
    .string "Crypte{END}"

    .global gUnknown_0820E804
gUnknown_0820E804:
    .string "Nabal{END}"

    .global gUnknown_0820E80A
gUnknown_0820E80A:
    .string "Tock{END}"

    .global gUnknown_0820E80F
gUnknown_0820E80F:
    .string "Cyme{END}"

    .global gUnknown_0820E814
gUnknown_0820E814:
    .string "Obélisq{END}"

    .global gUnknown_0820E81C
gUnknown_0820E81C:
    .string "Pagode{END}"

