    .align 2
    .global gUnknown_082157B0
gUnknown_082157B0:
    .word gUnknown_0820E76E @ 0 / 0x0
    .word gUnknown_0820E76F @ 1 / 0x1
    .word gUnknown_0820E776 @ 2 / 0x2
    .word gUnknown_0820E77C @ 3 / 0x3
    .word gUnknown_0820E783 @ 4 / 0x4
    .word gUnknown_0820E78A @ 5 / 0x5
    .word gUnknown_0820E78F @ 6 / 0x6
    .word gUnknown_0820E796 @ 7 / 0x7
    .word gUnknown_0820E79B @ 8 / 0x8
    .word gUnknown_0820E7A2 @ 9 / 0x9
    .word gUnknown_0820E7A9 @ 10 / 0xA
    .word gUnknown_0820E7AE @ 11 / 0xB
    .word gUnknown_0820E7B4 @ 12 / 0xC
    .word gUnknown_0820E7BB @ 13 / 0xD
    .word gUnknown_0820E7C0 @ 14 / 0xE
    .word gUnknown_0820E7C9 @ 15 / 0xF
    .word gUnknown_0820E7D0 @ 16 / 0x10
    .word gUnknown_0820E7D5 @ 17 / 0x11
    .word gUnknown_0820E7DC @ 18 / 0x12
    .word gUnknown_0820E7E3 @ 19 / 0x13
    .word gUnknown_0820E7EA @ 20 / 0x14
    .word gUnknown_0820E7F1 @ 21 / 0x15
    .word gUnknown_0820E7F7 @ 22 / 0x16
    .word gUnknown_0820E7FD @ 23 / 0x17
    .word gUnknown_0820E804 @ 24 / 0x18
    .word gUnknown_0820E80A @ 25 / 0x19
    .word gUnknown_0820E80F @ 26 / 0x1A
    .word gUnknown_0820E814 @ 27 / 0x1B
    .word gUnknown_0820E81C @ 28 / 0x1C
