    .global gUnknown_0820E34A
gUnknown_0820E34A:
    .string "Robe{END}"

    .global gUnknown_0820E34F
gUnknown_0820E34F:
    .string "CqDaim{END}"

    .global gUnknown_0820E356
gUnknown_0820E356:
    .string "RobeLèg{END}"

    .global gUnknown_0820E35E
gUnknown_0820E35E:
    .string "ArmMét{END}"

    .global gUnknown_0820E365
gUnknown_0820E365:
    .string "RobeSoie{END}"

    .global gUnknown_0820E36E
gUnknown_0820E36E:
    .string "Habits{END}"

    .global gUnknown_0820E375
gUnknown_0820E375:
    .string "HabLèg{END}"

    .global gUnknown_0820E37C
gUnknown_0820E37C:
    .string "RobeSoir{END}"

    .global gUnknown_0820E385
gUnknown_0820E385:
    .string "ArmPad{END}"

    .global gUnknown_0820E38C
gUnknown_0820E38C:
    .string "PeauLoup{END}"

    .global gUnknown_0820E395
gUnknown_0820E395:
    .string "ArmRôdr{END}"

    .global gUnknown_0820E39D
gUnknown_0820E39D:
    .string "ArmBronz{END}"

    .global gUnknown_0820E3A6
gUnknown_0820E3A6:
    .string "ArmPlaqu{END}"

    .global gUnknown_0820E3AF
gUnknown_0820E3AF:
    .string "Faux{END}"

    .global gUnknown_0820E3B4
gUnknown_0820E3B4:
    .string "ArmFeu{END}"

    .global gUnknown_0820E3BB
gUnknown_0820E3BB:
    .string "HabImmac{END}"

    .global gUnknown_0820E3C4
gUnknown_0820E3C4:
    .string "ArmuSp{END}"

    .global gUnknown_0820E3CB
gUnknown_0820E3CB:
    .string "ArmGl{END}"

    .global gUnknown_0820E3D1
gUnknown_0820E3D1:
    .string "MaillM{END}"

    .global gUnknown_0820E3D8
gUnknown_0820E3D8:
    .string "Faux{END}"

    .global gUnknown_0820E3DD
gUnknown_0820E3DD:
    .string "CapEp{END}"

    .global gUnknown_0820E3E3
gUnknown_0820E3E3:
    .string "CapVol{END}"

    .global gUnknown_0820E3EA
gUnknown_0820E3EA:
    .string "RobeMal{END}"

    .global gUnknown_0820E3F2
gUnknown_0820E3F2:
    .string "RobeVel{END}"

    .global gUnknown_0820E3FA
gUnknown_0820E3FA:
    .string "ArmDaim{END}"

    .global gUnknown_0820E402
gUnknown_0820E402:
    .string "CottMail{END}"

    .global gUnknown_0820E40B
gUnknown_0820E40B:
    .string "MaillFer{END}"

    .global gUnknown_0820E414
gUnknown_0820E414:
    .string "RobLaine{END}"

    .global gUnknown_0820E41D
gUnknown_0820E41D:
    .string "RobeDaim{END}"

    .global gUnknown_0820E426
gUnknown_0820E426:
    .string "ArmVie{END}"

    .global gUnknown_0820E42D
gUnknown_0820E42D:
    .string "ArmPuis{END}"

    .global gUnknown_0820E435
gUnknown_0820E435:
    .string "ArmQrtz{END}"

    .global gUnknown_0820E43D
gUnknown_0820E43D:
    .string "ArmAngle{END}"

    .global gUnknown_0820E446
gUnknown_0820E446:
    .string "Faux{END}"

    .global gUnknown_0820E44B
gUnknown_0820E44B:
    .string "MantGour{END}"

    .global gUnknown_0820E454
gUnknown_0820E454:
    .string "Faux{END}"

    .global gUnknown_0820E459
gUnknown_0820E459:
    .string "Faux{END}"

    .global gUnknown_0820E45E
gUnknown_0820E45E:
    .string "ArmMond{END}"

    .global gUnknown_0820E466
gUnknown_0820E466:
    .string "ArmSage{END}"

    .global gUnknown_0820E46E
gUnknown_0820E46E:
    .string "Faux{END}"

    .global gUnknown_0820E473
gUnknown_0820E473:
    .string "RobeMyst{END}"

    .global gUnknown_0820E47C
gUnknown_0820E47C:
    .string "RobeTer{END}"

    .global gUnknown_0820E484
gUnknown_0820E484:
    .string "Faux{END}"

    .global gUnknown_0820E489
gUnknown_0820E489:
    .string "ArmAg{END}"

    .global gUnknown_0820E48F
gUnknown_0820E48F:
    .string "Faux{END}"

    .global gUnknown_0820E494
gUnknown_0820E494:
    .string "CapChass{END}"

    .global gUnknown_0820E49D
gUnknown_0820E49D:
    .string "CapClair{END}"

    .global gUnknown_0820E4A6
gUnknown_0820E4A6:
    .string "Faux{END}"

    .global gUnknown_0820E4AB
gUnknown_0820E4AB:
    .string "BoucBois{END}"

    .global gUnknown_0820E4B4
gUnknown_0820E4B4:
    .string "Gantelet{END}"

    .global gUnknown_0820E4BD
gUnknown_0820E4BD:
    .string "BoucDaim{END}"

    .global gUnknown_0820E4C6
gUnknown_0820E4C6:
    .string "BoucGard{END}"

    .global gUnknown_0820E4CF
gUnknown_0820E4CF:
    .string "Bracelet{END}"

    .global gUnknown_0820E4D8
gUnknown_0820E4D8:
    .string "BoucFer{END}"

    .global gUnknown_0820E4E0
gUnknown_0820E4E0:
    .string "BoucBrnz{END}"

    .global gUnknown_0820E4E9
gUnknown_0820E4E9:
    .string "BoucMét{END}"

    .global gUnknown_0820E4F1
gUnknown_0820E4F1:
    .string "BoucFeu{END}"

    .global gUnknown_0820E4F9
gUnknown_0820E4F9:
    .string "Faux{END}"

    .global gUnknown_0820E4FE
gUnknown_0820E4FE:
    .string "PetBouc{END}"

    .global gUnknown_0820E506
gUnknown_0820E506:
    .string "EcuFer{END}"

    .global gUnknown_0820E50D
gUnknown_0820E50D:
    .string "EcuMét{END}"

    .global gUnknown_0820E514
gUnknown_0820E514:
    .string "Faux{END}"

    .global gUnknown_0820E519
gUnknown_0820E519:
    .string "Poignet{END}"

    .global gUnknown_0820E521
gUnknown_0820E521:
    .string "BoucGl{END}"

    .global gUnknown_0820E528
gUnknown_0820E528:
    .string "BoucPro{END}"

    .global gUnknown_0820E530
gUnknown_0820E530:
    .string "BracAmr{END}"

    .global gUnknown_0820E538
gUnknown_0820E538:
    .string "BracVent{END}"

    .global gUnknown_0820E541
gUnknown_0820E541:
    .string "AnnRubis{END}"

    .global gUnknown_0820E54A
gUnknown_0820E54A:
    .string "Faux{END}"

    .global gUnknown_0820E54F
gUnknown_0820E54F:
    .string "BracNoir{END}"

    .global gUnknown_0820E558
gUnknown_0820E558:
    .string "Faux{END}"

    .global gUnknown_0820E55D
gUnknown_0820E55D:
    .string "BoucMyst{END}"

    .global gUnknown_0820E566
gUnknown_0820E566:
    .string "Gant{END}"

    .global gUnknown_0820E56B
gUnknown_0820E56B:
    .string "Faux{END}"

    .global gUnknown_0820E570
gUnknown_0820E570:
    .string "PiègeGar{END}"

    .global gUnknown_0820E579
gUnknown_0820E579:
    .string "BoucLèg{END}"

    .global gUnknown_0820E581
gUnknown_0820E581:
    .string "AnnMag{END}"

    .global gUnknown_0820E588
gUnknown_0820E588:
    .string "Bandage{END}"

    .global gUnknown_0820E590
gUnknown_0820E590:
    .string "Faux{END}"

    .global gUnknown_0820E595
gUnknown_0820E595:
    .string "BracArg{END}"

    .global gUnknown_0820E59D
gUnknown_0820E59D:
    .string "Faux{END}"

    .global gUnknown_0820E5A2
gUnknown_0820E5A2:
    .string "BoucFrd{END}"

    .global gUnknown_0820E5AA
gUnknown_0820E5AA:
    .string "GantChas{END}"

    .global gUnknown_0820E5B3
gUnknown_0820E5B3:
    .string "BoucMasq{END}"

    .global gUnknown_0820E5BC
gUnknown_0820E5BC:
    .string "BoucDrag{END}"

    .global gUnknown_0820E5C5
gUnknown_0820E5C5:
    .string "Faux{END}"

    .global gUnknown_0820E5CA
gUnknown_0820E5CA:
    .string "BoucLave{END}"

    .global gUnknown_0820E5D3
gUnknown_0820E5D3:
    .string "Faux{END}"

    .global gUnknown_0820E5D8
gUnknown_0820E5D8:
    .string "CasqDaim{END}"

    .global gUnknown_0820E5E1
gUnknown_0820E5E1:
    .string "Viseur{END}"

    .global gUnknown_0820E5E8
gUnknown_0820E5E8:
    .string "Bandeau{END}"

    .global gUnknown_0820E5F0
gUnknown_0820E5F0:
    .string "Tiare{END}"

    .global gUnknown_0820E5F6
gUnknown_0820E5F6:
    .string "BndChaîn{END}"

    .global gUnknown_0820E5FF
gUnknown_0820E5FF:
    .string "TiareOr{END}"

    .global gUnknown_0820E607
gUnknown_0820E607:
    .string "CasqEcho{END}"

    .global gUnknown_0820E610
gUnknown_0820E610:
    .string "MasqFer{END}"

    .global gUnknown_0820E618
gUnknown_0820E618:
    .string "Faux{END}"

    .global gUnknown_0820E61D
gUnknown_0820E61D:
    .string "Faux{END}"

    .global gUnknown_0820E622
gUnknown_0820E622:
    .string "CasqPier{END}"

    .global gUnknown_0820E62B
gUnknown_0820E62B:
    .string "CasqOr{END}"

    .global gUnknown_0820E632
gUnknown_0820E632:
    .string "MasFacia{END}"

    .global gUnknown_0820E63B
gUnknown_0820E63B:
    .string "CasAgil{END}"

    .global gUnknown_0820E643
gUnknown_0820E643:
    .string "JolieCsq{END}"

    .global gUnknown_0820E64C
gUnknown_0820E64C:
    .string "SfMyst{END}"

    .global gUnknown_0820E653
gUnknown_0820E653:
    .string "CasqPlng{END}"

    .global gUnknown_0820E65C
gUnknown_0820E65C:
    .string "MasqGaia{END}"

    .global gUnknown_0820E665
gUnknown_0820E665:
    .string "CouvreCh{END}"

    .global gUnknown_0820E66E
gUnknown_0820E66E:
    .string "CasqMaud{END}"

    .global gUnknown_0820E677
gUnknown_0820E677:
    .string "CasCoqui{END}"

    .global gUnknown_0820E680
gUnknown_0820E680:
    .string "CasqPail{END}"

    .global gUnknown_0820E689
gUnknown_0820E689:
    .string "CasqFer{END}"

    .global gUnknown_0820E691
gUnknown_0820E691:
    .string "Faux{END}"

    .global gUnknown_0820E696
gUnknown_0820E696:
    .string "CasqMaré{END}"

    .global gUnknown_0820E69F
gUnknown_0820E69F:
    .string "CasqCrân{END}"

    .global gUnknown_0820E6A8
gUnknown_0820E6A8:
    .string "CasqPuis{END}"

    .global gUnknown_0820E6B1
gUnknown_0820E6B1:
    .string "Domino{END}"

    .global gUnknown_0820E6B8
gUnknown_0820E6B8:
    .string "CasCorn{END}"

    .global gUnknown_0820E6C0
gUnknown_0820E6C0:
    .string "Bandana{END}"

    .global gUnknown_0820E6C8
gUnknown_0820E6C8:
    .string "Turban{END}"

    .global gUnknown_0820E6CF
gUnknown_0820E6CF:
    .string "Faux{END}"

    .global gUnknown_0820E6D4
gUnknown_0820E6D4:
    .string "CasqAmr{END}"

    .global gUnknown_0820E6DC
gUnknown_0820E6DC:
    .string "Faux{END}"

    .global gUnknown_0820E6E1
gUnknown_0820E6E1:
    .string "Faux{END}"

    .global gUnknown_0820E6E6
gUnknown_0820E6E6:
    .string "Faux{END}"

    .global gUnknown_0820E6EB
gUnknown_0820E6EB:
    .string "CasqBrnz{END}"

    .global gUnknown_0820E6F4
gUnknown_0820E6F4:
    .string "CasqSp{END}"

    .global gUnknown_0820E6FB
gUnknown_0820E6FB:
    .string "CasqSol{END}"

    .global gUnknown_0820E703
gUnknown_0820E703:
    .string "CasqLoup{END}"

    .global gUnknown_0820E70C
gUnknown_0820E70C:
    .string "CasqGl{END}"

    .global gUnknown_0820E713
gUnknown_0820E713:
    .string "Faux{END}"

    .global gUnknown_0820E718
gUnknown_0820E718:
    .string "Faux{END}"

    .global gUnknown_0820E71D
gUnknown_0820E71D:
    .string "Faux{END}"

    .global gUnknown_0820E722
gUnknown_0820E722:
    .string "CasqEtoi{END}"

    .global gUnknown_0820E72B
gUnknown_0820E72B:
    .string "Faux{END}"

    .global gUnknown_0820E730
gUnknown_0820E730:
    .string "AnnCrâne{END}"

    .global gUnknown_0820E739
gUnknown_0820E739:
    .string "BoucCiel{END}"

    .global gUnknown_0820E742
gUnknown_0820E742:
    .string "Faux{END}"

    .global gUnknown_0820E747
gUnknown_0820E747:
    .string "Faux{END}"

    .global gUnknown_0820E74C
gUnknown_0820E74C:
    .string "CasqDrag{END}"

    .global gUnknown_0820E755
gUnknown_0820E755:
    .string "ArmDrag{END}"

    .global gUnknown_0820E75D
gUnknown_0820E75D:
    .string "AnnIntel{END}"

    .global gUnknown_0820E766
gUnknown_0820E766:
    .string "AnnRêve{END}"

