    .global gUnknown_0820D0AD
gUnknown_0820D0AD:
    .string "Gren{END}"

    .global gUnknown_0820D0B2
gUnknown_0820D0B2:
    .string "Chev{END}"

    .global gUnknown_0820D0B7
gUnknown_0820D0B7:
    .string "Mag{END}"

    .global gUnknown_0820D0BB
gUnknown_0820D0BB:
    .string "Mag{END}"

    .global gUnknown_0820D0BF
gUnknown_0820D0BF:
    .string "Mag{END}"

    .global gUnknown_0820D0C3
gUnknown_0820D0C3:
    .string "Puce{END}"

    .global gUnknown_0820D0C8
gUnknown_0820D0C8:
    .string "Oiseau{END}"

    .global gUnknown_0820D0CF
gUnknown_0820D0CF:
    .string "Perch{END}"

    .global gUnknown_0820D0D5
gUnknown_0820D0D5:
    .string "Triste{END}"

    .global gUnknown_0820D0DC
gUnknown_0820D0DC:
    .string "Bec{END}"

    .global gUnknown_0820D0E0
gUnknown_0820D0E0:
    .string "Frisse{END}"

    .global gUnknown_0820D0E7
gUnknown_0820D0E7:
    .string "Zard{END}"

    .global gUnknown_0820D0EC
gUnknown_0820D0EC:
    .string "Mort{END}"

    .global gUnknown_0820D0F1
gUnknown_0820D0F1:
    .string "Mortéa{END}"

    .global gUnknown_0820D0F8
gUnknown_0820D0F8:
    .string "Serre{END}"

    .global gUnknown_0820D0FE
gUnknown_0820D0FE:
    .string "Bain{END}"

    .global gUnknown_0820D103
gUnknown_0820D103:
    .string "Général{END}"

    .global gUnknown_0820D10B
gUnknown_0820D10B:
    .string "Gremlin{END}"

    .global gUnknown_0820D113
gUnknown_0820D113:
    .string "Follet{END}"

    .global gUnknown_0820D11A
gUnknown_0820D11A:
    .string "Pog{END}"

    .global gUnknown_0820D11E
gUnknown_0820D11E:
    .string "Zombi{END}"

    .global gUnknown_0820D124
gUnknown_0820D124:
    .string "Vase{END}"

    .global gUnknown_0820D129
gUnknown_0820D129:
    .string "CavS{END}"

    .global gUnknown_0820D12E
gUnknown_0820D12E:
    .string "Blob{END}"

    .global gUnknown_0820D133
gUnknown_0820D133:
    .string "Lancier{END}"

    .global gUnknown_0820D13B
gUnknown_0820D13B:
    .string "Archer{END}"

    .global gUnknown_0820D142
gUnknown_0820D142:
    .string "Ruga{END}"

    .global gUnknown_0820D147
gUnknown_0820D147:
    .string "CochGuer{END}"

    .global gUnknown_0820D150
gUnknown_0820D150:
    .string "BlobAme{END}"

    .global gUnknown_0820D158
gUnknown_0820D158:
    .string "Bulla{END}"

    .global gUnknown_0820D15E
gUnknown_0820D15E:
    .string "Cafard{END}"

    .global gUnknown_0820D165
gUnknown_0820D165:
    .string "MoucheG{END}"

    .global gUnknown_0820D16D
gUnknown_0820D16D:
    .string "Espoeil{END}"

    .global gUnknown_0820D175
gUnknown_0820D175:
    .string "Octo{END}"

    .global gUnknown_0820D17A
gUnknown_0820D17A:
    .string "Poulpe{END}"

    .global gUnknown_0820D181
gUnknown_0820D181:
    .string "VerSab{END}"

    .global gUnknown_0820D188
gUnknown_0820D188:
    .string "Nuage{END}"

    .global gUnknown_0820D18E
gUnknown_0820D18E:
    .string "Scorp{END}"

    .global gUnknown_0820D194
gUnknown_0820D194:
    .string "Mage{END}"

    .global gUnknown_0820D199
gUnknown_0820D199:
    .string "Gratte{END}"

    .global gUnknown_0820D1A0
gUnknown_0820D1A0:
    .string "TirArc{END}"

    .global gUnknown_0820D1A7
gUnknown_0820D1A7:
    .string "Mouche{END}"

    .global gUnknown_0820D1AE
gUnknown_0820D1AE:
    .string "fantas{END}"

    .global gUnknown_0820D1B5
gUnknown_0820D1B5:
    .string "Créon{END}"

    .global gUnknown_0820D1BB
gUnknown_0820D1BB:
    .string "Chev{END}"

    .global gUnknown_0820D1C0
gUnknown_0820D1C0:
    .string "Mothro{END}"

    .global gUnknown_0820D1C7
gUnknown_0820D1C7:
    .string "Mote{END}"

    .global gUnknown_0820D1CC
gUnknown_0820D1CC:
    .string "Soldat{END}"

    .global gUnknown_0820D1D3
gUnknown_0820D1D3:
    .string "Tristev{END}"

    .global gUnknown_0820D1DB
gUnknown_0820D1DB:
    .string "Pinceur{END}"

    .global gUnknown_0820D1E3
gUnknown_0820D1E3:
    .string "VaseX{END}"

    .global gUnknown_0820D1E9
gUnknown_0820D1E9:
    .string "Brüm{END}"

    .global gUnknown_0820D1EE
gUnknown_0820D1EE:
    .string "VaseR{END}"

    .global gUnknown_0820D1F4
gUnknown_0820D1F4:
    .string "Poisse{END}"

    .global gUnknown_0820D1FB
gUnknown_0820D1FB:
    .string "PoissCh{END}"

    .global gUnknown_0820D203
gUnknown_0820D203:
    .string "Nain{END}"

    .global gUnknown_0820D208
gUnknown_0820D208:
    .string "Tronc{END}"

    .global gUnknown_0820D20E
gUnknown_0820D20E:
    .string "NSable{END}"

    .global gUnknown_0820D215
gUnknown_0820D215:
    .string "Tentac{END}"

    .global gUnknown_0820D21C
gUnknown_0820D21C:
    .string "ScorpM{END}"

    .global gUnknown_0820D223
gUnknown_0820D223:
    .string "RugaX{END}"

    .global gUnknown_0820D229
gUnknown_0820D229:
    .string "LancierX{END}"

    .global gUnknown_0820D232
gUnknown_0820D232:
    .string "ArcherX{END}"

    .global gUnknown_0820D23A
gUnknown_0820D23A:
    .string "AmePeine{END}"

    .global gUnknown_0820D243
gUnknown_0820D243:
    .string "RugaX{END}"

    .global gUnknown_0820D249
gUnknown_0820D249:
    .string "FleurX{END}"

    .global gUnknown_0820D250
gUnknown_0820D250:
    .string "CrapCor{END}"

    .global gUnknown_0820D258
gUnknown_0820D258:
    .string "Mote{END}"

    .global gUnknown_0820D25D
gUnknown_0820D25D:
    .string "Cerl{END}"

    .global gUnknown_0820D262
gUnknown_0820D262:
    .string "Mothro{END}"

    .global gUnknown_0820D269
gUnknown_0820D269:
    .string "InsP{END}"

    .global gUnknown_0820D26E
gUnknown_0820D26E:
    .string "Chimère{END}"

    .global gUnknown_0820D276
gUnknown_0820D276:
    .string "Thalle{END}"

    .global gUnknown_0820D27D
gUnknown_0820D27D:
    .string "Volant{END}"

    .global gUnknown_0820D284
gUnknown_0820D284:
    .string "Cafard{END}"

    .global gUnknown_0820D28B
gUnknown_0820D28B:
    .string "Phénix{END}"

    .global gUnknown_0820D292
gUnknown_0820D292:
    .string "Mortéo{END}"

    .global gUnknown_0820D299
gUnknown_0820D299:
    .string "Sorcier{END}"

    .global gUnknown_0820D2A1
gUnknown_0820D2A1:
    .string "Crapaud{END}"

    .global gUnknown_0820D2A9
gUnknown_0820D2A9:
    .string "Roublard{END}"

    .global gUnknown_0820D2B2
gUnknown_0820D2B2:
    .string "Goda{END}"

    .global gUnknown_0820D2B7
gUnknown_0820D2B7:
    .string "Zog{END}"

    .global gUnknown_0820D2BB
gUnknown_0820D2BB:
    .string "Jade{END}"

    .global gUnknown_0820D2C0
gUnknown_0820D2C0:
    .string "Déesse{END}"

    .global gUnknown_0820D2C7
gUnknown_0820D2C7:
    .string "Déesse{END}"

    .global gUnknown_0820D2CE
gUnknown_0820D2CE:
    .string "Sara{END}"

    .global gUnknown_0820D2D3
gUnknown_0820D2D3:
    .string "MageGuerre{END}"

    .global gUnknown_0820D2DE
gUnknown_0820D2DE:
    .string "Zoom{END}"

    .global gUnknown_0820D2E3
gUnknown_0820D2E3:
    .string "Gargouille{END}"

    .global gUnknown_0820D2EE
gUnknown_0820D2EE:
    .string "ChevG{END}"

    .global gUnknown_0820D2F4
gUnknown_0820D2F4:
    .string "Ombre{END}"

    .global gUnknown_0820D2FA
gUnknown_0820D2FA:
    .string "AmePeineX{END}"

    .global gUnknown_0820D304
gUnknown_0820D304:
    .string "Araignée{END}"

    .global gUnknown_0820D30D
gUnknown_0820D30D:
    .string "Foyer{END}"

    .global gUnknown_0820D313
gUnknown_0820D313:
    .string "Golem{END}"

    .global gUnknown_0820D319
gUnknown_0820D319:
    .string "Coffre{END}"

    .global gUnknown_0820D320
gUnknown_0820D320:
    .string "Déesse{END}"

    .global gUnknown_0820D327
gUnknown_0820D327:
    .string "PuceD{END}"

    .global gUnknown_0820D32D
gUnknown_0820D32D:
    .string "Crabe{END}"

    .global gUnknown_0820D333
gUnknown_0820D333:
    .string "Fleur{END}"

    .global gUnknown_0820D339
gUnknown_0820D339:
    .string "VaseG{END}"

    .global gUnknown_0820D33F
gUnknown_0820D33F:
    .string "VaseM{END}"

    .global gUnknown_0820D345
gUnknown_0820D345:
    .string "Bourdon{END}"

    .global gUnknown_0820D34D
gUnknown_0820D34D:
    .string "Rampant{END}"

    .global gUnknown_0820D355
gUnknown_0820D355:
    .string "Ruga{END}"

    .global gUnknown_0820D35A
gUnknown_0820D35A:
    .string "Ronk{END}"

    .global gUnknown_0820D35F
gUnknown_0820D35F:
    .string "PoisChX{END}"

    .global gUnknown_0820D367
gUnknown_0820D367:
    .string "FoyerX{END}"

    .global gUnknown_0820D36E
gUnknown_0820D36E:
    .string "BlobAmeX{END}"

    .global gUnknown_0820D377
gUnknown_0820D377:
    .string "Nautile{END}"

    .global gUnknown_0820D37F
gUnknown_0820D37F:
    .string "Veuve{END}"

    .global gUnknown_0820D385
gUnknown_0820D385:
    .string "PuceM{END}"

    .global gUnknown_0820D38B
gUnknown_0820D38B:
    .string "RampantX{END}"

    .global gUnknown_0820D394
gUnknown_0820D394:
    .string "Mimique{END}"

    .global gUnknown_0820D39C
gUnknown_0820D39C:
    .string "CochGuerX{END}"

    .global gUnknown_0820D3A6
gUnknown_0820D3A6:
    .string "TêteFeu{END}"

    .global gUnknown_0820D3AE
gUnknown_0820D3AE:
    .string "Brute{END}"

    .global gUnknown_0820D3B4
gUnknown_0820D3B4:
    .string "Griffe{END}"

    .global gUnknown_0820D3BB
gUnknown_0820D3BB:
    .string "PinceurX{END}"

    .global gUnknown_0820D3C4
gUnknown_0820D3C4:
    .string "CréonX{END}"

    .global gUnknown_0820D3CB
gUnknown_0820D3CB:
    .string "Bain{END}"

    .global gUnknown_0820D3D0
gUnknown_0820D3D0:
    .string "CavD{END}"

    .global gUnknown_0820D3D5
gUnknown_0820D3D5:
    .string "Goule{END}"

    .global gUnknown_0820D3DB
gUnknown_0820D3DB:
    .string "Cactus{END}"

    .global gUnknown_0820D3E2
gUnknown_0820D3E2:
    .string "CactusX{END}"

    .global gUnknown_0820D3EA
gUnknown_0820D3EA:
    .string "UCI{END}"

    .global gUnknown_0820D3EE
gUnknown_0820D3EE:
    .string "Entité{END}"

    .global gUnknown_0820D3F5
gUnknown_0820D3F5:
    .string "ChevD{END}"

