    .align 2
    .global gUnknown_082142E0
gUnknown_082142E0:
    .word gUnknown_0820C9D8 @ 0 / 0x0
    .word gUnknown_0820CA91 @ 1 / 0x1
    .word gUnknown_0820CB2B @ 2 / 0x2
    .word gUnknown_0820CBC4 @ 3 / 0x3
    .word gUnknown_0820CC02 @ 4 / 0x4
    .word gUnknown_0820CC75 @ 5 / 0x5
    .word gUnknown_0820CCC0 @ 6 / 0x6
    .word gUnknown_0820CD0E @ 7 / 0x7
    .word gUnknown_0820CD72 @ 8 / 0x8
    .word gUnknown_0820CDEC @ 9 / 0x9
    .word gUnknown_0820CE40 @ 10 / 0xA
    .word gUnknown_0820CE79 @ 11 / 0xB
    .word gUnknown_0820CEB7 @ 12 / 0xC
    .word gUnknown_0820CEFC @ 13 / 0xD
    .word gUnknown_0820CF5C @ 14 / 0xE
    .word gUnknown_0820CFAD @ 15 / 0xF
    .word gUnknown_0820CFFB @ 16 / 0x10
    .word gUnknown_0820D02C @ 17 / 0x11
    .word gUnknown_0820D05B @ 18 / 0x12
    .word gUnknown_0820D085 @ 19 / 0x13
