    .global gUnknown_0820DD59
gUnknown_0820DD59:
    .string "70 GP{END}"

    .global gUnknown_0820DD5F
gUnknown_0820DD5F:
    .string "150 GP{END}"

    .global gUnknown_0820DD66
gUnknown_0820DD66:
    .string "300 GP{END}"

    .global gUnknown_0820DD6D
gUnknown_0820DD6D:
    .string "650 GP{END}"

    .global gUnknown_0820DD74
gUnknown_0820DD74:
    .string "900 GP{END}"

    .global gUnknown_0820DD7B
gUnknown_0820DD7B:
    .string "1200 GP{END}"

    .global gUnknown_0820DD83
gUnknown_0820DD83:
    .string "2000 GP{END}"

    .global gUnknown_0820DD8B
gUnknown_0820DD8B:
    .string "3000 GP{END}"

    .global gUnknown_0820DD93
gUnknown_0820DD93:
    .string "Herbe{END}"

    .global gUnknown_0820DD99
gUnknown_0820DD99:
    .string "Soin{END}"

    .global gUnknown_0820DD9E
gUnknown_0820DD9E:
    .string "Fourmi{END}"

    .global gUnknown_0820DDA5
gUnknown_0820DDA5:
    .string "Gland{END}"

    .global gUnknown_0820DDAB
gUnknown_0820DDAB:
    .string "Déjec{END}"

    .global gUnknown_0820DDB1
gUnknown_0820DDB1:
    .string "Larme{END}"

    .global gUnknown_0820DDB7
gUnknown_0820DDB7:
    .string "Charme{END}"

    .global gUnknown_0820DDBE
gUnknown_0820DDBE:
    .string "Vie2{END}"

    .global gUnknown_0820DDC3
gUnknown_0820DDC3:
    .string "Bille1{END}"

    .global gUnknown_0820DDCA
gUnknown_0820DDCA:
    .string "Bille2{END}"

    .global gUnknown_0820DDD1
gUnknown_0820DDD1:
    .string "Bille3{END}"

    .global gUnknown_0820DDD8
gUnknown_0820DDD8:
    .string "Moust{END}"

    .global gUnknown_0820DDDE
gUnknown_0820DDDE:
    .string "Ver{END}"

    .global gUnknown_0820DDE2
gUnknown_0820DDE2:
    .string "Ver2{END}"

    .global gUnknown_0820DDE7
gUnknown_0820DDE7:
    .string "Crev{END}"

    .global gUnknown_0820DDEC
gUnknown_0820DDEC:
    .string "Oursin{END}"

    .global gUnknown_0820DDF3
gUnknown_0820DDF3:
    .string "Coquill{END}"

    .global gUnknown_0820DDFB
gUnknown_0820DDFB:
    .string "Pomme{END}"

    .global gUnknown_0820DE01
gUnknown_0820DE01:
    .string "ProtA{END}"

    .global gUnknown_0820DE07
gUnknown_0820DE07:
    .string "Bois{END}"

    .global gUnknown_0820DE0C
gUnknown_0820DE0C:
    .string "ViandeB{END}"

    .global gUnknown_0820DE14
gUnknown_0820DE14:
    .string "Vie{END}"

    .global gUnknown_0820DE18
gUnknown_0820DE18:
    .string "Ongles{END}"

    .global gUnknown_0820DE1F
gUnknown_0820DE1F:
    .string "Viande{END}"

    .global gUnknown_0820DE26
gUnknown_0820DE26:
    .string "StnB{END}"

    .global gUnknown_0820DE2B
gUnknown_0820DE2B:
    .string "StnF{END}"

    .global gUnknown_0820DE30
gUnknown_0820DE30:
    .string "StnC{END}"

    .global gUnknown_0820DE35
gUnknown_0820DE35:
    .string "Fumée{END}"

    .global gUnknown_0820DE3B
gUnknown_0820DE3B:
    .string "BaiserN{END}"

    .global gUnknown_0820DE43
gUnknown_0820DE43:
    .string "Soins2{END}"

    .global gUnknown_0820DE4A
gUnknown_0820DE4A:
    .string "ProtB{END}"

    .global gUnknown_0820DE50
gUnknown_0820DE50:
    .string "Echarp{END}"

    .global gUnknown_0820DE57
gUnknown_0820DE57:
    .string "PtnW{END}"

    .global gUnknown_0820DE5C
gUnknown_0820DE5C:
    .string "PtnS{END}"

    .global gUnknown_0820DE61
gUnknown_0820DE61:
    .string "Sablier{END}"

    .global gUnknown_0820DE69
gUnknown_0820DE69:
    .string "InsExp{END}"

    .global gUnknown_0820DE70
gUnknown_0820DE70:
    .string "Table{END}"

    .global gUnknown_0820DE76
gUnknown_0820DE76:
    .string "MonteCh{END}"

    .global gUnknown_0820DE7E
gUnknown_0820DE7E:
    .string "CléE{END}"

    .global gUnknown_0820DE83
gUnknown_0820DE83:
    .string "EauCal{END}"

    .global gUnknown_0820DE8A
gUnknown_0820DE8A:
    .string "Carros{END}"

    .global gUnknown_0820DE91
gUnknown_0820DE91:
    .string "Bloc{END}"

    .global gUnknown_0820DE96
gUnknown_0820DE96:
    .string "PtnA{END}"

    .global gUnknown_0820DE9B
gUnknown_0820DE9B:
    .string "PtnL{END}"

    .global gUnknown_0820DEA0
gUnknown_0820DEA0:
    .string "PtnV{END}"

    .global gUnknown_0820DEA5
gUnknown_0820DEA5:
    .string "AmeNr{END}"

    .global gUnknown_0820DEAB
gUnknown_0820DEAB:
    .string "Télép{END}"

    .global gUnknown_0820DEB1
gUnknown_0820DEB1:
    .string "Placéb{END}"

    .global gUnknown_0820DEB8
gUnknown_0820DEB8:
    .string "Remède{END}"

    .global gUnknown_0820DEBF
gUnknown_0820DEBF:
    .string "Jarre{END}"

    .global gUnknown_0820DEC5
gUnknown_0820DEC5:
    .string "Scie{END}"

    .global gUnknown_0820DECA
gUnknown_0820DECA:
    .string "Tablette{END}"

    .global gUnknown_0820DED3
gUnknown_0820DED3:
    .string "Anneau{END}"

    .global gUnknown_0820DEDA
gUnknown_0820DEDA:
    .string "Jarre{0x1A}{END}"

    .global gUnknown_0820DEE1
gUnknown_0820DEE1:
    .string "CléRoi{END}"

    .global gUnknown_0820DEE8
gUnknown_0820DEE8:
    .string "Papier{END}"

    .global gUnknown_0820DEEF
gUnknown_0820DEEF:
    .string "Voeu{END}"

    .global gUnknown_0820DEF4
gUnknown_0820DEF4:
    .string "Bourse{END}"

    .global gUnknown_0820DEFB
gUnknown_0820DEFB:
    .string "Poudre{END}"

    .global gUnknown_0820DF02
gUnknown_0820DF02:
    .string "CléL{END}"

    .global gUnknown_0820DF07
gUnknown_0820DF07:
    .string "CléN{END}"

    .global gUnknown_0820DF0C
gUnknown_0820DF0C:
    .string "Miroir{END}"

    .global gUnknown_0820DF13
gUnknown_0820DF13:
    .string "Livre{END}"

    .global gUnknown_0820DF19
gUnknown_0820DF19:
    .string "Sardine{END}"

    .global gUnknown_0820DF21
gUnknown_0820DF21:
    .string "Maqureau{END}"

    .global gUnknown_0820DF2A
gUnknown_0820DF2A:
    .string "Sole{END}"

    .global gUnknown_0820DF2F
gUnknown_0820DF2F:
    .string "Truite{END}"

    .global gUnknown_0820DF36
gUnknown_0820DF36:
    .string "Ecrev{END}"

    .global gUnknown_0820DF3C
gUnknown_0820DF3C:
    .string "Pince{END}"

    .global gUnknown_0820DF42
gUnknown_0820DF42:
    .string "Thon{END}"

    .global gUnknown_0820DF47
gUnknown_0820DF47:
    .string "PBulle{END}"

    .global gUnknown_0820DF4E
gUnknown_0820DF4E:
    .string "Canne1{END}"

    .global gUnknown_0820DF55
gUnknown_0820DF55:
    .string "Canne2{END}"

    .global gUnknown_0820DF5C
gUnknown_0820DF5C:
    .string "Canne3{END}"

    .global gUnknown_0820DF63
gUnknown_0820DF63:
    .string "Canne4{END}"

    .global gUnknown_0820DF6A
gUnknown_0820DF6A:
    .string "Canne5{END}"

    .global gUnknown_0820DF71
gUnknown_0820DF71:
    .string "Fer{END}"

    .global gUnknown_0820DF75
gUnknown_0820DF75:
    .string "Clé{END}"

    .global gUnknown_0820DF79
gUnknown_0820DF79:
    .string "Vitamn{END}"

    .global gUnknown_0820DF80
gUnknown_0820DF80:
    .string "Statue{END}"

    .global gUnknown_0820DF87
gUnknown_0820DF87:
    .string "VOeuf{END}"

    .global gUnknown_0820DF8D
gUnknown_0820DF8D:
    .string "Biens{END}"

    .global gUnknown_0820DF93
gUnknown_0820DF93:
    .string "Oeuf{END}"

    .global gUnknown_0820DF98
gUnknown_0820DF98:
    .string "Sphère{END}"

    .global gUnknown_0820DF9F
gUnknown_0820DF9F:
    .string "Brnchies{END}"

    .global gUnknown_0820DFA8
gUnknown_0820DFA8:
    .string "Ling{END}"

    .global gUnknown_0820DFAD
gUnknown_0820DFAD:
    .string "Glaçon{END}"

    .global gUnknown_0820DFB4
gUnknown_0820DFB4:
    .string "Fifre{END}"

    .global gUnknown_0820DFBA
gUnknown_0820DFBA:
    .string "Passe{END}"

    .global gUnknown_0820DFC0
gUnknown_0820DFC0:
    .string "PiècesC{END}"

    .global gUnknown_0820DFC8
gUnknown_0820DFC8:
    .string "Pièces{END}"

    .global gUnknown_0820DFCF
gUnknown_0820DFCF:
    .string "CoeurDr{END}"

    .global gUnknown_0820DFD7
gUnknown_0820DFD7:
    .string "Carte{END}"

    .global gUnknown_0820DFDD
gUnknown_0820DFDD:
    .string "Liste{END}"

    .global gUnknown_0820DFE3
gUnknown_0820DFE3:
    .string "Kézako{END}"

    .global gUnknown_0820DFEA
gUnknown_0820DFEA:
    .string "Note1{END}"

    .global gUnknown_0820DFF0
gUnknown_0820DFF0:
    .string "Note2{END}"

    .global gUnknown_0820DFF6
gUnknown_0820DFF6:
    .string "GrifG{END}"

    .global gUnknown_0820DFFC
gUnknown_0820DFFC:
    .string "CléTps{END}"

    .global gUnknown_0820E003
gUnknown_0820E003:
    .string "Boomg{END}"

    .global gUnknown_0820E009
gUnknown_0820E009:
    .string "CléCiel{END}"

    .global gUnknown_0820E011
gUnknown_0820E011:
    .string "Capuch{END}"

    .global gUnknown_0820E018
gUnknown_0820E018:
    .string "Travrsin{END}"

    .global gUnknown_0820E021
gUnknown_0820E021:
    .string "Maestro{END}"

    .global gUnknown_0820E029
gUnknown_0820E029:
    .string "Mouche{END}"

    .global gUnknown_0820E030
gUnknown_0820E030:
    .string "Huile{END}"

    .global gUnknown_0820E036
gUnknown_0820E036:
    .string "SoinsM{END}"

    .global gUnknown_0820E03D
gUnknown_0820E03D:
    .string "Melon{END}"

    .global gUnknown_0820E043
gUnknown_0820E043:
    .string "Fruit{END}"

    .global gUnknown_0820E049
gUnknown_0820E049:
    .string "Poisson{END}"

    .global gUnknown_0820E051
gUnknown_0820E051:
    .string "Racine{END}"

    .global gUnknown_0820E058
gUnknown_0820E058:
    .string "NoixCoc{END}"

    .global gUnknown_0820E060
gUnknown_0820E060:
    .string "BoisB{END}"

    .global gUnknown_0820E066
gUnknown_0820E066:
    .string "Frtfiant{END}"

    .global gUnknown_0820E06F
gUnknown_0820E06F:
    .string "Herbe X9{END}"

    .global gUnknown_0820E078
gUnknown_0820E078:
    .string "FourmiX9{END}"

    .global gUnknown_0820E081
gUnknown_0820E081:
    .string "Larme X9{END}"

    .global gUnknown_0820E08A
gUnknown_0820E08A:
    .string "CharmeX9{END}"

    .global gUnknown_0820E093
gUnknown_0820E093:
    .string "Soin  X9{END}"

    .global gUnknown_0820E09C
gUnknown_0820E09C:
    .string "Gland X9{END}"

