    .global gUnknown_0820DAF5
gUnknown_0820DAF5:
    .string "Où ?{END}"

    .global gUnknown_0820DAFA
gUnknown_0820DAFA:
    .string "Drogen{END}"

    .global gUnknown_0820DB01
gUnknown_0820DB01:
    .string "Nanaï{END}"

    .global gUnknown_0820DB07
gUnknown_0820DB07:
    .string "Winlan{END}"

    .global gUnknown_0820DB0E
gUnknown_0820DB0E:
    .string "Roméro{END}"

    .global gUnknown_0820DB15
gUnknown_0820DB15:
    .string "Gust{END}"

    .global gUnknown_0820DB1A
gUnknown_0820DB1A:
    .string "Camlon{END}"

    .global gUnknown_0820DB21
gUnknown_0820DB21:
    .string "Nada{END}"

    .global gUnknown_0820DB26
gUnknown_0820DB26:
    .string "Tantar{END}"

    .global gUnknown_0820DB2D
gUnknown_0820DB2D:
    .string "Tuntar{END}"

    .global gUnknown_0820DB34
gUnknown_0820DB34:
    .string "Agua{END}"

    .global gUnknown_0820DB39
gUnknown_0820DB39:
    .string "Auria{END}"

    .global gUnknown_0820DB3F
gUnknown_0820DB3F:
    .string "Tryste{END}"

    .global gUnknown_0820DB46
gUnknown_0820DB46:
    .string "Arad{END}"

    .global gUnknown_0820DB4B
gUnknown_0820DB4B:
    .string "Printemps{END}"

    .global gUnknown_0820DB55
gUnknown_0820DB55:
    .string "Tunlan{END}"

    .global gUnknown_0820DB5C
gUnknown_0820DB5C:
    .string "Gant{END}"

    .global gUnknown_0820DB61
gUnknown_0820DB61:
    .string "Scande{END}"

    .global gUnknown_0820DB68
gUnknown_0820DB68:
    .string "Carmen{END}"

    .global gUnknown_0820DB6F
gUnknown_0820DB6F:
    .string "Gramor{END}"

    .global gUnknown_0820DB76
gUnknown_0820DB76:
    .string "Wisdon{END}"

    .global gUnknown_0820DB7D
gUnknown_0820DB7D:
    .string "Karma{END}"

    .global gUnknown_0820DB83
gUnknown_0820DB83:
    .string "Prima{END}"

    .global gUnknown_0820DB89
gUnknown_0820DB89:
    .string "Crypte{END}"

    .global gUnknown_0820DB90
gUnknown_0820DB90:
    .string "Nabal{END}"

    .global gUnknown_0820DB96
gUnknown_0820DB96:
    .string "Tock{END}"

    .global gUnknown_0820DB9B
gUnknown_0820DB9B:
    .string "Cyme{END}"

    .global gUnknown_0820DBA0
gUnknown_0820DBA0:
    .string "Obélisque{END}"

    .global gUnknown_0820DBAA
gUnknown_0820DBAA:
    .string "Pagode{END}"

    .global gUnknown_0820DBB1
gUnknown_0820DBB1:
    .string "Chapelle Drag{END}"

    .global gUnknown_0820DBBF
gUnknown_0820DBBF:
    .string "Temple Drag{END}"

    .global gUnknown_0820DBCB
gUnknown_0820DBCB:
    .string "Bois de Ramui{END}"

    .global gUnknown_0820DBD9
gUnknown_0820DBD9:
    .string "Grotte Aura{END}"

    .global gUnknown_0820DBE5
gUnknown_0820DBE5:
    .string "Forêt triste{END}"

    .global gUnknown_0820DBF2
gUnknown_0820DBF2:
    .string "Temple Gaia{END}"

    .global gUnknown_0820DBFE
gUnknown_0820DBFE:
    .string "Grotte Lac{END}"

    .global gUnknown_0820DC09
gUnknown_0820DC09:
    .string "Chapelle Lac{END}"

    .global gUnknown_0820DC16
gUnknown_0820DC16:
    .string "Caverne Cap{END}"

    .global gUnknown_0820DC22
gUnknown_0820DC22:
    .string "Caverne Aise{END}"

    .global gUnknown_0820DC2F
gUnknown_0820DC2F:
    .string "Tristebois{END}"

    .global gUnknown_0820DC3A
gUnknown_0820DC3A:
    .string "Fortin Drg N{END}"

    .global gUnknown_0820DC47
gUnknown_0820DC47:
    .string "Base secrète{END}"

    .global gUnknown_0820DC54
gUnknown_0820DC54:
    .string "Géant{END}"

    .global gUnknown_0820DC5A
gUnknown_0820DC5A:
    .string "Navire Drg N{END}"

    .global gUnknown_0820DC67
gUnknown_0820DC67:
    .string "Caverne L&N{END}"

    .global gUnknown_0820DC73
gUnknown_0820DC73:
    .string "Fortin caché{END}"

    .global gUnknown_0820DC80
gUnknown_0820DC80:
    .string "Tour L&N{END}"

    .global gUnknown_0820DC89
gUnknown_0820DC89:
    .string "Volcan marin{END}"

    .global gUnknown_0820DC96
gUnknown_0820DC96:
    .string "Tour Diable{END}"

    .global gUnknown_0820DCA2
gUnknown_0820DCA2:
    .string "Pays sauvage{END}"

    .global gUnknown_0820DCAF
gUnknown_0820DCAF:
    .string "Tour Marais{END}"

    .global gUnknown_0820DCBB
gUnknown_0820DCBB:
    .string "Bois Fées{END}"

    .global gUnknown_0820DCC5
gUnknown_0820DCC5:
    .string "Ville Marais{END}"

    .global gUnknown_0820DCD2
gUnknown_0820DCD2:
    .string "Labo{END}"

    .global gUnknown_0820DCD7
gUnknown_0820DCD7:
    .string "Trou souris{END}"

    .global gUnknown_0820DCE3
gUnknown_0820DCE3:
    .string "Caverne gren{END}"

    .global gUnknown_0820DCF0
gUnknown_0820DCF0:
    .string "Grotte du sud{END}"

    .global gUnknown_0820DCFE
gUnknown_0820DCFE:
    .string "Château sud{END}"

    .global gUnknown_0820DD0A
gUnknown_0820DD0A:
    .string "Ville onirik{END}"

    .global gUnknown_0820DD17
gUnknown_0820DD17:
    .string "Maison sage{END}"

    .global gUnknown_0820DD23
gUnknown_0820DD23:
    .string "Maison femme{END}"

    .global gUnknown_0820DD30
gUnknown_0820DD30:
    .string "Grotte désert{END}"

    .global gUnknown_0820DD3E
gUnknown_0820DD3E:
    .string "Grotte Hiver{END}"

    .global gUnknown_0820DD4B
gUnknown_0820DD4B:
    .string "Salle secrète{END}"

