    .global gUnknown_0820E823
gUnknown_0820E823:
    .string "Soins1{END}"

    .global gUnknown_0820E82A
gUnknown_0820E82A:
    .string "Vig{END}"

    .global gUnknown_0820E82E
gUnknown_0820E82E:
    .string "Inactif{END}"

    .global gUnknown_0820E836
gUnknown_0820E836:
    .string "AugmCh{END}"

    .global gUnknown_0820E83D
gUnknown_0820E83D:
    .string "AugmAtt{END}"

    .global gUnknown_0820E845
gUnknown_0820E845:
    .string "Soins2{END}"

    .global gUnknown_0820E84C
gUnknown_0820E84C:
    .string "Immob{END}"

    .global gUnknown_0820E852
gUnknown_0820E852:
    .string "AugmAg{END}"

    .global gUnknown_0820E859
gUnknown_0820E859:
    .string "Zom1{END}"

    .global gUnknown_0820E85E
gUnknown_0820E85E:
    .string "Soins3{END}"

    .global gUnknown_0820E865
gUnknown_0820E865:
    .string "Renouv{END}"

    .global gUnknown_0820E86C
gUnknown_0820E86C:
    .string "Guéris{END}"

    .global gUnknown_0820E873
gUnknown_0820E873:
    .string "Boucl{END}"

    .global gUnknown_0820E879
gUnknown_0820E879:
    .string "Soins4{END}"

    .global gUnknown_0820E880
gUnknown_0820E880:
    .string "Zom2{END}"

    .global gUnknown_0820E885
gUnknown_0820E885:
    .string "VigX{END}"

    .global gUnknown_0820E88A
gUnknown_0820E88A:
    .string "Chut{END}"

    .global gUnknown_0820E88F
gUnknown_0820E88F:
    .string "Dissipe{END}"

    .global gUnknown_0820E897
gUnknown_0820E897:
    .string "RenouvX{END}"

    .global gUnknown_0820E89F
gUnknown_0820E89F:
    .string "SoinsX{END}"

    .global gUnknown_0820E8A6
gUnknown_0820E8A6:
    .string "Mur{END}"

    .global gUnknown_0820E8AA
gUnknown_0820E8AA:
    .string "ZomX{END}"

    .global gUnknown_0820E8AF
gUnknown_0820E8AF:
    .string "Lueur{END}"

    .global gUnknown_0820E8B5
gUnknown_0820E8B5:
    .string "Etincel{END}"

    .global gUnknown_0820E8BD
gUnknown_0820E8BD:
    .string "Froid{END}"

    .global gUnknown_0820E8C3
gUnknown_0820E8C3:
    .string "35{END}"

    .global gUnknown_0820E8C6
gUnknown_0820E8C6:
    .string "Para{END}"

    .global gUnknown_0820E8CB
gUnknown_0820E8CB:
    .string "Draine{END}"

    .global gUnknown_0820E8D2
gUnknown_0820E8D2:
    .string "Frotte{END}"

    .global gUnknown_0820E8D9
gUnknown_0820E8D9:
    .string "Flamme{END}"

    .global gUnknown_0820E8E0
gUnknown_0820E8E0:
    .string "Grille{END}"

    .global gUnknown_0820E8E7
gUnknown_0820E8E7:
    .string "Givre{END}"

    .global gUnknown_0820E8ED
gUnknown_0820E8ED:
    .string "55{END}"

    .global gUnknown_0820E8F0
gUnknown_0820E8F0:
    .string "BouleFeu{END}"

    .global gUnknown_0820E8F9
gUnknown_0820E8F9:
    .string "Orage{END}"

    .global gUnknown_0820E8FF
gUnknown_0820E8FF:
    .string "Gel{END}"

    .global gUnknown_0820E903
gUnknown_0820E903:
    .string "95{END}"

    .global gUnknown_0820E906
gUnknown_0820E906:
    .string "Vent{END}"

    .global gUnknown_0820E90B
gUnknown_0820E90B:
    .string "Glace{END}"

    .global gUnknown_0820E911
gUnknown_0820E911:
    .string "Carbon{END}"

    .global gUnknown_0820E918
gUnknown_0820E918:
    .string "GlaceX{END}"

    .global gUnknown_0820E91F
gUnknown_0820E91F:
    .string "FeuX{END}"

    .global gUnknown_0820E924
gUnknown_0820E924:
    .string "EclairX{END}"

    .global gUnknown_0820E92C
gUnknown_0820E92C:
    .string "Absorbe{END}"

    .global gUnknown_0820E934
gUnknown_0820E934:
    .string "???1{END}"

    .global gUnknown_0820E939
gUnknown_0820E939:
    .string "Comète{END}"

    .global gUnknown_0820E940
gUnknown_0820E940:
    .string "???2{END}"

    .global gUnknown_0820E945
gUnknown_0820E945:
    .string "???3{END}"

    .global gUnknown_0820E94A
gUnknown_0820E94A:
    .string "???4{END}"

    .global gUnknown_0820E94F
gUnknown_0820E94F:
    .string "???5{END}"

    .global gUnknown_0820E954
gUnknown_0820E954:
    .string "???6{END}"

    .global gUnknown_0820E959
gUnknown_0820E959:
    .string "???7{END}"

    .global gUnknown_0820E95E
gUnknown_0820E95E:
    .string "Soins1{END}"

    .global gUnknown_0820E965
gUnknown_0820E965:
    .string "RenouvX{END}"

    .global gUnknown_0820E96D
gUnknown_0820E96D:
    .string "Edd{END}"

    .global gUnknown_0820E971
gUnknown_0820E971:
    .string "EddX{END}"

    .global gUnknown_0820E976
gUnknown_0820E976:
    .string "Eco{END}"

    .global gUnknown_0820E97A
gUnknown_0820E97A:
    .string "EcoX{END}"

    .global gUnknown_0820E97F
gUnknown_0820E97F:
    .string "???8{END}"

    .global gUnknown_0820E984
gUnknown_0820E984:
    .string "???9{END}"

    .global gUnknown_0820E989
gUnknown_0820E989:
    .string "???10{END}"

    .global gUnknown_0820E98F
gUnknown_0820E98F:
    .string "???12{END}"

    .global gUnknown_0820E995
gUnknown_0820E995:
    .string "???13{END}"

    .global gUnknown_0820E99B
gUnknown_0820E99B:
    .string "???14{END}"

    .global gUnknown_0820E9A1
gUnknown_0820E9A1:
    .string "???15{END}"

    .global gUnknown_0820E9A7
gUnknown_0820E9A7:
    .string "???16{END}"

    .global gUnknown_0820E9AD
gUnknown_0820E9AD:
    .string "???17{END}"

    .global gUnknown_0820E9B3
gUnknown_0820E9B3:
    .string "ZomX{END}"

    .global gUnknown_0820E9B8
gUnknown_0820E9B8:
    .string "???18{END}"

    .global gUnknown_0820E9BE
gUnknown_0820E9BE:
    .string "???19{END}"

    .global gUnknown_0820E9C4
gUnknown_0820E9C4:
    .string "Bombe{END}"

    .global gUnknown_0820E9CA
gUnknown_0820E9CA:
    .string "Boum{END}"

    .global gUnknown_0820E9CF
gUnknown_0820E9CF:
    .string "Télép{END}"

    .global gUnknown_0820E9D5
gUnknown_0820E9D5:
    .string "Fuite{END}"

    .global gUnknown_0820E9DB
gUnknown_0820E9DB:
    .string "Explos{END}"

    .global gUnknown_0820E9E2
gUnknown_0820E9E2:
    .string "Sortie{END}"

    .global gUnknown_0820E9E9
gUnknown_0820E9E9:
    .string "Nova{END}"

    .global gUnknown_0820E9EE
gUnknown_0820E9EE:
    .string "NovaX{END}"

    .global gUnknown_0820E9F4
gUnknown_0820E9F4:
    .string "???20{END}"

    .global gUnknown_0820E9FA
gUnknown_0820E9FA:
    .string "???21{END}"

