    .global gUnknown_0820D3FB
gUnknown_0820D3FB:
    .string "Rend 50 PV{END}"

    .global gUnknown_0820D406
gUnknown_0820D406:
    .string "Améliore la défense temp.{END}"

    .global gUnknown_0820D420
gUnknown_0820D420:
    .string "Ralentit l'ennemi{END}"

    .global gUnknown_0820D432
gUnknown_0820D432:
    .string "Augmente la chance temp.{END}"

    .global gUnknown_0820D44B
gUnknown_0820D44B:
    .string "Améliore l'attaque temp.{END}"

    .global gUnknown_0820D464
gUnknown_0820D464:
    .string "Rend 100 PV{END}"

    .global gUnknown_0820D470
gUnknown_0820D470:
    .string "Immobilise l'ennemi{END}"

    .global gUnknown_0820D484
gUnknown_0820D484:
    .string "Augmente l'agilité temp.{END}"

    .global gUnknown_0820D49D
gUnknown_0820D49D:
    .string "Ange Niv 1 un seul ennemi{END}"

    .global gUnknown_0820D4B7
gUnknown_0820D4B7:
    .string "Rend 250 PV{END}"

    .global gUnknown_0820D4C3
gUnknown_0820D4C3:
    .string "Soigne l'étourdissement 1 PV{END}"

    .global gUnknown_0820D4E0
gUnknown_0820D4E0:
    .string "Soigne tout état anormal{END}"

    .global gUnknown_0820D4F9
gUnknown_0820D4F9:
    .string "Réduit les dégâts magiques{END}"

    .global gUnknown_0820D514
gUnknown_0820D514:
    .string "Rend tous les PV{END}"

    .global gUnknown_0820D525
gUnknown_0820D525:
    .string "Ange Niv 2 un seul ennemi{END}"

    .global gUnknown_0820D53F
gUnknown_0820D53F:
    .string "Améliore la défense de tous{END}"

    .global gUnknown_0820D55B
gUnknown_0820D55B:
    .string "Bloque la magie ennemie temp{END}"

    .global gUnknown_0820D578
gUnknown_0820D578:
    .string "Annule une magie ennemie{END}"

    .global gUnknown_0820D591
gUnknown_0820D591:
    .string "Annule l'étourdissement{END}"

    .global gUnknown_0820D5A9
gUnknown_0820D5A9:
    .string "Rend 250 PV à tous{END}"

    .global gUnknown_0820D5BC
gUnknown_0820D5BC:
    .string "Renvoie la magie ennemie 1x{END}"

    .global gUnknown_0820D5D8
gUnknown_0820D5D8:
    .string "Ange Niv 3 groupe ennemi{END}"

    .global gUnknown_0820D5F1
gUnknown_0820D5F1:
    .string "Feu Niv 1 un seul ennemi{END}"

    .global gUnknown_0820D60A
gUnknown_0820D60A:
    .string "Tonnerre Niv 1 sur un ennemi{END}"

    .global gUnknown_0820D627
gUnknown_0820D627:
    .string "Glace Niv 1 sur un ennemi{END}"

    .global gUnknown_0820D641
gUnknown_0820D641:
    .string "Secousse Niv 1 sur un ennemi{END}"

    .global gUnknown_0820D65E
gUnknown_0820D65E:
    .string "Arrête le temps pour l'ennemi{END}"

    .global gUnknown_0820D67C
gUnknown_0820D67C:
    .string "Absorbe les PV de l'ennemi{END}"

    .global gUnknown_0820D697
gUnknown_0820D697:
    .string "Peine de mort un seul ennemi{END}"

    .global gUnknown_0820D6B4
gUnknown_0820D6B4:
    .string "Feu Niv 2 sur un ennemi{END}"

    .global gUnknown_0820D6CC
gUnknown_0820D6CC:
    .string "Tonnerre Niv 2 sur un ennemi{END}"

    .global gUnknown_0820D6E9
gUnknown_0820D6E9:
    .string "Glace Niv 2 sur un ennemi{END}"

    .global gUnknown_0820D703
gUnknown_0820D703:
    .string "Secousse Niv 2 groupe ennemi{END}"

    .global gUnknown_0820D720
gUnknown_0820D720:
    .string "Feu Niv 3 sur un ennemi{END}"

    .global gUnknown_0820D738
gUnknown_0820D738:
    .string "Tonnerre Niv 4 groupe ennemi{END}"

    .global gUnknown_0820D755
gUnknown_0820D755:
    .string "Glace Niv 3 groupe ennemi{END}"

    .global gUnknown_0820D76F
gUnknown_0820D76F:
    .string "Secousse Niv 3 groupe ennemi{END}"

    .global gUnknown_0820D78C
gUnknown_0820D78C:
    .string "Tonnerre Niv 5 groupe ennemi{END}"

    .global gUnknown_0820D7A9
gUnknown_0820D7A9:
    .string "Glace Niv 4 groupe ennemi{END}"

    .global gUnknown_0820D7C3
gUnknown_0820D7C3:
    .string "Feu Niv 5 groupe ennemi{END}"

    .global gUnknown_0820D7DB
gUnknown_0820D7DB:
    .string "Glace Niv 5 sur un ennemi{END}"

    .global gUnknown_0820D7F5
gUnknown_0820D7F5:
    .string "Feu Niv 4 sur un ennemi{END}"

    .global gUnknown_0820D80D
gUnknown_0820D80D:
    .string "Tonnerre Niv 3 sur un ennemi{END}"

    .global gUnknown_0820D82A
gUnknown_0820D82A:
    .string "Absorbe les PC de l'ennemi{END}"

    .global gUnknown_0820D845
gUnknown_0820D845:
    .string "Faux{END}"

    .global gUnknown_0820D84A
gUnknown_0820D84A:
    .string "Tempête de météores ennemis{END}"

    .global gUnknown_0820D866
gUnknown_0820D866:
    .string "Faux{END}"

    .global gUnknown_0820D86B
gUnknown_0820D86B:
    .string "Faux{END}"

    .global gUnknown_0820D870
gUnknown_0820D870:
    .string "Faux{END}"

    .global gUnknown_0820D875
gUnknown_0820D875:
    .string "Faux{END}"

    .global gUnknown_0820D87A
gUnknown_0820D87A:
    .string "Faux{END}"

    .global gUnknown_0820D87F
gUnknown_0820D87F:
    .string "Faux{END}"

    .global gUnknown_0820D884
gUnknown_0820D884:
    .string "Faux{END}"

    .global gUnknown_0820D889
gUnknown_0820D889:
    .string "Soigne l'étourdissement max{END}"

    .global gUnknown_0820D8A5
gUnknown_0820D8A5:
    .string "Utilisé au combat sous l'eau{END}"

    .global gUnknown_0820D8C2
gUnknown_0820D8C2:
    .string "Utilisé au combat sous l'eau{END}"

    .global gUnknown_0820D8DF
gUnknown_0820D8DF:
    .string "Utilisé au combat sous l'eau{END}"

    .global gUnknown_0820D8FC
gUnknown_0820D8FC:
    .string "Utilisé au combat sous l'eau{END}"

    .global gUnknown_0820D919
gUnknown_0820D919:
    .string "Faux{END}"

    .global gUnknown_0820D91E
gUnknown_0820D91E:
    .string "Faux{END}"

    .global gUnknown_0820D923
gUnknown_0820D923:
    .string "Faux{END}"

    .global gUnknown_0820D928
gUnknown_0820D928:
    .string "Faux{END}"

    .global gUnknown_0820D92D
gUnknown_0820D92D:
    .string "Faux{END}"

    .global gUnknown_0820D932
gUnknown_0820D932:
    .string "Faux{END}"

    .global gUnknown_0820D937
gUnknown_0820D937:
    .string "Faux{END}"

    .global gUnknown_0820D93C
gUnknown_0820D93C:
    .string "Faux{END}"

    .global gUnknown_0820D941
gUnknown_0820D941:
    .string "Faux{END}"

    .global gUnknown_0820D946
gUnknown_0820D946:
    .string "Ange Niv 3 groupe ennemi{END}"

    .global gUnknown_0820D95F
gUnknown_0820D95F:
    .string "Faux{END}"

    .global gUnknown_0820D964
gUnknown_0820D964:
    .string "Faux{END}"

    .global gUnknown_0820D969
gUnknown_0820D969:
    .string "Explosion Niv 1 un ennemi{END}"

    .global gUnknown_0820D983
gUnknown_0820D983:
    .string "Explosion Niv 2 ennemis{END}"

    .global gUnknown_0820D99B
gUnknown_0820D99B:
    .string "Téléporte en ville{END}"

    .global gUnknown_0820D9AE
gUnknown_0820D9AE:
    .string "Permet de fuir le combat{END}"

    .global gUnknown_0820D9C7
gUnknown_0820D9C7:
    .string "Explosion Niv 3 un ennemi{END}"

    .global gUnknown_0820D9E1
gUnknown_0820D9E1:
    .string "S'échapper des souterrains{END}"

    .global gUnknown_0820D9FC
gUnknown_0820D9FC:
    .string "Explosion Niv 4 ennemis{END}"

    .global gUnknown_0820DA14
gUnknown_0820DA14:
    .string "Explosion Niv 5 un emnnemi{END}"

    .global gUnknown_0820DA2F
gUnknown_0820DA2F:
    .string "Faux{END}"

    .global gUnknown_0820DA34
gUnknown_0820DA34:
    .string "Faux{END}"

    .global gUnknown_0820DA39
gUnknown_0820DA39:
    .string "Creuse pour fuir le combat{END}"

    .global gUnknown_0820DA54
gUnknown_0820DA54:
    .string "Utilisé au combat{END}"

    .global gUnknown_0820DA66
gUnknown_0820DA66:
    .string "Les personnages fusionnent{END}"

    .global gUnknown_0820DA81
gUnknown_0820DA81:
    .string "Disponible sous l'eau{END}"

    .global gUnknown_0820DA97
gUnknown_0820DA97:
    .string "Disponible sur terre{END}"

    .global gUnknown_0820DAAC
gUnknown_0820DAAC:
    .string "Les personnages fusionnent{END}"

    .global gUnknown_0820DAC7
gUnknown_0820DAC7:
    .string "Défusionne les personnages{END}"

    .global gUnknown_0820DAE2
gUnknown_0820DAE2:
    .string "Rend forme humaine{END}"

