    .global gUnknown_0820E0A5
gUnknown_0820E0A5:
    .string "Couteau{END}"

    .global gUnknown_0820E0AD
gUnknown_0820E0AD:
    .string "EpBronz{END}"

    .global gUnknown_0820E0B5
gUnknown_0820E0B5:
    .string "Sabre{END}"

    .global gUnknown_0820E0BB
gUnknown_0820E0BB:
    .string "Faux{END}"

    .global gUnknown_0820E0C0
gUnknown_0820E0C0:
    .string "EpLong{END}"

    .global gUnknown_0820E0C7
gUnknown_0820E0C7:
    .string "EpDrag{END}"

    .global gUnknown_0820E0CE
gUnknown_0820E0CE:
    .string "EpPuis{END}"

    .global gUnknown_0820E0D5
gUnknown_0820E0D5:
    .string "EpAilée{END}"

    .global gUnknown_0820E0DD
gUnknown_0820E0DD:
    .string "EpEmp{END}"

    .global gUnknown_0820E0E3
gUnknown_0820E0E3:
    .string "EpCass{END}"

    .global gUnknown_0820E0EA
gUnknown_0820E0EA:
    .string "Faux{END}"

    .global gUnknown_0820E0EF
gUnknown_0820E0EF:
    .string "EpFeu{END}"

    .global gUnknown_0820E0F5
gUnknown_0820E0F5:
    .string "Faucille{END}"

    .global gUnknown_0820E0FE
gUnknown_0820E0FE:
    .string "EpLarge{END}"

    .global gUnknown_0820E106
gUnknown_0820E106:
    .string "EpMyst{END}"

    .global gUnknown_0820E10D
gUnknown_0820E10D:
    .string "ArmeSp{END}"

    .global gUnknown_0820E114
gUnknown_0820E114:
    .string "RapCour{END}"

    .global gUnknown_0820E11C
gUnknown_0820E11C:
    .string "Rapière{END}"

    .global gUnknown_0820E124
gUnknown_0820E124:
    .string "RapFer{END}"

    .global gUnknown_0820E12B
gUnknown_0820E12B:
    .string "RapEmpoi{END}"

    .global gUnknown_0820E134
gUnknown_0820E134:
    .string "RapLèg{END}"

    .global gUnknown_0820E13B
gUnknown_0820E13B:
    .string "Faux{END}"

    .global gUnknown_0820E140
gUnknown_0820E140:
    .string "RapFeu{END}"

    .global gUnknown_0820E147
gUnknown_0820E147:
    .string "RapAilée{END}"

    .global gUnknown_0820E150
gUnknown_0820E150:
    .string "RapBron{END}"

    .global gUnknown_0820E158
gUnknown_0820E158:
    .string "RapMal{END}"

    .global gUnknown_0820E15F
gUnknown_0820E15F:
    .string "RapTonn{END}"

    .global gUnknown_0820E167
gUnknown_0820E167:
    .string "Faux{END}"

    .global gUnknown_0820E16C
gUnknown_0820E16C:
    .string "RapLoi{END}"

    .global gUnknown_0820E173
gUnknown_0820E173:
    .string "RapPuiss{END}"

    .global gUnknown_0820E17C
gUnknown_0820E17C:
    .string "MartFer{END}"

    .global gUnknown_0820E184
gUnknown_0820E184:
    .string "MartEpn{END}"

    .global gUnknown_0820E18C
gUnknown_0820E18C:
    .string "Gourdin{END}"

    .global gUnknown_0820E194
gUnknown_0820E194:
    .string "MartG{END}"

    .global gUnknown_0820E19A
gUnknown_0820E19A:
    .string "MartFeu{END}"

    .global gUnknown_0820E1A2
gUnknown_0820E1A2:
    .string "Faux{END}"

    .global gUnknown_0820E1A7
gUnknown_0820E1A7:
    .string "MartRage{END}"

    .global gUnknown_0820E1B0
gUnknown_0820E1B0:
    .string "Faux{END}"

    .global gUnknown_0820E1B5
gUnknown_0820E1B5:
    .string "Maillet{END}"

    .global gUnknown_0820E1BD
gUnknown_0820E1BD:
    .string "MartEtoi{END}"

    .global gUnknown_0820E1C6
gUnknown_0820E1C6:
    .string "Bâton{END}"

    .global gUnknown_0820E1CC
gUnknown_0820E1CC:
    .string "Canne{END}"

    .global gUnknown_0820E1D2
gUnknown_0820E1D2:
    .string "CanneOs{END}"

    .global gUnknown_0820E1DA
gUnknown_0820E1DA:
    .string "CanneMal{END}"

    .global gUnknown_0820E1E3
gUnknown_0820E1E3:
    .string "Faux{END}"

    .global gUnknown_0820E1E8
gUnknown_0820E1E8:
    .string "CanneGl{END}"

    .global gUnknown_0820E1F0
gUnknown_0820E1F0:
    .string "Faux{END}"

    .global gUnknown_0820E1F5
gUnknown_0820E1F5:
    .string "CanneBr{END}"

    .global gUnknown_0820E1FD
gUnknown_0820E1FD:
    .string "Faux{END}"

    .global gUnknown_0820E202
gUnknown_0820E202:
    .string "GrBâton{END}"

    .global gUnknown_0820E20A
gUnknown_0820E20A:
    .string "Pique{END}"

    .global gUnknown_0820E210
gUnknown_0820E210:
    .string "Javeline{END}"

    .global gUnknown_0820E219
gUnknown_0820E219:
    .string "VLance{END}"

    .global gUnknown_0820E220
gUnknown_0820E220:
    .string "LanHér{END}"

    .global gUnknown_0820E227
gUnknown_0820E227:
    .string "Trident{END}"

    .global gUnknown_0820E22F
gUnknown_0820E22F:
    .string "Faux{END}"

    .global gUnknown_0820E234
gUnknown_0820E234:
    .string "Dormeuse{END}"

    .global gUnknown_0820E23D
gUnknown_0820E23D:
    .string "Faux{END}"

    .global gUnknown_0820E242
gUnknown_0820E242:
    .string "ArbCreus{END}"

    .global gUnknown_0820E24B
gUnknown_0820E24B:
    .string "ArbRouil{END}"

    .global gUnknown_0820E254
gUnknown_0820E254:
    .string "ArbFer{END}"

    .global gUnknown_0820E25B
gUnknown_0820E25B:
    .string "ArbGl{END}"

    .global gUnknown_0820E261
gUnknown_0820E261:
    .string "Faux{END}"

    .global gUnknown_0820E266
gUnknown_0820E266:
    .string "ArbMyst{END}"

    .global gUnknown_0820E26E
gUnknown_0820E26E:
    .string "Faux{END}"

    .global gUnknown_0820E273
gUnknown_0820E273:
    .string "DagLanc{END}"

    .global gUnknown_0820E27B
gUnknown_0820E27B:
    .string "Dague{END}"

    .global gUnknown_0820E281
gUnknown_0820E281:
    .string "Dard{END}"

    .global gUnknown_0820E286
gUnknown_0820E286:
    .string "TriDag{END}"

    .global gUnknown_0820E28D
gUnknown_0820E28D:
    .string "DagPuis{END}"

    .global gUnknown_0820E295
gUnknown_0820E295:
    .string "DagFeu{END}"

    .global gUnknown_0820E29C
gUnknown_0820E29C:
    .string "DagArg{END}"

    .global gUnknown_0820E2A3
gUnknown_0820E2A3:
    .string "Faux{END}"

    .global gUnknown_0820E2A8
gUnknown_0820E2A8:
    .string "Faux{END}"

    .global gUnknown_0820E2AD
gUnknown_0820E2AD:
    .string "DagGl{END}"

    .global gUnknown_0820E2B3
gUnknown_0820E2B3:
    .string "Faux{END}"

    .global gUnknown_0820E2B8
gUnknown_0820E2B8:
    .string "DagNr{END}"

    .global gUnknown_0820E2BE
gUnknown_0820E2BE:
    .string "Faux{END}"

    .global gUnknown_0820E2C3
gUnknown_0820E2C3:
    .string "ArcBronz{END}"

    .global gUnknown_0820E2CC
gUnknown_0820E2CC:
    .string "ArcCour{END}"

    .global gUnknown_0820E2D4
gUnknown_0820E2D4:
    .string "ArcLong{END}"

    .global gUnknown_0820E2DC
gUnknown_0820E2DC:
    .string "ArcAcier{END}"

    .global gUnknown_0820E2E5
gUnknown_0820E2E5:
    .string "ArcEmpoi{END}"

    .global gUnknown_0820E2EE
gUnknown_0820E2EE:
    .string "ArcAcéré{END}"

    .global gUnknown_0820E2F7
gUnknown_0820E2F7:
    .string "ArcLune{END}"

    .global gUnknown_0820E2FF
gUnknown_0820E2FF:
    .string "ArcJade{END}"

    .global gUnknown_0820E307
gUnknown_0820E307:
    .string "TriArc{END}"

    .global gUnknown_0820E30E
gUnknown_0820E30E:
    .string "Faux{END}"

    .global gUnknown_0820E313
gUnknown_0820E313:
    .string "Faux{END}"

    .global gUnknown_0820E318
gUnknown_0820E318:
    .string "Faux{END}"

    .global gUnknown_0820E31D
gUnknown_0820E31D:
    .string "ArcNain{END}"

    .global gUnknown_0820E325
gUnknown_0820E325:
    .string "ArcHéros{END}"

    .global gUnknown_0820E32E
gUnknown_0820E32E:
    .string "Faux{END}"

    .global gUnknown_0820E333
gUnknown_0820E333:
    .string "Boomrg{END}"

    .global gUnknown_0820E33A
gUnknown_0820E33A:
    .string "Fleuret{END}"

    .global gUnknown_0820E342
gUnknown_0820E342:
    .string "Trirang{END}"

