    .global gUnknown_08216654
gUnknown_08216654:
    .string "ATT{END}"

    .global gUnknown_08216658
gUnknown_08216658:
    .string "SORT{END}"

    .global gUnknown_0821665D
gUnknown_0821665D:
    .string "OBJ{END}"

    .global gUnknown_08216661
gUnknown_08216661:
    .string "CHNG{END}"

    .global gUnknown_08216666
gUnknown_08216666:
    .string "A{END}"

    .global gUnknown_08216668
gUnknown_08216668:
    .string "U{END}"

    .global gUnknown_0821666A
gUnknown_0821666A:
    .string "T{END}"

    .global gUnknown_0821666C
gUnknown_0821666C:
    .string "O{END}"

    .global gUnknown_0821666E
gUnknown_0821666E:
    .string "V{END}"

    .global gUnknown_08216670
gUnknown_08216670:
    .string "A{END}"

    .global gUnknown_08216672
gUnknown_08216672:
    .string " {END}"

    .global gUnknown_08216674
gUnknown_08216674:
    .string " {END}"

    .global gUnknown_08216676
gUnknown_08216676:
    .string "{0x15}{END}"

    .global gUnknown_08216678
gUnknown_08216678:
    .string "ATTK{END}"

    .global gUnknown_0821667D
gUnknown_0821667D:
    .string "SPEL{END}"

    .global gUnknown_08216682
gUnknown_08216682:
    .string "ITEM{END}"

    .global gUnknown_08216687
gUnknown_08216687:
    .string "CHNG{END}"

    .global gUnknown_0821668C
gUnknown_0821668C:
    .string "A{END}"

    .global gUnknown_0821668E
gUnknown_0821668E:
    .string "U{END}"

    .global gUnknown_08216690
gUnknown_08216690:
    .string "T{END}"

    .global gUnknown_08216692
gUnknown_08216692:
    .string "O{END}"

    .global gUnknown_08216694
gUnknown_08216694:
    .string "R{END}"

    .global gUnknown_08216696
gUnknown_08216696:
    .string "U{END}"

    .global gUnknown_08216698
gUnknown_08216698:
    .string "N{END}"

    .global gUnknown_0821669A
gUnknown_0821669A:
    .string " {END}"

    .global gUnknown_0821669C
gUnknown_0821669C:
    .string "{0x15}{END}"

    .global gUnknown_0821669E
gUnknown_0821669E:
    .string "ANGR{END}"

    .global gUnknown_082166A3
gUnknown_082166A3:
    .string "ZAUB{END}"

    .global gUnknown_082166A8
gUnknown_082166A8:
    .string "OBJK{END}"

    .global gUnknown_082166AD
gUnknown_082166AD:
    .string "POS{END}"

    .global gUnknown_082166B1
gUnknown_082166B1:
    .string "A{END}"

    .global gUnknown_082166B3
gUnknown_082166B3:
    .string "U{END}"

    .global gUnknown_082166B5
gUnknown_082166B5:
    .string "T{END}"

    .global gUnknown_082166B7
gUnknown_082166B7:
    .string "O{END}"

    .global gUnknown_082166B9
gUnknown_082166B9:
    .string "G{END}"

    .global gUnknown_082166BB
gUnknown_082166BB:
    .string "E{END}"

    .global gUnknown_082166BD
gUnknown_082166BD:
    .string "H{END}"

    .global gUnknown_082166BF
gUnknown_082166BF:
    .string " {END}"

    .global gUnknown_082166C1
gUnknown_082166C1:
    .string "{0x15}{END}"

    .global gUnknown_082166C3
gUnknown_082166C3:
    .string "SWCH{END}"

    .global gUnknown_082166C8
gUnknown_082166C8:
    .string "TSCH{END}"

    .global gUnknown_082166CD
gUnknown_082166CD:
    .string "POS{END}"

    .global gUnknown_082166D1
gUnknown_082166D1:
    .string "DFND{END}"

    .global gUnknown_082166D6
gUnknown_082166D6:
    .string "VERT{END}"

    .global gUnknown_082166DB
gUnknown_082166DB:
    .string "DEF{END}"

    .global gUnknown_082166DF
gUnknown_082166DF:
    .string "HP1 {END}"

    .global gUnknown_082166E4
gUnknown_082166E4:
    .string "HP1 {END}"

    .global gUnknown_082166E9
gUnknown_082166E9:
    .string "PV1 {END}"

    .global gUnknown_082166EE
gUnknown_082166EE:
    .string "DUMP{END}"

    .global gUnknown_082166F3
gUnknown_082166F3:
    .string "DUMP{END}"

    .global gUnknown_082166F8
gUnknown_082166F8:
    .string "LACH{END}"

    .global gUnknown_082166FD
gUnknown_082166FD:
    .string "HPMX{END}"

    .global gUnknown_08216702
gUnknown_08216702:
    .string "HPMX{END}"

    .global gUnknown_08216707
gUnknown_08216707:
    .string "PVMX{END}"

    .global gUnknown_0821670C
gUnknown_0821670C:
    .string "Fail{END}"

    .global gUnknown_08216711
gUnknown_08216711:
    .string "Miss{END}"

    .global gUnknown_08216716
gUnknown_08216716:
    .string "Cntr{END}"

    .global gUnknown_0821671B
gUnknown_0821671B:
    .string "Slam{END}"

    .global gUnknown_08216720
gUnknown_08216720:
    .string "Cont{END}"

    .global gUnknown_08216725
gUnknown_08216725:
    .string "Ech{END}"

    .global gUnknown_08216729
gUnknown_08216729:
    .string "Raté{END}"

    .global gUnknown_0821672E
gUnknown_0821672E:
    .string "Cntr{END}"

    .global gUnknown_08216733
gUnknown_08216733:
    .string "Yah!{END}"

    .global gUnknown_08216738
gUnknown_08216738:
    .string "Cont{END}"

    .global gUnknown_0821673D
gUnknown_0821673D:
    .string "Fehl{END}"

    .global gUnknown_08216742
gUnknown_08216742:
    .string "Verf{END}"

    .global gUnknown_08216747
gUnknown_08216747:
    .string "Kntr{END}"

    .global gUnknown_0821674C
gUnknown_0821674C:
    .string "Slam{END}"

    .global gUnknown_08216751
gUnknown_08216751:
    .string "Ver{END}"

    .global gUnknown_08216755
gUnknown_08216755:
    .string " Used in battle.{END}"

    .global gUnknown_08216766
gUnknown_08216766:
    .string "Im Kampf benutzt.{END}"

    .global gUnknown_08216778
gUnknown_08216778:
    .string "Utilisé au combat.{END}"

    .global gUnknown_0821678B
gUnknown_0821678B:
    .string "AP{END}"

    .global gUnknown_0821678E
gUnknown_0821678E:
    .string "AP{END}"

    .global gUnknown_08216791
gUnknown_08216791:
    .string "PC{END}"

    .global gUnknown_08216794
gUnknown_08216794:
    .string "/{END}"

    .global gUnknown_08216796
gUnknown_08216796:
    .string "Spells are not available.{END}"

    .global gUnknown_082167B0
gUnknown_082167B0:
    .string "Sorts indisponibles.{END}"

    .global gUnknown_082167C5
gUnknown_082167C5:
    .string "Zauber nicht verfügbar. {END}"

