    .global gUnknown_08185398
gUnknown_08185398:
    .string "BREATH OF FIRE{END}"

    .global gUnknown_081853A7
gUnknown_081853A7:
    .string "PRODUCED STAFF{END}"

    .global gUnknown_081853B6
gUnknown_081853B6:
    .string "PLANNER{END}"

    .global gUnknown_081853BE
gUnknown_081853BE:
    .string "Bamboo{END}"

    .global gUnknown_081853C5
gUnknown_081853C5:
    .string "Botunori{END}"

    .global gUnknown_081853CE
gUnknown_081853CE:
    .string "Pukchi{END}"

    .global gUnknown_081853D5
gUnknown_081853D5:
    .string "Makoto{END}"

    .global gUnknown_081853DC
gUnknown_081853DC:
    .string "SCROLL STAFF{END}"

    .global gUnknown_081853E9
gUnknown_081853E9:
    .string "Don{END}"

    .global gUnknown_081853ED
gUnknown_081853ED:
    .string "Banndy{END}"

    .global gUnknown_081853F4
gUnknown_081853F4:
    .string "Scr. Spirit{END}"

    .global gUnknown_08185400
gUnknown_08185400:
    .string "U-King{END}"

    .global gUnknown_08185407
gUnknown_08185407:
    .string "Tuck-K{END}"

    .global gUnknown_0818540E
gUnknown_0818540E:
    .string "OBJECT STAFF{END}"

    .global gUnknown_0818541B
gUnknown_0818541B:
    .string "Inuffkin{END}"

    .global gUnknown_08185424
gUnknown_08185424:
    .string "Fishman{END}"

    .global gUnknown_0818542C
gUnknown_0818542C:
    .string "Simiz{END}"

    .global gUnknown_08185432
gUnknown_08185432:
    .string "Zura-Zura{END}"

    .global gUnknown_0818543C
gUnknown_0818543C:
    .string "Mats{END}"

    .global gUnknown_08185441
gUnknown_08185441:
    .string "MUSIC COMPOSER{END}"

    .global gUnknown_08185450
gUnknown_08185450:
    .string "Bun-Bun{END}"

    .global gUnknown_08185458
gUnknown_08185458:
    .string "Mari{END}"

    .global gUnknown_0818545D
gUnknown_0818545D:
    .string "O-Jaring{END}"

    .global gUnknown_08185466
gUnknown_08185466:
    .string "Pii♪{END}"

    .global gUnknown_0818546B
gUnknown_0818546B:
    .string "SOUND EFFECTS{END}"

    .global gUnknown_08185479
gUnknown_08185479:
    .string "Any{END}"

    .global gUnknown_0818547D
gUnknown_0818547D:
    .string "Elf{END}"

    .global gUnknown_08185481
gUnknown_08185481:
    .string "SOUND PROGRAMMER{END}"

    .global gUnknown_08185492
gUnknown_08185492:
    .string "Oyabun{END}"

    .global gUnknown_08185499
gUnknown_08185499:
    .string "Ikebon{END}"

    .global gUnknown_081854A0
gUnknown_081854A0:
    .string "GAME PROGRAMMER{END}"

    .global gUnknown_081854B0
gUnknown_081854B0:
    .string "Kanecon{END}"

    .global gUnknown_081854B8
gUnknown_081854B8:
    .string "Noriko{END}"

    .global gUnknown_081854BF
gUnknown_081854BF:
    .string "Sun Chan{END}"

    .global gUnknown_081854C8
gUnknown_081854C8:
    .string "Sleeper{END}"

    .global gUnknown_081854D0
gUnknown_081854D0:
    .string "Shu{END}"

    .global gUnknown_081854D4
gUnknown_081854D4:
    .string "SPECIAL THANKS{END}"

    .global gUnknown_081854E3
gUnknown_081854E3:
    .string "Bone{END}"

    .global gUnknown_081854E8
gUnknown_081854E8:
    .string "QUETZAL{END}"

    .global gUnknown_081854F0
gUnknown_081854F0:
    .string "Kazuki{END}"

    .global gUnknown_081854F7
gUnknown_081854F7:
    .string "No.19{END}"

    .global gUnknown_081854FD
gUnknown_081854FD:
    .string "Tatuya{END}"

    .global gUnknown_08185504
gUnknown_08185504:
    .string "カプコンしゃいんのみなさん{END}"

    .global gUnknown_08185512
gUnknown_08185512:
    .string "おつかれさまでした{END}"

    .global gUnknown_0818551C
gUnknown_0818551C:
    .string "ALL CAPCOM STAFF{END}"

    .global gUnknown_0818552D
gUnknown_0818552D:
    .string "    FIGHTERS{END}"

    .global gUnknown_0818553A
gUnknown_0818553A:
    .string "and...{END}"

    .global gUnknown_08185541
gUnknown_08185541:
    .string "   You{END}"

    .global gUnknown_08185548
gUnknown_08185548:
    .string "Thanks for playing!{END}"

    .global gUnknown_0818555C
gUnknown_0818555C:
    .string "...and{END}"
