    .global gUnknown_0820C925
gUnknown_0820C925:
    .string "Fwd{END}"

    .global gUnknown_0820C929
gUnknown_0820C929:
    .string "Bck{END}"

    .global gUnknown_0820C92D
gUnknown_0820C92D:
    .string "End{END}"

    .global gUnknown_0820C931
gUnknown_0820C931:
    .string "Vwts{END}"

    .global gUnknown_0820C936
gUnknown_0820C936:
    .string "Zrck{END}"

    .global gUnknown_0820C93B
gUnknown_0820C93B:
    .string "Ende{END}"

    .global gUnknown_0820C940
gUnknown_0820C940:
    .string "Av{END}"

    .global gUnknown_0820C943
gUnknown_0820C943:
    .string "Rtr{END}"

    .global gUnknown_0820C947
gUnknown_0820C947:
    .string "Fin{END}"
