    .global gUnknown_0820B3DE
gUnknown_0820B3DE:
    .string "OK to discard?       Yes No{END}"

    .global gUnknown_0820B3FA
gUnknown_0820B3FA:
    .string "Use whose spell?{END}"

    .global gUnknown_0820B40B
gUnknown_0820B40B:
    .string "Use on whom?{END}"

    .global gUnknown_0820B418
gUnknown_0820B418:
    .string "Change whose equipment?{END}"

    .global gUnknown_0820B430
gUnknown_0820B430:
    .string "View whose status?{END}"

    .global gUnknown_0820B443
gUnknown_0820B443:
    .string "Sort items?          Yes No{END}"

    .global gUnknown_0820B45F
gUnknown_0820B45F:
    .string "Select an item to switch.{END}"

    .global gUnknown_0820B479
gUnknown_0820B479:
    .string "With which item?{END}"

    .global gUnknown_0820B48A
gUnknown_0820B48A:
    .string "USE{END}"

    .global gUnknown_0820B48E
gUnknown_0820B48E:
    .string "DSCD{END}"

    .global gUnknown_0820B493
gUnknown_0820B493:
    .string "CHNG{END}"

    .global gUnknown_0820B498
gUnknown_0820B498:
    .string "SORT{END}"

    .global gUnknown_0820B49D
gUnknown_0820B49D:
    .string "Use an item.{END}"

    .global gUnknown_0820B4AA
gUnknown_0820B4AA:
    .string "Discard an item.{END}"

    .global gUnknown_0820B4BB
gUnknown_0820B4BB:
    .string "Switch items.{END}"

    .global gUnknown_0820B4C9
gUnknown_0820B4C9:
    .string "Sort items.{END}"

    .global gUnknown_0820B4D5
gUnknown_0820B4D5:
    .string "View vital items.{END}"

    .global gUnknown_0820B4E7
gUnknown_0820B4E7:
    .string "ITEM{END}"

    .global gUnknown_0820B4EC
gUnknown_0820B4EC:
    .string "SPEL{END}"

    .global gUnknown_0820B4F1
gUnknown_0820B4F1:
    .string "EQIP{END}"

    .global gUnknown_0820B4F6
gUnknown_0820B4F6:
    .string "SWCH{END}"

    .global gUnknown_0820B4FB
gUnknown_0820B4FB:
    .string "CHNG{END}"

    .global gUnknown_0820B500
gUnknown_0820B500:
    .string "END{END}"

    .global gUnknown_0820B504
gUnknown_0820B504:
    .string "Change which character?{END}"

    .global gUnknown_0820B51C
gUnknown_0820B51C:
    .string "With which character?{END}"

    .global gUnknown_0820B532
gUnknown_0820B532:
    .string "Dig{END}"

    .global gUnknown_0820B536
gUnknown_0820B536:
    .string "Select an item to discard.{END}"

    .global gUnknown_0820B551
gUnknown_0820B551:
    .string "NONE{END}"

    .global gUnknown_0820B556
gUnknown_0820B556:
    .string "REMOVE{END}"

    .global gUnknown_0820B55D
gUnknown_0820B55D:
    .string "       "

    .global gUnknown_0820B564
gUnknown_0820B564:
    .string "  "

    .global gUnknown_0820B566
gUnknown_0820B566:
    .string "  "

    .global gUnknown_0820B568
gUnknown_0820B568:
    .string " "

    .global gUnknown_0820B569
gUnknown_0820B569:
    .string "   {END}"

    .global gUnknown_0820B56D
gUnknown_0820B56D:
    .string "AP{END}"

    .global gUnknown_0820B570
gUnknown_0820B570:
    .string "/{END}"

    .global gUnknown_0820B572
gUnknown_0820B572:
    .string "AP{END}"

    .global gUnknown_0820B575
gUnknown_0820B575:
    .string "Switch whose line?{END}"

    .global gUnknown_0820B588
gUnknown_0820B588:
    .string "Quick Save the game?{END}"

    .global gUnknown_0820B59D
gUnknown_0820B59D:
    .string "{END}"

    .global gUnknown_0820B59E
gUnknown_0820B59E:
    .string "WARNING: OK to overwrite{END}"

    .global gUnknown_0820B5B7
gUnknown_0820B5B7:
    .string "the existing data{END}"

    .global gUnknown_0820B5C9
gUnknown_0820B5C9:
    .string "?{END}"

    .global gUnknown_0820B5CB
gUnknown_0820B5CB:
    .string "Quick Save successfully{END}"

    .global gUnknown_0820B5E3
gUnknown_0820B5E3:
    .string "completed.{END}"

    .global gUnknown_0820B5EE
gUnknown_0820B5EE:
    .string "Yes{END}"

    .global gUnknown_0820B5F2
gUnknown_0820B5F2:
    .string " No{END}"

    .global gUnknown_0820B5F6
gUnknown_0820B5F6:
    .string "Push A Button for details.{END}"

    .global gUnknown_0820B611
gUnknown_0820B611:
    .string "Which item?{END}"

    .global gUnknown_0820B61D
gUnknown_0820B61D:
    .string "ERROR!: SAVE FAILED.{END}"

    .global gUnknown_0820B632
gUnknown_0820B632:
    .string "AP{END}"

    .global gUnknown_0820B635
gUnknown_0820B635:
    .string "/{END}"

    .global gUnknown_0820B637
gUnknown_0820B637:
    .string "AP{END}"

    .global gUnknown_0820B63A
gUnknown_0820B63A:
    .string "Verwerfen OK?         Ja Nein{END}"

    .global gUnknown_0820B658
gUnknown_0820B658:
    .string "Wessen Zauber benutzen?{END}"

    .global gUnknown_0820B670
gUnknown_0820B670:
    .string "Wer soll benutzen?{END}"

    .global gUnknown_0820B683
gUnknown_0820B683:
    .string "Wessen Ausrüstung ändern?{END}"

    .global gUnknown_0820B69D
gUnknown_0820B69D:
    .string "Wessen Status anzeigen?{END}"

    .global gUnknown_0820B6B5
gUnknown_0820B6B5:
    .string "Objekte sortieren?    Ja Nein{END}"

    .global gUnknown_0820B6D3
gUnknown_0820B6D3:
    .string "Zu tauschendes Objekt:.{END}"

    .global gUnknown_0820B6EB
gUnknown_0820B6EB:
    .string "Mit welchem Objekt?{END}"

    .global gUnknown_0820B6FF
gUnknown_0820B6FF:
    .string "BNTZ{END}"

    .global gUnknown_0820B704
gUnknown_0820B704:
    .string "WEGW{END}"

    .global gUnknown_0820B709
gUnknown_0820B709:
    .string "TSCH{END}"

    .global gUnknown_0820B70E
gUnknown_0820B70E:
    .string "SORT{END}"

    .global gUnknown_0820B713
gUnknown_0820B713:
    .string "Ein Objekt benutzen.{END}"

    .global gUnknown_0820B728
gUnknown_0820B728:
    .string "Ein Objekt wegwerfen.{END}"

    .global gUnknown_0820B73E
gUnknown_0820B73E:
    .string "Objekte tauschen.{END}"

    .global gUnknown_0820B750
gUnknown_0820B750:
    .string "Objekte sortieren.{END}"

    .global gUnknown_0820B763
gUnknown_0820B763:
    .string "Wichtige Objekte zeigen.{END}"

    .global gUnknown_0820B77C
gUnknown_0820B77C:
    .string "OBJ{END}"

    .global gUnknown_0820B780
gUnknown_0820B780:
    .string "ZAUB{END}"

    .global gUnknown_0820B785
gUnknown_0820B785:
    .string "AUSR{END}"

    .global gUnknown_0820B78A
gUnknown_0820B78A:
    .string "TSCH{END}"

    .global gUnknown_0820B78F
gUnknown_0820B78F:
    .string "POS{END}"

    .global gUnknown_0820B793
gUnknown_0820B793:
    .string "ENDE{END}"

    .global gUnknown_0820B798
gUnknown_0820B798:
    .string "Wessen Position ändern?{END}"

    .global gUnknown_0820B7B0
gUnknown_0820B7B0:
    .string "Tauschen mit?{END}"

    .global gUnknown_0820B7BE
gUnknown_0820B7BE:
    .string "Graben{END}"

    .global gUnknown_0820B7C5
gUnknown_0820B7C5:
    .string "Zu verwerfendes Objekt:.{END}"

    .global gUnknown_0820B7DE
gUnknown_0820B7DE:
    .string "KEINS{END}"

    .global gUnknown_0820B7E4
gUnknown_0820B7E4:
    .string "ENTF{END}"

    .global gUnknown_0820B7E9
gUnknown_0820B7E9:
    .string "Wessen Reihe?{END}"

    .global gUnknown_0820B7F7
gUnknown_0820B7F7:
    .string "Spiel schnellspeichern?{END}"

    .global gUnknown_0820B80F
gUnknown_0820B80F:
    .string "{END}"

    .global gUnknown_0820B810
gUnknown_0820B810:
    .string "WARNUNG: OK um existierende{END}"

    .global gUnknown_0820B82C
gUnknown_0820B82C:
    .string "Daten zu überschreiben{END}"

    .global gUnknown_0820B843
gUnknown_0820B843:
    .string "?{END}"

    .global gUnknown_0820B845
gUnknown_0820B845:
    .string "Speichern erfolgreich{END}"

    .global gUnknown_0820B85B
gUnknown_0820B85B:
    .string "beendet{END}"

    .global gUnknown_0820B863
gUnknown_0820B863:
    .string "Ja.{END}"

    .global gUnknown_0820B867
gUnknown_0820B867:
    .string "Nein{END}"

    .global gUnknown_0820B86C
gUnknown_0820B86C:
    .string "A-Knopf für Details.{END}"

    .global gUnknown_0820B881
gUnknown_0820B881:
    .string "Welches Objekt?{END}"

    .global gUnknown_0820B891
gUnknown_0820B891:
    .string "PA{END}"

    .global gUnknown_0820B894
gUnknown_0820B894:
    .string "/{END}"

    .global gUnknown_0820B896
gUnknown_0820B896:
    .string "PA{END}"

    .global gUnknown_0820B899
gUnknown_0820B899:
    .string "S'en débarrasser ?   Oui Non{END}"

    .global gUnknown_0820B8B6
gUnknown_0820B8B6:
    .string "Quel personnage ?{END}"

    .global gUnknown_0820B8C8
gUnknown_0820B8C8:
    .string "Sur quel personnage ?{END}"

    .global gUnknown_0820B8DE
gUnknown_0820B8DE:
    .string "Changer quel équipement ?{END}"

    .global gUnknown_0820B8F8
gUnknown_0820B8F8:
    .string "Quel personnage ?{END}"

    .global gUnknown_0820B90A
gUnknown_0820B90A:
    .string "Ranger objets ?      Oui Non{END}"

    .global gUnknown_0820B927
gUnknown_0820B927:
    .string "Echanger quel objet ?{END}"

    .global gUnknown_0820B93D
gUnknown_0820B93D:
    .string "Avec quel objet ?{END}"

    .global gUnknown_0820B94F
gUnknown_0820B94F:
    .string "UTIL{END}"

    .global gUnknown_0820B954
gUnknown_0820B954:
    .string "POUB{END}"

    .global gUnknown_0820B959
gUnknown_0820B959:
    .string "CHNG{END}"

    .global gUnknown_0820B95E
gUnknown_0820B95E:
    .string "RANG{END}"

    .global gUnknown_0820B963
gUnknown_0820B963:
    .string "Utiliser un objet.{END}"

    .global gUnknown_0820B976
gUnknown_0820B976:
    .string "Se débarrasser d'un objet.{END}"

    .global gUnknown_0820B991
gUnknown_0820B991:
    .string "Echanger un objet{END}"

    .global gUnknown_0820B9A3
gUnknown_0820B9A3:
    .string "Ranger les objets.{END}"

    .global gUnknown_0820B9B6
gUnknown_0820B9B6:
    .string "Voir les objets vitaux.{END}"

    .global gUnknown_0820B9CE
gUnknown_0820B9CE:
    .string "OBJ{END}"

    .global gUnknown_0820B9D2
gUnknown_0820B9D2:
    .string "SORT{END}"

    .global gUnknown_0820B9D7
gUnknown_0820B9D7:
    .string "EQIP{END}"

    .global gUnknown_0820B9DC
gUnknown_0820B9DC:
    .string "POS{END}"

    .global gUnknown_0820B9E0
gUnknown_0820B9E0:
    .string "CHNG{END}"

    .global gUnknown_0820B9E5
gUnknown_0820B9E5:
    .string "FIN{END}"

    .global gUnknown_0820B9E9
gUnknown_0820B9E9:
    .string "Changer quel personnage ?{END}"

    .global gUnknown_0820BA03
gUnknown_0820BA03:
    .string "Avec quel personnage ?{END}"

    .global gUnknown_0820BA1A
gUnknown_0820BA1A:
    .string "Creuser{END}"

    .global gUnknown_0820BA22
gUnknown_0820BA22:
    .string "Jeter quel objet ?{END}"

    .global gUnknown_0820BA35
gUnknown_0820BA35:
    .string "AUCUN{END}"

    .global gUnknown_0820BA3B
gUnknown_0820BA3B:
    .string "OTER{END}"

    .global gUnknown_0820BA40
gUnknown_0820BA40:
    .string "Echanger quelle position ?{END}"

    .global gUnknown_0820BA5B
gUnknown_0820BA5B:
    .string "Faire une sauvegarde{END}"

    .global gUnknown_0820BA70
gUnknown_0820BA70:
    .string "rapide ?{END}"

    .global gUnknown_0820BA79
gUnknown_0820BA79:
    .string "AVERTISSEMENT : OK pour{END}"

    .global gUnknown_0820BA91
gUnknown_0820BA91:
    .string "écrasement des données {END}"

    .global gUnknown_0820BAA9
gUnknown_0820BAA9:
    .string "existantes ?{END}"

    .global gUnknown_0820BAB6
gUnknown_0820BAB6:
    .string "Sauvegarde rapide{END}"

    .global gUnknown_0820BAC8
gUnknown_0820BAC8:
    .string "réussie.{END}"

    .global gUnknown_0820BAD1
gUnknown_0820BAD1:
    .string "Oui{END}"

    .global gUnknown_0820BAD5
gUnknown_0820BAD5:
    .string "Non{END}"

    .global gUnknown_0820BAD9
gUnknown_0820BAD9:
    .string "Bouton A pour plus d'infos{END}"

    .global gUnknown_0820BAF4
gUnknown_0820BAF4:
    .string "Quel objet ?{END}"

    .global gUnknown_0820BB01
gUnknown_0820BB01:
    .string "{0x8A}Einhändig{END}"

    .global gUnknown_0820BB0C
gUnknown_0820BB0C:
    .string "{0x8A}Zweihändig{END}"

    .global gUnknown_0820BB18
gUnknown_0820BB18:
    .string "{0x83}ETC{END}"

    .global gUnknown_0820BB1D
gUnknown_0820BB1D:
    .string "{0x83}HLM{END}"

    .global gUnknown_0820BB22
gUnknown_0820BB22:
    .string "{0x83}RST{END}"

    .global gUnknown_0820BB27
gUnknown_0820BB27:
    .string "{0x83}SCH{END}"

    .global gUnknown_0820BB2C
gUnknown_0820BB2C:
    .string "{0x83}WAF{END}"

    .global gUnknown_0820BB31
gUnknown_0820BB31:
    .string "FEHLER!: SPEICHERFEHLER.{END}"

    .global gUnknown_0820BB4A
gUnknown_0820BB4A:
    .string "{0x8A}Une main{END}"

    .global gUnknown_0820BB54
gUnknown_0820BB54:
    .string "{0x8A}Deux mains{END}"

    .global gUnknown_0820BB60
gUnknown_0820BB60:
    .string "{0x83}ETC{END}"

    .global gUnknown_0820BB65
gUnknown_0820BB65:
    .string "{0x83}CAS{END}"

    .global gUnknown_0820BB6A
gUnknown_0820BB6A:
    .string "{0x83}HAB{END}"

    .global gUnknown_0820BB6F
gUnknown_0820BB6F:
    .string "{0x83}BOU{END}"

    .global gUnknown_0820BB74
gUnknown_0820BB74:
    .string "{0x83}ARM{END}"

    .global gUnknown_0820BB79
gUnknown_0820BB79:
    .string "ERREUR : ECHEC DE SAUVEGARDE !.{END}"

    .global gUnknown_0820BB99
gUnknown_0820BB99:
    .string "{0x8A}One handed{END}"

    .global gUnknown_0820BBA5
gUnknown_0820BBA5:
    .string "{0x8A}Two handed{END}"

    .global gUnknown_0820BBB1
gUnknown_0820BBB1:
    .string "{0x83}ETC{END}"

    .global gUnknown_0820BBB6
gUnknown_0820BBB6:
    .string "{0x83}HLM{END}"

    .global gUnknown_0820BBBB
gUnknown_0820BBBB:
    .string "{0x83}ARM{END}"

    .global gUnknown_0820BBC0
gUnknown_0820BBC0:
    .string "{0x83}SHD{END}"

    .global gUnknown_0820BBC5
gUnknown_0820BBC5:
    .string "{0x83}WPN{END}"

    .global gUnknown_0820BBCA
gUnknown_0820BBCA:
    .string "{END}"

    .global gUnknown_0820BBCB
gUnknown_0820BBCB:
    .string "{END}"

