    .global gUnknown_08188380
gUnknown_08188380:
    .string "Empty{END}"

    .global gUnknown_08188386
gUnknown_08188386:
    .string "No equip{END}"

    .global gUnknown_0818838F
gUnknown_0818838F:
    .string "No item to trade in.{END}"

    .global gUnknown_081883A4
gUnknown_081883A4:
    .string "I buy {END}"

    .global gUnknown_081883AB
gUnknown_081883AB:
    .string " for {END}"

    .global gUnknown_081883B1
gUnknown_081883B1:
    .string "GP.{END}"

    .global gUnknown_081883B5
gUnknown_081883B5:
    .string "I can't trade it in.{END}"

    .global gUnknown_081883CA
gUnknown_081883CA:
    .string "We don't trade in {END}"

    .global gUnknown_081883DD
gUnknown_081883DD:
    .string ".{END}"

    .global gUnknown_081883DF
gUnknown_081883DF:
    .string "No item space available.{END}"

    .global gUnknown_081883F8
gUnknown_081883F8:
    .string "Item  Coin{END}"

    .global gUnknown_08188403
gUnknown_08188403:
    .string "Dpst  Draw{END}"

    .global gUnknown_0818840E
gUnknown_0818840E:
    .string "Cash:{END}"

    .global gUnknown_08188414
gUnknown_08188414:
    .string "In Bank:{END}"

    .global gUnknown_0818841D
gUnknown_0818841D:
    .string "Deposit:{END}"

    .global gUnknown_08188426
gUnknown_08188426:
    .string "Withdraw:{END}"

    .global gUnknown_08188430
gUnknown_08188430:
    .string "Whose name will you change?{END}"

    .global gUnknown_0818844C
gUnknown_0818844C:
    .string "You can't sell this.{END}"

    .global gUnknown_08188461
gUnknown_08188461:
    .string "OK to trade in?       Yes No{END}"

    .global gUnknown_0818847E
gUnknown_0818847E:
    .string "How many?{END}"

    .global gUnknown_08188488
gUnknown_08188488:
    .string "OK to sell?          Yes No{END}"

    .global gUnknown_081884A4
gUnknown_081884A4:
    .string "Use D-pad to change.{END}"

    .global gUnknown_081884B9
gUnknown_081884B9:
    .string "Money overflows. OK?  Yes No{END}"

    .global gUnknown_081884D6
gUnknown_081884D6:
    .string "Buy{END}"

    .global gUnknown_081884DA
gUnknown_081884DA:
    .string "Sell{END}"

    .global gUnknown_081884DF
gUnknown_081884DF:
    .string "Exit{END}"

    .global gUnknown_081884E4
gUnknown_081884E4:
    .string "Trde{END}"

    .global gUnknown_081884E9
gUnknown_081884E9:
    .string "What will you do?{END}"

    .global gUnknown_081884FB
gUnknown_081884FB:
    .string "Not enough money.{END}"

    .global gUnknown_0818850D
gUnknown_0818850D:
    .string "You can't carry any more.{END}"

    .global gUnknown_08188527
gUnknown_08188527:
    .string "You can't sell it.{END}"

    .global gUnknown_0818853A
gUnknown_0818853A:
    .string "N/A for your party members.{END}"

    .global gUnknown_08188556
gUnknown_08188556:
    .string "How much will you withdraw?{END}"

    .global gUnknown_08188572
gUnknown_08188572:
    .string "How much will you deposit?{END}"

    .global gUnknown_0818858D
gUnknown_0818858D:
    .string "Libre{END}"

    .global gUnknown_08188593
gUnknown_08188593:
    .string "Néant{END}"

    .global gUnknown_08188599
gUnknown_08188599:
    .string "Pas d'objet à échanger.{END}"

    .global gUnknown_081885B1
gUnknown_081885B1:
    .string "J'achète {END}"

    .global gUnknown_081885BB
gUnknown_081885BB:
    .string " pour {END}"

    .global gUnknown_081885C2
gUnknown_081885C2:
    .string "PO.{END}"

    .global gUnknown_081885C6
gUnknown_081885C6:
    .string "Je ne peux échanger.{END}"

    .global gUnknown_081885DB
gUnknown_081885DB:
    .string "Nous n'échangeons pas {END}"

    .global gUnknown_081885F2
gUnknown_081885F2:
    .string "Pas d'espace.{END}"

    .global gUnknown_08188600
gUnknown_08188600:
    .string "Obj.  PO{END}"

    .global gUnknown_08188609
gUnknown_08188609:
    .string "Dépô  Retr{END}"

    .global gUnknown_08188614
gUnknown_08188614:
    .string "Argent :{END}"

    .global gUnknown_0818861D
gUnknown_0818861D:
    .string "A la banque{END}"

    .global gUnknown_08188629
gUnknown_08188629:
    .string "Dépôt :{END}"

    .global gUnknown_08188631
gUnknown_08188631:
    .string "Retrait :{END}"

    .global gUnknown_0818863B
gUnknown_0818863B:
    .string "Changer quel nom ?{END}"

    .global gUnknown_0818864E
gUnknown_0818864E:
    .string "Impossible à vendre{END}"

    .global gUnknown_08188662
gUnknown_08188662:
    .string "OK pour échange ?    Oui Non{END}"

    .global gUnknown_0818867F
gUnknown_0818867F:
    .string "Combien ?{END}"

    .global gUnknown_08188689
gUnknown_08188689:
    .string "OK pour vente ?      Oui Non{END}"

    .global gUnknown_081886A6
gUnknown_081886A6:
    .string "Changer au Pavé Multi{END}"

    .global gUnknown_081886BC
gUnknown_081886BC:
    .string "OK pour dépassement d'argent ?  Oui Non{END}"

    .global gUnknown_081886E4
gUnknown_081886E4:
    .string "Ach.{END}"

    .global gUnknown_081886E9
gUnknown_081886E9:
    .string "Ven.{END}"

    .global gUnknown_081886EE
gUnknown_081886EE:
    .string "Fin{END}"

    .global gUnknown_081886F2
gUnknown_081886F2:
    .string "Troc{END}"

    .global gUnknown_081886F7
gUnknown_081886F7:
    .string "Que voulez-vous faire ?{END}"

    .global gUnknown_0818870F
gUnknown_0818870F:
    .string "Pas assez d'argent.{END}"

    .global gUnknown_08188723
gUnknown_08188723:
    .string "Impossible de porter plus{END}"

    .global gUnknown_0818873D
gUnknown_0818873D:
    .string "Vous ne pouvez pas vendre ceci{END}"

    .global gUnknown_0818875C
gUnknown_0818875C:
    .string "Ne s'applique pas aux membres du groupe.{END}"

    .global gUnknown_08188785
gUnknown_08188785:
    .string "Combien voulez-vous retirer ?{END}"

    .global gUnknown_081887A3
gUnknown_081887A3:
    .string "Combien voulez-vous déposer ?{END}"

    .global gUnknown_081887C1
gUnknown_081887C1:
    .string "Leer{END}"

    .global gUnknown_081887C6
gUnknown_081887C6:
    .string "K.Ausr.{END}"

    .global gUnknown_081887CE
gUnknown_081887CE:
    .string "Kein Tauschobj. in.{END}"

    .global gUnknown_081887E2
gUnknown_081887E2:
    .string "Kaufe {END}"

    .global gUnknown_081887E9
gUnknown_081887E9:
    .string " für {END}"

    .global gUnknown_081887EF
gUnknown_081887EF:
    .string "G.{END}"

    .global gUnknown_081887F2
gUnknown_081887F2:
    .string "Ich tausche nicht:{END}"

    .global gUnknown_08188805
gUnknown_08188805:
    .string "Wir handeln nicht in: {END}"

    .global gUnknown_0818881C
gUnknown_0818881C:
    .string "Kein Platz für Objekt.{END}"

    .global gUnknown_08188833
gUnknown_08188833:
    .string "Obj   Münz{END}"

    .global gUnknown_0818883E
gUnknown_0818883E:
    .string "Einl  Abh{END}"

    .global gUnknown_08188848
gUnknown_08188848:
    .string "Bar:{END}"

    .global gUnknown_0818884D
gUnknown_0818884D:
    .string "In Bank:{END}"

    .global gUnknown_08188856
gUnknown_08188856:
    .string "Einz.:{END}"

    .global gUnknown_0818885D
gUnknown_0818885D:
    .string "Abh.:{END}"

    .global gUnknown_08188863
gUnknown_08188863:
    .string "Wessen Namen ändern?{END}"

    .global gUnknown_08188878
gUnknown_08188878:
    .string "Nicht verkäuflich.{END}"

    .global gUnknown_0818888B
gUnknown_0818888B:
    .string "Handeln OK?          Ja Nein{END}"

    .global gUnknown_081888A8
gUnknown_081888A8:
    .string "Wie viel{END}"

    .global gUnknown_081888B1
gUnknown_081888B1:
    .string "Verkauf OK?          Ja Nein{END}"

    .global gUnknown_081888CE
gUnknown_081888CE:
    .string "StKrz zum Ändern.{END}"

    .global gUnknown_081888E0
gUnknown_081888E0:
    .string "Geldüberlauf OK?  Ja  Nein{END}"

    .global gUnknown_081888FB
gUnknown_081888FB:
    .string "Kauf{END}"

    .global gUnknown_08188900
gUnknown_08188900:
    .string "Verk{END}"

    .global gUnknown_08188905
gUnknown_08188905:
    .string "Ende{END}"

    .global gUnknown_0818890A
gUnknown_0818890A:
    .string "Hndl{END}"

    .global gUnknown_0818890F
gUnknown_0818890F:
    .string "Was möchtest du tun?{END}"

    .global gUnknown_08188924
gUnknown_08188924:
    .string "Nicht genug Geld.{END}"

    .global gUnknown_08188936
gUnknown_08188936:
    .string "Kann nicht mehr tragen{END}"

    .global gUnknown_0818894D
gUnknown_0818894D:
    .string "Nicht verkaufbar{END}"

    .global gUnknown_0818895E
gUnknown_0818895E:
    .string "NV für Gruppenmitglieder.{END}"

    .global gUnknown_08188978
gUnknown_08188978:
    .string "Wie viel abholen?{END}"

    .global gUnknown_0818898A
gUnknown_0818898A:
    .string "Wie viel einlegen?{END}"

    .global gUnknown_0818899D
gUnknown_0818899D:
    .string "G{END}"

    .global gUnknown_0818899F
gUnknown_0818899F:
    .string "PO{END}"

    .global gUnknown_081889A2
gUnknown_081889A2:
    .string "G{END}"

    .global gUnknown_081889A4
gUnknown_081889A4:
    .string "{END}"

    .global gUnknown_081889A5
gUnknown_081889A5:
    .byte 1

    .global gUnknown_081889A6
gUnknown_081889A6:
    .string "{END}"
