    .global gUnknown_08218AF8
gUnknown_08218AF8:
    .string "{0x13}{0x01} grinned fearlessly."

    .global gUnknown_08218B0E
gUnknown_08218B0E:
    .string "{0x11}{0x01} sourit sans peur."

    .global gUnknown_08218B22
gUnknown_08218B22:
    .string "{0x11}{0x01} grinst furchtlos."

    .global gUnknown_08218B36
gUnknown_08218B36:
    .string "{CODE7 0x01} got up."

    .global gUnknown_08218B40
gUnknown_08218B40:
    .string "{ITEM 0x01} est debout."

    .global gUnknown_08218B4E
gUnknown_08218B4E:
    .string "{0x11}{0x01} steht wieder auf."

    .global gUnknown_08218B62
gUnknown_08218B62:
    .string "{0x0E}{0x01} seems alright."

    .global gUnknown_08218B73
gUnknown_08218B73:
    .string "{0x11}{0x01} a l'air en forme."

    .global gUnknown_08218B87
gUnknown_08218B87:
    .string "{ITEM 0x01} scheint OK."

    .global gUnknown_08218B95
gUnknown_08218B95:
    .string "{DEFENSE 0x01} began crying."

    .global gUnknown_08218BA5
gUnknown_08218BA5:
    .string "{CODE7 0x01} pleure."

    .global gUnknown_08218BAF
gUnknown_08218BAF:
    .string "{STRING 0x01} heult auf."

    .global gUnknown_08218BBC
gUnknown_08218BBC:
    .string "{CODE8 0x01} got mad!"

    .global gUnknown_08218BC7
gUnknown_08218BC7:
    .string "{0x0E}{0x01} est en colère!"

    .global gUnknown_08218BD8
gUnknown_08218BD8:
    .string "{WEAPON 0x01} dreht durch!"

    .global gUnknown_08218BE7
gUnknown_08218BE7:
    .string "{DEFENSE 0x01} is intrigued."

    .global gUnknown_08218BF7
gUnknown_08218BF7:
    .string "{DEFENSE 0x01} est intrigué."

    .global gUnknown_08218C07
gUnknown_08218C07:
    .string "{0x12}{0x01} ist unbeeindruckt."

    .global gUnknown_08218C1C
gUnknown_08218C1C:
    .string "{CODE8 0x37}o effect"

    .global gUnknown_08218C26
gUnknown_08218C26:
    .string "{STRING 0x2A}ucun effet"

    .global gUnknown_08218C32
gUnknown_08218C32:
    .string "{STRING 0x34}ein Effekt"

    .global gUnknown_08218C3E
gUnknown_08218C3E:
    .string "{CODE7 0x2A}rrrrgh!"

    .global gUnknown_08218C47
gUnknown_08218C47:
    .string "{CODE8 0x2A}aaaaaah!"

    .global gUnknown_08218C51
gUnknown_08218C51:
    .string "{CODE7 0x2A}rrrrgh!{END}"

    @Unreferenced string
    .global gUnknown_08218C5B
gUnknown_08218C5B:
    .string "{END}"

    .align 2
    .global gUnknown_08218C5C
gUnknown_08218C5C:
    .word gUnknown_08218AF8 @ 0 / 0x0
    .word gUnknown_08218B36 @ 1 / 0x1
    .word gUnknown_08218B62 @ 2 / 0x2
    .word gUnknown_08218B95 @ 3 / 0x3
    .word gUnknown_08218BBC @ 4 / 0x4
    .word gUnknown_08218BE7 @ 5 / 0x5
    .word gUnknown_08218C1C @ 6 / 0x6
    .word gUnknown_08218C3E @ 7 / 0x7
    
    .align 2
    .global gUnknown_08218C7C
gUnknown_08218C7C:
    .word gUnknown_08218B0E @ 0 / 0x0
    .word gUnknown_08218B40 @ 1 / 0x1
    .word gUnknown_08218B73 @ 2 / 0x2
    .word gUnknown_08218BA5 @ 3 / 0x3
    .word gUnknown_08218BC7 @ 4 / 0x4
    .word gUnknown_08218BF7 @ 5 / 0x5
    .word gUnknown_08218C26 @ 6 / 0x6
    .word gUnknown_08218C47 @ 7 / 0x7
    
    .align 2
    .global gUnknown_08218C9C
gUnknown_08218C9C:
    .word gUnknown_08218B22 @ 0 / 0x0
    .word gUnknown_08218B4E @ 1 / 0x1
    .word gUnknown_08218B87 @ 2 / 0x2
    .word gUnknown_08218BAF @ 3 / 0x3
    .word gUnknown_08218BD8 @ 4 / 0x4
    .word gUnknown_08218C07 @ 5 / 0x5
    .word gUnknown_08218C32 @ 6 / 0x6
    .word gUnknown_08218C51 @ 7 / 0x7
