    .global gUnknown_08215C98
gUnknown_08215C98:
    .string "/{END}"

    .global gUnknown_08215C9A
gUnknown_08215C9A:
    .string "ATTACK{END}"

    .global gUnknown_08215CA1
gUnknown_08215CA1:
    .string "DEFENSE{END}"

    .global gUnknown_08215CA9
gUnknown_08215CA9:
    .string "ACTIVE{END}"

    .global gUnknown_08215CB0
gUnknown_08215CB0:
    .string "INTLGCE{END}"

    .global gUnknown_08215CB8
gUnknown_08215CB8:
    .string "FATE{END}"

    .global gUnknown_08215CBD
gUnknown_08215CBD:
    .string "MAG DEF{END}"

    .global gUnknown_08215CC5
gUnknown_08215CC5:
    .string "MAG DEF{END}"

    .global gUnknown_08215CCD
gUnknown_08215CCD:
    .string "WPN{END}"

    .global gUnknown_08215CD1
gUnknown_08215CD1:
    .string "SHD{END}"

    .global gUnknown_08215CD5
gUnknown_08215CD5:
    .string "ARM{END}"

    .global gUnknown_08215CD9
gUnknown_08215CD9:
    .string "HLM{END}"

    .global gUnknown_08215CDD
gUnknown_08215CDD:
    .string "ETC{END}"

    .global gUnknown_08215CE1
gUnknown_08215CE1:
    .string "Revert{END}"

    .global gUnknown_08215CE8
gUnknown_08215CE8:
    .string "STRNGTH{END}"

    .global gUnknown_08215CF0
gUnknown_08215CF0:
    .string "VIGOR{END}"

    .global gUnknown_08215CF6
gUnknown_08215CF6:
    .string "AGILITY{END}"

    .global gUnknown_08215CFE
gUnknown_08215CFE:
    .string "WISDOM{END}"

    .global gUnknown_08215D05
gUnknown_08215D05:
    .string "LUCK{END}"

    .global gUnknown_08215D0A
gUnknown_08215D0A:
    .string " Psn{END}"

    .global gUnknown_08215D0F
gUnknown_08215D0F:
    .string " Zom{END}"

    .global gUnknown_08215D14
gUnknown_08215D14:
    .string " Crs{END}"

    .global gUnknown_08215D19
gUnknown_08215D19:
    .string "Fuse{END}"

    .global gUnknown_08215D1E
gUnknown_08215D1E:
    .string "Crs Psn{END}"

    .global gUnknown_08215D26
gUnknown_08215D26:
    .string "Crs Zom{END}"

    .global gUnknown_08215D2E
gUnknown_08215D2E:
    .string "Psn Zom{END}"

    .global gUnknown_08215D36
gUnknown_08215D36:
    .string "Stun{END}"

    .global gUnknown_08215D3B
gUnknown_08215D3B:
    .string "N/A{END}"

    .global gUnknown_08215D3F
gUnknown_08215D3F:
    .string "/{END}"

    .global gUnknown_08215D41
gUnknown_08215D41:
    .string "ANGRFF{END}"

    .global gUnknown_08215D48
gUnknown_08215D48:
    .string "VERTEID{END}"

    .global gUnknown_08215D50
gUnknown_08215D50:
    .string "AKTIV{END}"

    .global gUnknown_08215D56
gUnknown_08215D56:
    .string "INTLGNZ{END}"

    .global gUnknown_08215D5E
gUnknown_08215D5E:
    .string "CHRSMA{END}"

    .global gUnknown_08215D65
gUnknown_08215D65:
    .string "MAG.RES.{END}"

    .global gUnknown_08215D6E
gUnknown_08215D6E:
    .string "MAG VER{END}"

    .global gUnknown_08215D76
gUnknown_08215D76:
    .string "WFF{END}"

    .global gUnknown_08215D7A
gUnknown_08215D7A:
    .string "SHD{END}"

    .global gUnknown_08215D7E
gUnknown_08215D7E:
    .string "RST{END}"

    .global gUnknown_08215D82
gUnknown_08215D82:
    .string "HLM{END}"

    .global gUnknown_08215D86
gUnknown_08215D86:
    .string "SON{END}"

    .global gUnknown_08215D8A
gUnknown_08215D8A:
    .string "Umkehr{END}"

    .global gUnknown_08215D91
gUnknown_08215D91:
    .string "STÄRKE{END}"

    .global gUnknown_08215D98
gUnknown_08215D98:
    .string "ENRGIE{END}"

    .global gUnknown_08215D9F
gUnknown_08215D9F:
    .string "AGILIT{END}"

    .global gUnknown_08215DA6
gUnknown_08215DA6:
    .string "WEISHT{END}"

    .global gUnknown_08215DAD
gUnknown_08215DAD:
    .string "GLÜCK{END}"

    .global gUnknown_08215DB3
gUnknown_08215DB3:
    .string " Gft{END}"

    .global gUnknown_08215DB8
gUnknown_08215DB8:
    .string " Zom{END}"

    .global gUnknown_08215DBD
gUnknown_08215DBD:
    .string " Vfl{END}"

    .global gUnknown_08215DC2
gUnknown_08215DC2:
    .string "Fus{END}"

    .global gUnknown_08215DC6
gUnknown_08215DC6:
    .string "Vfl Gft{END}"

    .global gUnknown_08215DCE
gUnknown_08215DCE:
    .string "Vfl Zom{END}"

    .global gUnknown_08215DD6
gUnknown_08215DD6:
    .string "Gft Zom{END}"

    .global gUnknown_08215DDE
gUnknown_08215DDE:
    .string "Btbt{END}"

    .global gUnknown_08215DE3
gUnknown_08215DE3:
    .string "N/V{END}"

    .global gUnknown_08215DE7
gUnknown_08215DE7:
    .string "/{END}"

    .global gUnknown_08215DE9
gUnknown_08215DE9:
    .string "ATTAQUE{END}"

    .global gUnknown_08215DF1
gUnknown_08215DF1:
    .string "DEFENSE{END}"

    .global gUnknown_08215DF9
gUnknown_08215DF9:
    .string "ACTIVE{END}"

    .global gUnknown_08215E00
gUnknown_08215E00:
    .string "INTEL{END}"

    .global gUnknown_08215E06
gUnknown_08215E06:
    .string "DESTIN{END}"

    .global gUnknown_08215E0D
gUnknown_08215E0D:
    .string "DEF MAG{END}"

    .global gUnknown_08215E15
gUnknown_08215E15:
    .string "DEF MAG{END}"

    .global gUnknown_08215E1D
gUnknown_08215E1D:
    .string "ARM{END}"

    .global gUnknown_08215E21
gUnknown_08215E21:
    .string "BOU{END}"

    .global gUnknown_08215E25
gUnknown_08215E25:
    .string "HAB{END}"

    .global gUnknown_08215E29
gUnknown_08215E29:
    .string "CAS{END}"

    .global gUnknown_08215E2D
gUnknown_08215E2D:
    .string "ETC{END}"

    .global gUnknown_08215E31
gUnknown_08215E31:
    .string "Inverser{END}"

    .global gUnknown_08215E3A
gUnknown_08215E3A:
    .string "FORCE{END}"

    .global gUnknown_08215E40
gUnknown_08215E40:
    .string "VIGUEUR{END}"

    .global gUnknown_08215E48
gUnknown_08215E48:
    .string "AGILITE{END}"

    .global gUnknown_08215E50
gUnknown_08215E50:
    .string "SAGESSE{END}"

    .global gUnknown_08215E58
gUnknown_08215E58:
    .string "CHANCE{END}"

    .global gUnknown_08215E5F
gUnknown_08215E5F:
    .string " Psn{END}"

    .global gUnknown_08215E64
gUnknown_08215E64:
    .string " Zom{END}"

    .global gUnknown_08215E69
gUnknown_08215E69:
    .string " Crs{END}"

    .global gUnknown_08215E6E
gUnknown_08215E6E:
    .string "Fus{END}"

    .global gUnknown_08215E72
gUnknown_08215E72:
    .string "Crs Psn{END}"

    .global gUnknown_08215E7A
gUnknown_08215E7A:
    .string "Crs Zom{END}"

    .global gUnknown_08215E82
gUnknown_08215E82:
    .string "Psn Zom{END}"

    .global gUnknown_08215E8A
gUnknown_08215E8A:
    .string "Etourd{END}"

    .global gUnknown_08215E91
gUnknown_08215E91:
    .string "Non Ap{END}"

