    .global gUnknown_08183140
gUnknown_08183140:
    .string "LANGUAGE{END}"

    .global gUnknown_08183149
gUnknown_08183149:
    .string "LANGUE{END}"

    .global gUnknown_08183150
gUnknown_08183150:
    .string "SPRACHE{END}"

    .global gUnknown_08183158
gUnknown_08183158:
    .string "English{END}"

    .global gUnknown_08183160
gUnknown_08183160:
    .string "Français{END}"

    .global gUnknown_08183169
gUnknown_08183169:
    .string "Deutsch{END}"

    .global gUnknown_08183171
gUnknown_08183171:
    .string "OK to delete the data{END}"

    .global gUnknown_08183187
gUnknown_08183187:
    .string "?{END}"

    .global gUnknown_08183189
gUnknown_08183189:
    .string "YES  NO{END}"

    .global gUnknown_08183191
gUnknown_08183191:
    .string "Yes{END}"

    .global gUnknown_08183195
gUnknown_08183195:
    .string " No{END}"

    .global gUnknown_08183199
gUnknown_08183199:
    .string "cù{END}"

    .global gUnknown_0818319C
gUnknown_0818319C:
    .string "ccù{END}"

    .global gUnknown_081831A0
gUnknown_081831A0:
    .string "EXCHANGE{END}"

    .global gUnknown_081831A9
gUnknown_081831A9:
    .string "WARNING: Save Data{END}"

    .global gUnknown_081831BC
gUnknown_081831BC:
    .string " already exists.{END}"

    .global gUnknown_081831CD
gUnknown_081831CD:
    .string "WARNING: Starting the{END}"

    .global gUnknown_081831E3
gUnknown_081831E3:
    .string "game from the Quick Save{END}"

    .global gUnknown_081831FC
gUnknown_081831FC:
    .string "point will delete the{END}"

    .global gUnknown_08183212
gUnknown_08183212:
    .string "data.{END}"

    .global gUnknown_08183218
gUnknown_08183218:
    .string "Start the game from the{END}"

    .global gUnknown_08183230
gUnknown_08183230:
    .string "Quick Save point?{END}"

    .global gUnknown_08183242
gUnknown_08183242:
    .string "{END}"

    .global gUnknown_08183243
gUnknown_08183243:
    .string "Unfortunately, the saved{END}"

    .global gUnknown_0818325C
gUnknown_0818325C:
    .string "data has been erased.{END}"

    .global gUnknown_08183272
gUnknown_08183272:
    .string "SCENARIO{END}"

    .global gUnknown_0818327B
gUnknown_0818327B:
    .string "GAME START{END}"

    .global gUnknown_08183286
gUnknown_08183286:
    .string "NEW GAME{END}"

    .global gUnknown_0818328F
gUnknown_0818328F:
    .string "COPY{END}"

    .global gUnknown_08183294
gUnknown_08183294:
    .string "ERASE{END}"

    .global gUnknown_0818329A
gUnknown_0818329A:
    .string "No.{END}"

    .global gUnknown_0818329E
gUnknown_0818329E:
    .string "Blank{END}"

    .global gUnknown_081832A4
gUnknown_081832A4:
    .string "Text Speed{END}"

    .global gUnknown_081832AF
gUnknown_081832AF:
    .string "Dash{END}"

    .global gUnknown_081832B4
gUnknown_081832B4:
    .string "{0xA3}{0x9B}{0xC6}{0xDF}{END}"

    .global gUnknown_081832B9
gUnknown_081832B9:
    .string "Music{END}"

    .global gUnknown_081832BF
gUnknown_081832BF:
    .string "END{END}"

    .global gUnknown_081832C3
gUnknown_081832C3:
    .string "Fast{END}"

    .global gUnknown_081832C8
gUnknown_081832C8:
    .string "Nrml{END}"

    .global gUnknown_081832CD
gUnknown_081832CD:
    .string "Slow{END}"

    .global gUnknown_081832D2
gUnknown_081832D2:
    .string "Nrml{END}"

    .global gUnknown_081832D7
gUnknown_081832D7:
    .string "Auto{END}"

    .global gUnknown_081832DC
gUnknown_081832DC:
    .string "{0xA5}{0xAB}{0xC2}{0x9D}{END}"

    .global gUnknown_081832E1
gUnknown_081832E1:
    .string "{0xBB}{0xB1}{0xBF}{0xC1}{END}"

    .global gUnknown_081832E6
gUnknown_081832E6:
    .string "ON{END}"

    .global gUnknown_081832E9
gUnknown_081832E9:
    .string "OFF{END}"

    .global gUnknown_081832ED
gUnknown_081832ED:
    .string "{0x7F}   {END}"

    .global gUnknown_081832F2
gUnknown_081832F2:
    .string "{END}"

    .global gUnknown_081832F3
gUnknown_081832F3:
    .string "{END}"

    .global gUnknown_081832F4
gUnknown_081832F4:
    .string "{END}"

    .global gUnknown_081832F5
gUnknown_081832F5:
    .string " {0x7F}  {END}"

    .global gUnknown_081832FA
gUnknown_081832FA:
    .string "{END}"

    .global gUnknown_081832FB
gUnknown_081832FB:
    .string "{END}"

    .global gUnknown_081832FC
gUnknown_081832FC:
    .string "{END}"

    .global gUnknown_081832FD
gUnknown_081832FD:
    .string "  {0x7F} {END}"

    .global gUnknown_08183302
gUnknown_08183302:
    .string "{END}"

    .global gUnknown_08183303
gUnknown_08183303:
    .string "{END}"

    .global gUnknown_08183304
gUnknown_08183304:
    .string "{END}"

    .global gUnknown_08183305
gUnknown_08183305:
    .string "   {0x7F}{END}"

    .global gUnknown_0818330A
gUnknown_0818330A:
    .string "{END}"

    .global gUnknown_0818330B
gUnknown_0818330B:
    .string "{END}"

    .global gUnknown_0818330C
gUnknown_0818330C:
    .string "{END}"

    .global gUnknown_0818330D
gUnknown_0818330D:
    .string "Daten löschen OK {END}"

    .global gUnknown_0818331F
gUnknown_0818331F:
    .string "?{END}"

    .global gUnknown_08183321
gUnknown_08183321:
    .string "JA NEIN{END}"

    .global gUnknown_08183329
gUnknown_08183329:
    .string "Ja{END}"

    .global gUnknown_0818332C
gUnknown_0818332C:
    .string "Nein{END}"

    .global gUnknown_08183331
gUnknown_08183331:
    .string "AUSTAUSCH{END}"

    .global gUnknown_0818333B
gUnknown_0818333B:
    .string "WARNUNG: Daten {END}"

    .global gUnknown_0818334B
gUnknown_0818334B:
    .string "existieren bereits.{END}"

    .global gUnknown_0818335F
gUnknown_0818335F:
    .string "WARNUNG: Alte{END}"

    .global gUnknown_0818336D
gUnknown_0818336D:
    .string "Daten werden{END}"

    .global gUnknown_0818337A
gUnknown_0818337A:
    .string "gelöscht!{END}"

    .global gUnknown_08183384
gUnknown_08183384:
    .string "{END}"

    .global gUnknown_08183385
gUnknown_08183385:
    .string "Quick-Save{END}"

    .global gUnknown_08183390
gUnknown_08183390:
    .string "starten?{END}"

    .global gUnknown_08183399
gUnknown_08183399:
    .string "{END}"

    .global gUnknown_0818339A
gUnknown_0818339A:
    .string "Die gespeicherten Daten{END}"

    .global gUnknown_081833B2
gUnknown_081833B2:
    .string "wurden gelöscht{END}"

    .global gUnknown_081833C2
gUnknown_081833C2:
    .string "SZENARIO{END}"

    .global gUnknown_081833CB
gUnknown_081833CB:
    .string "SPIELSTART{END}"

    .global gUnknown_081833D6
gUnknown_081833D6:
    .string "NEUES SPIEL{END}"

    .global gUnknown_081833E2
gUnknown_081833E2:
    .string "KOPIE{END}"

    .global gUnknown_081833E8
gUnknown_081833E8:
    .string "LÖSCHEN{END}"

    .global gUnknown_081833F0
gUnknown_081833F0:
    .string "Nr.{END}"

    .global gUnknown_081833F4
gUnknown_081833F4:
    .string "Leer{END}"

    .global gUnknown_081833F9
gUnknown_081833F9:
    .string "Texttempo{END}"

    .global gUnknown_08183403
gUnknown_08183403:
    .string "Renn{END}"

    .global gUnknown_08183408
gUnknown_08183408:
    .string "Musik{END}"

    .global gUnknown_0818340E
gUnknown_0818340E:
    .string "ENDE{END}"

    .global gUnknown_08183413
gUnknown_08183413:
    .string "shnl{END}"

    .global gUnknown_08183418
gUnknown_08183418:
    .string "Nrml{END}"

    .global gUnknown_0818341D
gUnknown_0818341D:
    .string "Lngs{END}"

    .global gUnknown_08183422
gUnknown_08183422:
    .string "Nrml{END}"

    .global gUnknown_08183427
gUnknown_08183427:
    .string "Auto{END}"

    .global gUnknown_0818342C
gUnknown_0818342C:
    .string "AN{END}"

    .global gUnknown_0818342F
gUnknown_0818342F:
    .string "AUS{END}"

    .global gUnknown_08183433
gUnknown_08183433:
    .string "OK pour effacer{END}"

    .global gUnknown_08183443
gUnknown_08183443:
    .string "?{END}"

    .global gUnknown_08183445
gUnknown_08183445:
    .string "OUI  NON{END}"

    .global gUnknown_0818344E
gUnknown_0818344E:
    .string "Oui{END}"

    .global gUnknown_08183452
gUnknown_08183452:
    .string "Non{END}"

    .global gUnknown_08183456
gUnknown_08183456:
    .string "ECHANGER{END}"

    .global gUnknown_0818345F
gUnknown_0818345F:
    .string "AVERTISSEMENT: les données de{END}"

    .global gUnknown_0818347D
gUnknown_0818347D:
    .string " existent déjà.{END}"

    .global gUnknown_0818348D
gUnknown_0818348D:
    .string "AVERTISSEMENT : démarrer{END}"

    .global gUnknown_081834A6
gUnknown_081834A6:
    .string "la partie au point{END}"

    .global gUnknown_081834B9
gUnknown_081834B9:
    .string "de sauvegarde rapide {END}"

    .global gUnknown_081834CF
gUnknown_081834CF:
    .string "effacera les données.{END}"

    .global gUnknown_081834E5
gUnknown_081834E5:
    .string "Démarrer la partie à {END}"

    .global gUnknown_081834FB
gUnknown_081834FB:
    .string "partir du point de {END}"

    .global gUnknown_0818350F
gUnknown_0818350F:
    .string "sauvegarde rapide ?{END}"

    .global gUnknown_08183523
gUnknown_08183523:
    .string "Hélas, les données{END}"

    .global gUnknown_08183536
gUnknown_08183536:
    .string "sauvegardées ont été effacées.{END}"

    .global gUnknown_08183555
gUnknown_08183555:
    .string "SCENARIO{END}"

    .global gUnknown_0818355E
gUnknown_0818355E:
    .string "LANCER JEU{END}"

    .global gUnknown_08183569
gUnknown_08183569:
    .string "NOUV PARTIE{END}"

    .global gUnknown_08183575
gUnknown_08183575:
    .string "COPIER{END}"

    .global gUnknown_0818357C
gUnknown_0818357C:
    .string "EFFACER{END}"

    .global gUnknown_08183584
gUnknown_08183584:
    .string "No.{END}"

    .global gUnknown_08183588
gUnknown_08183588:
    .string "Vide{END}"

    .global gUnknown_0818358D
gUnknown_0818358D:
    .string "Texte{END}"

    .global gUnknown_08183593
gUnknown_08183593:
    .string "Courir{END}"

    .global gUnknown_0818359A
gUnknown_0818359A:
    .string "Musique{END}"

    .global gUnknown_081835A2
gUnknown_081835A2:
    .string "Fin{END}"

    .global gUnknown_081835A6
gUnknown_081835A6:
    .string "Rapd{END}"

    .global gUnknown_081835AB
gUnknown_081835AB:
    .string "Nrml{END}"

    .global gUnknown_081835B0
gUnknown_081835B0:
    .string "Lent{END}"

    .global gUnknown_081835B5
gUnknown_081835B5:
    .string "Nrml{END}"

    .global gUnknown_081835BA
gUnknown_081835BA:
    .string "Auto{END}"

    .global gUnknown_081835BF
gUnknown_081835BF:
    .string "Oui{END}"

    .global gUnknown_081835C3
gUnknown_081835C3:
    .string "Non{END}"

