    .global gUnknown_082114C0
gUnknown_082114C0:
    .string "{END}"

    .global gUnknown_082114C1
gUnknown_082114C1:
    .string "ゲイト{KANJI 0x73}{END}"

    .global gUnknown_082114C7
gUnknown_082114C7:
    .string "モトの{KANJI 0x78}{END}"

    .global gUnknown_082114CD
gUnknown_082114CD:
    .string "コルセアの{KANJI 0x78}{END}"

    .global gUnknown_082114D5
gUnknown_082114D5:
    .string "ウインディア{END}"

    .global gUnknown_082114DC
gUnknown_082114DC:
    .string "はいきょ{END}"

    .global gUnknown_082114E1
gUnknown_082114E1:
    .string "きょうどうたい{END}"

    .global gUnknown_082114E9
gUnknown_082114E9:
    .string "カペタン{KANJI 0x73}{END}"

    .global gUnknown_082114F0
gUnknown_082114F0:
    .string "スイマ-{KANJI 0x2A}{END}"

    .global gUnknown_082114F7
gUnknown_082114F7:
    .string "{KANJI 0x2E}の{KANJI 0x3E}の{KANJI 0x78}{END}"

    .global gUnknown_08211500
gUnknown_08211500:
    .string "くじらみさき{END}"

    .global gUnknown_08211507
gUnknown_08211507:
    .string "ハンタ-ごや{END}"

    .global gUnknown_0821150E
gUnknown_0821150E:
    .string "ファマ{KANJI 0x73}{END}"

    .global gUnknown_08211514
gUnknown_08211514:
    .string "おんがくのくに{END}"

    .global gUnknown_0821151C
gUnknown_0821151C:
    .string "ガンツ{END}"

    .global gUnknown_08211520
gUnknown_08211520:
    .string "いのりのやど{END}"

    .global gUnknown_08211527
gUnknown_08211527:
    .string "コットのとりで{END}"

    .global gUnknown_0821152F
gUnknown_0821152F:
    .string "バンドオ{KANJI 0x4A}{KANJI 0x43}{END}"

    .global gUnknown_08211538
gUnknown_08211538:
    .string "ドラグニ-ル{END}"

    .global gUnknown_0821153F
gUnknown_0821153F:
    .string "エブライ{END}"

    .global gUnknown_08211544
gUnknown_08211544:
    .string "ハイランド{KANJI 0x2A}{END}"

    .global gUnknown_0821154C
gUnknown_0821154C:
    .string "イ-のどうくつ{END}"

    .global gUnknown_08211554
gUnknown_08211554:
    .string "うらやぶ{END}"

    .global gUnknown_08211559
gUnknown_08211559:
    .string "フタビ{KANJI 0x1F}{END}"

    .global gUnknown_0821155F
gUnknown_0821155F:
    .string "タグジの{KANJI 0x2F}{END}"

    .global gUnknown_08211566
gUnknown_08211566:
    .string "ロッコ{KANJI 0x1F}{END}"

    .global gUnknown_0821156C
gUnknown_0821156C:
    .string "エバのぬけ{KANJI 0x85}{END}"

    .global gUnknown_08211574
gUnknown_08211574:
    .string "ウパのどうくつ{END}"

    .global gUnknown_0821157C
gUnknown_0821157C:
    .string "マオリ{KANJI 0x1F}{END}"

    .global gUnknown_08211582
gUnknown_08211582:
    .string "{KANJI 0x90}{KANJI 0x65}の{KANJI 0x80}{END}"

    .global gUnknown_0821158A
gUnknown_0821158A:
    .string "ぬけみち{END}"

    .global gUnknown_0821158F
gUnknown_0821158F:
    .string "きおくの{KANJI 0x80}{END}"

    .global gUnknown_08211596
gUnknown_08211596:
    .string "くじらはま{END}"

    .global gUnknown_0821159C
gUnknown_0821159C:
    .string "くじらのくち{END}"

    .global gUnknown_082115A3
gUnknown_082115A3:
    .string "くじらたいない{END}"

    .global gUnknown_082115AB
gUnknown_082115AB:
    .string "くじらどうくつ{END}"

    .global gUnknown_082115B3
gUnknown_082115B3:
    .string "シャロンの{KANJI 0x2F}{END}"

    .global gUnknown_082115BB
gUnknown_082115BB:
    .string "ひみつつうろ{END}"

    .global gUnknown_082115C2
gUnknown_082115C2:
    .string "むげんの{KANJI 0x80}{END}"

    .global gUnknown_082115C9
gUnknown_082115C9:
    .string "かれいど{END}"

    .global gUnknown_082115CE
gUnknown_082115CE:
    .string "やまねこてい{END}"

    .global gUnknown_082115D5
gUnknown_082115D5:
    .string "ケハの{KANJI 0x2F}{END}"

    .global gUnknown_082115DB
gUnknown_082115DB:
    .string "ゆめのなか{END}"

    .global gUnknown_082115E1
gUnknown_082115E1:
    .string "ウインディア{KANJI 0x2A}{END}"

    .global gUnknown_082115EA
gUnknown_082115EA:
    .string "ぎしきの{KANJI 0x80}{END}"

    .global gUnknown_082115F1
gUnknown_082115F1:
    .string "そらのどうくつ{END}"

    .global gUnknown_082115F9
gUnknown_082115F9:
    .string "てんの{KANJI 0x80}{END}"

    .global gUnknown_082115FF
gUnknown_082115FF:
    .string "ぬすびとのはか{END}"

    .global gUnknown_08211607
gUnknown_08211607:
    .string "エバ{KANJI 0x3A}{KANJI 0x4A}{KANJI 0x43}{END}"

    .global gUnknown_08211610
gUnknown_08211610:
    .string "ふなつきば{END}"

    .global gUnknown_08211616
gUnknown_08211616:
    .string "コロシアム{END}"

    .global gUnknown_0821161C
gUnknown_0821161C:
    .string "ギルド{END}"

    .global gUnknown_08211620
gUnknown_08211620:
    .string "{KANJI 0x90}{KANJI 0xA8}がっこう{END}"

    .global gUnknown_08211629
gUnknown_08211629:
    .string "キルゴア{KANJI 0x42}{END}"

    .global gUnknown_08211630
gUnknown_08211630:
    .string "トラウト{KANJI 0x42}{END}"

    .global gUnknown_08211637
gUnknown_08211637:
    .string "{KANJI 0x18}{KANJI 0x75}ごや{END}"

    .global gUnknown_0821163E
gUnknown_0821163E:
    .string "みはりの{KANJI 0x80}{END}"

    .global gUnknown_08211645
gUnknown_08211645:
    .string "アルの{KANJI 0x2F}{END}"

    .global gUnknown_0821164B
gUnknown_0821164B:
    .string "みせものテント{END}"

    .global gUnknown_08211653
gUnknown_08211653:
    .string "じじいの{KANJI 0x42}{END}"

    .global gUnknown_0821165A
gUnknown_0821165A:
    .string "ナマンダじいん{END}"

    .global gUnknown_08211662
gUnknown_08211662:
    .string "ディ-スのへや{END}"

    .global gUnknown_0821166A
gUnknown_0821166A:
    .string "みさきの{KANJI 0x42}{END}"

    .global gUnknown_08211671
gUnknown_08211671:
    .string "{KANJI 0x3A}{KANJI 0x16}{KANJI 0x61}{END}"

    .global gUnknown_08211678
gUnknown_08211678:
    .string "きりのたに{END}"

    .global gUnknown_0821167E
gUnknown_0821167E:
    .string "たきのへや{END}"

    .global gUnknown_08211684
gUnknown_08211684:
    .string "アルの{KANJI 0x2F}{END}"

    .global gUnknown_0821168A
gUnknown_0821168A:
    .string "みぎうえ{END}"

    .global gUnknown_0821168F
gUnknown_0821168F:
    .string "ひだりうえ{END}"

    .global gUnknown_08211695
gUnknown_08211695:
    .string "みぎした{END}"

    .global gUnknown_0821169A
gUnknown_0821169A:
    .string "ひだりした{END}"

    .global gUnknown_082116A0
gUnknown_082116A0:
    .string "れいはいどう{END}"

    .global gUnknown_082116A7
gUnknown_082116A7:
    .string "フロ-シティ-{END}"

    .global gUnknown_082116AF
gUnknown_082116AF:
    .string "ちかのめいろ{END}"

    .global gUnknown_082116B6
gUnknown_082116B6:
    .string "トイレ{END}"

    .global gUnknown_082116BA
gUnknown_082116BA:
    .string "いっけんや{END}"

    .global gUnknown_082116C0
gUnknown_082116C0:
    .string "ちかのはかば{END}"

    .global gUnknown_082116C7
gUnknown_082116C7:
    .string "つりば{END}"

    .global gUnknown_082116CB
gUnknown_082116CB:
    .string "かりば{END}"

    .global gUnknown_082116CF
gUnknown_082116CF:
    .string "{KANJI 0x16}{KANJI 0x61}{END}"

    .align 2
    .global gUnknown_082116D4
gUnknown_082116D4:
    .word gUnknown_082114C0 @ 0 / 0x0
    .word gUnknown_082114C1 @ 1 / 0x1
    .word gUnknown_082114C7 @ 2 / 0x2
    .word gUnknown_082114CD @ 3 / 0x3
    .word gUnknown_082114D5 @ 4 / 0x4
    .word gUnknown_082114DC @ 5 / 0x5
    .word gUnknown_082114E1 @ 6 / 0x6
    .word gUnknown_082114E9 @ 7 / 0x7
    .word gUnknown_082114F0 @ 8 / 0x8
    .word gUnknown_082114F7 @ 9 / 0x9
    .word gUnknown_08211500 @ 10 / 0xA
    .word gUnknown_08211507 @ 11 / 0xB
    .word gUnknown_0821150E @ 12 / 0xC
    .word gUnknown_08211514 @ 13 / 0xD
    .word gUnknown_0821151C @ 14 / 0xE
    .word gUnknown_08211520 @ 15 / 0xF
    .word gUnknown_08211527 @ 16 / 0x10
    .word gUnknown_0821152F @ 17 / 0x11
    .word gUnknown_08211538 @ 18 / 0x12
    .word gUnknown_0821153F @ 19 / 0x13
    .word gUnknown_08211544 @ 20 / 0x14
    .word gUnknown_0821154C @ 21 / 0x15
    .word gUnknown_08211554 @ 22 / 0x16
    .word gUnknown_08211559 @ 23 / 0x17
    .word gUnknown_0821155F @ 24 / 0x18
    .word gUnknown_08211566 @ 25 / 0x19
    .word gUnknown_0821156C @ 26 / 0x1A
    .word gUnknown_08211574 @ 27 / 0x1B
    .word gUnknown_0821157C @ 28 / 0x1C
    .word gUnknown_08211582 @ 29 / 0x1D
    .word gUnknown_0821158A @ 30 / 0x1E
    .word gUnknown_0821158F @ 31 / 0x1F
    .word gUnknown_08211596 @ 32 / 0x20
    .word gUnknown_0821159C @ 33 / 0x21
    .word gUnknown_082115A3 @ 34 / 0x22
    .word gUnknown_082115AB @ 35 / 0x23
    .word gUnknown_082115B3 @ 36 / 0x24
    .word gUnknown_082115BB @ 37 / 0x25
    .word gUnknown_082115C2 @ 38 / 0x26
    .word gUnknown_082115C9 @ 39 / 0x27
    .word gUnknown_082115CE @ 40 / 0x28
    .word gUnknown_082115D5 @ 41 / 0x29
    .word gUnknown_082115DB @ 42 / 0x2A
    .word gUnknown_082115E1 @ 43 / 0x2B
    .word gUnknown_082115EA @ 44 / 0x2C
    .word gUnknown_082115F1 @ 45 / 0x2D
    .word gUnknown_082115F9 @ 46 / 0x2E
    .word gUnknown_082115FF @ 47 / 0x2F
    .word gUnknown_08211607 @ 48 / 0x30
    .word gUnknown_08211610 @ 49 / 0x31
    .word gUnknown_08211616 @ 50 / 0x32
    .word gUnknown_0821161C @ 51 / 0x33
    .word gUnknown_08211620 @ 52 / 0x34
    .word gUnknown_08211629 @ 53 / 0x35
    .word gUnknown_08211630 @ 54 / 0x36
    .word gUnknown_08211637 @ 55 / 0x37
    .word gUnknown_0821163E @ 56 / 0x38
    .word gUnknown_08211645 @ 57 / 0x39
    .word gUnknown_0821164B @ 58 / 0x3A
    .word gUnknown_08211653 @ 59 / 0x3B
    .word gUnknown_0821165A @ 60 / 0x3C
    .word gUnknown_08211662 @ 61 / 0x3D
    .word gUnknown_0821166A @ 62 / 0x3E
    .word gUnknown_08211671 @ 63 / 0x3F
    .word gUnknown_08211678 @ 64 / 0x40
    .word gUnknown_0821167E @ 65 / 0x41
    .word gUnknown_08211684 @ 66 / 0x42
    .word gUnknown_0821168A @ 67 / 0x43
    .word gUnknown_0821168F @ 68 / 0x44
    .word gUnknown_08211695 @ 69 / 0x45
    .word gUnknown_0821169A @ 70 / 0x46
    .word gUnknown_082116A0 @ 71 / 0x47
    .word gUnknown_082116A7 @ 72 / 0x48
    .word gUnknown_082116AF @ 73 / 0x49
    .word gUnknown_082116B6 @ 74 / 0x4A
    .word gUnknown_082116BA @ 75 / 0x4B
    .word gUnknown_082116C0 @ 76 / 0x4C
    .word gUnknown_082116C7 @ 77 / 0x4D
    .word gUnknown_082116CB @ 78 / 0x4E
    .word gUnknown_082116CF @ 79 / 0x4F
