    .global gUnknown_082109D6
gUnknown_082109D6:
    .string "{END}"

    .global gUnknown_082109D7
gUnknown_082109D7:
    .string "やくそう{END}"

    .global gUnknown_082109DC
gUnknown_082109DC:
    .string "げんきだま{END}"

    .global gUnknown_082109E2
gUnknown_082109E2:
    .string "トプリフエキス{END}"

    .global gUnknown_082109EA
gUnknown_082109EA:
    .string "リフラルエキス{END}"

    .global gUnknown_082109F2
gUnknown_082109F2:
    .string "きつけやく{END}"

    .global gUnknown_082109F8
gUnknown_082109F8:
    .string "つきのしずく{END}"

    .global gUnknown_082109FF
gUnknown_082109FF:
    .string "どくけし{END}"

    .global gUnknown_08210A04
gUnknown_08210A04:
    .string "ちりょくのみ{END}"

    .global gUnknown_08210A0B
gUnknown_08210A0B:
    .string "きよめのつゆ{END}"

    .global gUnknown_08210A12
gUnknown_08210A12:
    .string "ベムのなみだ{END}"

    .global gUnknown_08210A19
gUnknown_08210A19:
    .string "ばんのうやく{END}"

    .global gUnknown_08210A20
gUnknown_08210A20:
    .string "ちえのたま{END}"

    .global gUnknown_08210A26
gUnknown_08210A26:
    .string "スタミナのもと{END}"

    .global gUnknown_08210A2E
gUnknown_08210A2E:
    .string "ラッキ-ぼんぼん{END}"

    .global gUnknown_08210A37
gUnknown_08210A37:
    .string "パワ-フ-ド{END}"

    .global gUnknown_08210A3E
gUnknown_08210A3E:
    .string "はやめし{END}"

    .global gUnknown_08210A43
gUnknown_08210A43:
    .string "みそにこみ{END}"

    .global gUnknown_08210A49
gUnknown_08210A49:
    .string "こんじょうだま{END}"

    .global gUnknown_08210A51
gUnknown_08210A51:
    .string "ビッア{END}"

    .global gUnknown_08210A55
gUnknown_08210A55:
    .string "ファイアスパイス{END}"

    .global gUnknown_08210A5E
gUnknown_08210A5E:
    .string "かきごおり{END}"

    .global gUnknown_08210A64
gUnknown_08210A64:
    .string "かみなりおこし{END}"

    .global gUnknown_08210A6C
gUnknown_08210A6C:
    .string "とっこうやく{END}"

    .global gUnknown_08210A73
gUnknown_08210A73:
    .string "コイン{END}"

    .global gUnknown_08210A77
gUnknown_08210A77:
    .string "まもりけむり{END}"

    .global gUnknown_08210A7E
gUnknown_08210A7E:
    .string "かいじょだま{END}"

    .global gUnknown_08210A85
gUnknown_08210A85:
    .string "きのさお{END}"

    .global gUnknown_08210A8A
gUnknown_08210A8A:
    .string "たけざお{END}"

    .global gUnknown_08210A8F
gUnknown_08210A8F:
    .string "さおデラックス{END}"

    .global gUnknown_08210A97
gUnknown_08210A97:
    .string "たくみのさお{END}"

    .global gUnknown_08210A9E
gUnknown_08210A9E:
    .string "みみず{END}"

    .global gUnknown_08210AA2
gUnknown_08210AA2:
    .string "えび{END}"

    .global gUnknown_08210AA5
gUnknown_08210AA5:
    .string "さざえ{END}"

    .global gUnknown_08210AA9
gUnknown_08210AA9:
    .string "ばんのうえさ{END}"

    .global gUnknown_08210AB0
gUnknown_08210AB0:
    .string "いわし{END}"

    .global gUnknown_08210AB4
gUnknown_08210AB4:
    .string "さば{END}"

    .global gUnknown_08210AB7
gUnknown_08210AB7:
    .string "ねこまたぎ{END}"

    .global gUnknown_08210ABD
gUnknown_08210ABD:
    .string "べら{END}"

    .global gUnknown_08210AC0
gUnknown_08210AC0:
    .string "アブラメ{END}"

    .global gUnknown_08210AC5
gUnknown_08210AC5:
    .string "きす{END}"

    .global gUnknown_08210AC8
gUnknown_08210AC8:
    .string "たい{END}"

    .global gUnknown_08210ACB
gUnknown_08210ACB:
    .string "ちぬ{END}"

    .global gUnknown_08210ACE
gUnknown_08210ACE:
    .string "とりにく{END}"

    .global gUnknown_08210AD3
gUnknown_08210AD3:
    .string "にく{END}"

    .global gUnknown_08210AD6
gUnknown_08210AD6:
    .string "なんこつ{END}"

    .global gUnknown_08210ADB
gUnknown_08210ADB:
    .string "すじにく{END}"

    .global gUnknown_08210AE0
gUnknown_08210AE0:
    .string "きも{END}"

    .global gUnknown_08210AE3
gUnknown_08210AE3:
    .string "ロ-ス{END}"

    .global gUnknown_08210AE7
gUnknown_08210AE7:
    .string "たまご{END}"

    .global gUnknown_08210AEB
gUnknown_08210AEB:
    .string "サ-ロイン{END}"

    .global gUnknown_08210AF1
gUnknown_08210AF1:
    .string "おこげ{END}"

    .global gUnknown_08210AF5
gUnknown_08210AF5:
    .string "デスおじや{END}"

    .global gUnknown_08210AFB
gUnknown_08210AFB:
    .string "やみナベ{END}"

    .global gUnknown_08210B00
gUnknown_08210B00:
    .string "ハ-ドせんべい{END}"

    .global gUnknown_08210B08
gUnknown_08210B08:
    .string "たこやき{END}"

    .global gUnknown_08210B0D
gUnknown_08210B0D:
    .string "おこのみやき{END}"

    .global gUnknown_08210B14
gUnknown_08210B14:
    .string "おうごんとう{END}"

    .global gUnknown_08210B1B
gUnknown_08210B1B:
    .string "ひっさつのほのお{END}"

    .global gUnknown_08210B24
gUnknown_08210B24:
    .string "かみかぜだま{END}"

    .global gUnknown_08210B2B
gUnknown_08210B2B:
    .string "なまずのいかり{END}"

    .global gUnknown_08210B33
gUnknown_08210B33:
    .string "ひょうがのかけら{END}"

    .global gUnknown_08210B3C
gUnknown_08210B3C:
    .string "ビルメダル{END}"

    .global gUnknown_08210B42
gUnknown_08210B42:
    .string "ゆうきのベルト{END}"

    .global gUnknown_08210B4A
gUnknown_08210B4A:
    .string "そっこうのくつ{END}"

    .global gUnknown_08210B52
gUnknown_08210B52:
    .string "ダイアのうでわ{END}"

    .global gUnknown_08210B5A
gUnknown_08210B5A:
    .string "どくろのうでわ{END}"

    .global gUnknown_08210B62
gUnknown_08210B62:
    .string "ちえのわ{END}"

    .global gUnknown_08210B67
gUnknown_08210B67:
    .string "すずのくびわ{END}"

    .global gUnknown_08210B6E
gUnknown_08210B6E:
    .string "せいなるスカ-フ{END}"

    .global gUnknown_08210B77
gUnknown_08210B77:
    .string "かぜのうでわ{END}"

    .global gUnknown_08210B7E
gUnknown_08210B7E:
    .string "あいのうでわ{END}"

    .global gUnknown_08210B85
gUnknown_08210B85:
    .string "ガッツベルト{END}"

    .global gUnknown_08210B8C
gUnknown_08210B8C:
    .string "ロメロのうでわ{END}"

    .global gUnknown_08210B94
gUnknown_08210B94:
    .string "ゆめのイヤリング{END}"

    .global gUnknown_08210B9D
gUnknown_08210B9D:
    .string "いのちのうでわ{END}"

    .global gUnknown_08210BA5
gUnknown_08210BA5:
    .string "てつのうでわ{END}"

    .global gUnknown_08210BAC
gUnknown_08210BAC:
    .string "おまもり{END}"

    .global gUnknown_08210BB1
gUnknown_08210BB1:
    .string "ひかりのうでわ{END}"

    .global gUnknown_08210BB9
gUnknown_08210BB9:
    .string "{END}"

    .global gUnknown_08210BBA
gUnknown_08210BBA:
    .string "よみのうでわ{END}"

    .global gUnknown_08210BC1
gUnknown_08210BC1:
    .string "{END}"

    .global gUnknown_08210BC2
gUnknown_08210BC2:
    .string "{END}"

    .global gUnknown_08210BC3
gUnknown_08210BC3:
    .string "1Z{END}"

    .global gUnknown_08210BC6
gUnknown_08210BC6:
    .string "100Z{END}"

    .global gUnknown_08210BCB
gUnknown_08210BCB:
    .string "1000Z{END}"

    .global gUnknown_08210BD1
gUnknown_08210BD1:
    .string "10000Z{END}"

    .global gUnknown_08210BD8
gUnknown_08210BD8:
    .string "アルのみ{END}"

    .global gUnknown_08210BDD
gUnknown_08210BDD:
    .string "くじらまんじゅう{END}"

    .global gUnknown_08210BE6
gUnknown_08210BE6:
    .string "{END}"

    .global gUnknown_08210BE7
gUnknown_08210BE7:
    .string "{END}"

    .global gUnknown_08210BE8
gUnknown_08210BE8:
    .string "ジジのかがみ{END}"

    .global gUnknown_08210BEF
gUnknown_08210BEF:
    .string "ボウイナイフ{END}"

    .global gUnknown_08210BF6
gUnknown_08210BF6:
    .string "ショ-トボウ{END}"

    .global gUnknown_08210BFD
gUnknown_08210BFD:
    .string "どうのけん{END}"

    .global gUnknown_08210C03
gUnknown_08210C03:
    .string "ボウガン{END}"

    .global gUnknown_08210C08
gUnknown_08210C08:
    .string "きのぼう{END}"

    .global gUnknown_08210C0D
gUnknown_08210C0D:
    .string "ろっかくぼう{END}"

    .global gUnknown_08210C14
gUnknown_08210C14:
    .string "リベットナックル{END}"

    .global gUnknown_08210C1D
gUnknown_08210C1D:
    .string "ツタのムチ{END}"

    .global gUnknown_08210C23
gUnknown_08210C23:
    .string "ぎんのナイフ{END}"

    .global gUnknown_08210C2A
gUnknown_08210C2A:
    .string "マジシャンリング{END}"

    .global gUnknown_08210C33
gUnknown_08210C33:
    .string "らせつはおうけん{END}"

    .global gUnknown_08210C3C
gUnknown_08210C3C:
    .string "サ-ベル{END}"

    .global gUnknown_08210C41
gUnknown_08210C41:
    .string "ロングソ-ド{END}"

    .global gUnknown_08210C48
gUnknown_08210C48:
    .string "バスタ-ソ-ド{END}"

    .global gUnknown_08210C50
gUnknown_08210C50:
    .string "クロスボウ{END}"

    .global gUnknown_08210C56
gUnknown_08210C56:
    .string "ツインボウ{END}"

    .global gUnknown_08210C5C
gUnknown_08210C5C:
    .string "どうのバトン{END}"

    .global gUnknown_08210C63
gUnknown_08210C63:
    .string "クオ-タスタッフ{END}"

    .global gUnknown_08210C6C
gUnknown_08210C6C:
    .string "アイアンナックル{END}"

    .global gUnknown_08210C75
gUnknown_08210C75:
    .string "バ-ンナックル{END}"

    .global gUnknown_08210C7D
gUnknown_08210C7D:
    .string "ソ-サラ-リング{END}"

    .global gUnknown_08210C86
gUnknown_08210C86:
    .string "ファイアリング{END}"

    .global gUnknown_08210C8E
gUnknown_08210C8E:
    .string "ダガ-{END}"

    .global gUnknown_08210C92
gUnknown_08210C92:
    .string "バタフライナイフ{END}"

    .global gUnknown_08210C9B
gUnknown_08210C9B:
    .string "アサシンダガ-{END}"

    .global gUnknown_08210CA3
gUnknown_08210CA3:
    .string "ショ-トレイピア{END}"

    .global gUnknown_08210CAC
gUnknown_08210CAC:
    .string "エストック{END}"

    .global gUnknown_08210CB2
gUnknown_08210CB2:
    .string "フレイムソ-ド{END}"

    .global gUnknown_08210CBA
gUnknown_08210CBA:
    .string "スタ-ブリンガ-{END}"

    .global gUnknown_08210CC3
gUnknown_08210CC3:
    .string "ダマカスブレイド{END}"

    .global gUnknown_08210CCC
gUnknown_08210CCC:
    .string "ア-マ-ペイン{END}"

    .global gUnknown_08210CD4
gUnknown_08210CD4:
    .string "ドラゴンブレイド{END}"

    .global gUnknown_08210CDD
gUnknown_08210CDD:
    .string "キングオブダガ-{END}"

    .global gUnknown_08210CE6
gUnknown_08210CE6:
    .string "あしゅらのけん{END}"

    .global gUnknown_08210CEE
gUnknown_08210CEE:
    .string "こうていのけん{END}"

    .global gUnknown_08210CF6
gUnknown_08210CF6:
    .string "エルモアのけん{END}"

    .global gUnknown_08210CFE
gUnknown_08210CFE:
    .string "ファイアボウ{END}"

    .global gUnknown_08210D05
gUnknown_08210D05:
    .string "オ-トボウ{END}"

    .global gUnknown_08210D0B
gUnknown_08210D0B:
    .string "アイスバレル{END}"

    .global gUnknown_08210D12
gUnknown_08210D12:
    .string "バスタ-ボウ{END}"

    .global gUnknown_08210D19
gUnknown_08210D19:
    .string "どきゅう{END}"

    .global gUnknown_08210D1E
gUnknown_08210D1E:
    .string "むてきのレイピア{END}"

    .global gUnknown_08210D27
gUnknown_08210D27:
    .string "スネ-クスタッフ{END}"

    .global gUnknown_08210D30
gUnknown_08210D30:
    .string "ヒ-トスタッフ{END}"

    .global gUnknown_08210D38
gUnknown_08210D38:
    .string "しらかばのつえ{END}"

    .global gUnknown_08210D40
gUnknown_08210D40:
    .string "ライダトンファ{END}"

    .global gUnknown_08210D48
gUnknown_08210D48:
    .string "あばれんぼう{END}"

    .global gUnknown_08210D4F
gUnknown_08210D4F:
    .string "にゃんにゃんぼう{END}"

    .global gUnknown_08210D58
gUnknown_08210D58:
    .string "ホ-ククロ-{END}"

    .global gUnknown_08210D5F
gUnknown_08210D5F:
    .string "ブラスナックル{END}"

    .global gUnknown_08210D67
gUnknown_08210D67:
    .string "カイザ-ナックル{END}"

    .global gUnknown_08210D70
gUnknown_08210D70:
    .string "ファイナルブロ-{END}"

    .global gUnknown_08210D79
gUnknown_08210D79:
    .string "しっこくのゆびわ{END}"

    .global gUnknown_08210D82
gUnknown_08210D82:
    .string "スト-ムリング{END}"

    .global gUnknown_08210D8A
gUnknown_08210D8A:
    .string "アンバ-リング{END}"

    .global gUnknown_08210D92
gUnknown_08210D92:
    .string "イモ-タルリング{END}"

    .global gUnknown_08210D9B
gUnknown_08210D9B:
    .string "グラディウス{END}"

    .global gUnknown_08210DA2
gUnknown_08210DA2:
    .string "ノ-ザンダガ-{END}"

    .global gUnknown_08210DAA
gUnknown_08210DAA:
    .string "チャクラム{END}"

    .global gUnknown_08210DB0
gUnknown_08210DB0:
    .string "ぐれんのナイフ{END}"

    .global gUnknown_08210DB8
gUnknown_08210DB8:
    .string "かげぬい{END}"

    .global gUnknown_08210DBD
gUnknown_08210DBD:
    .string "デモニックナイフ{END}"

    .global gUnknown_08210DC6
gUnknown_08210DC6:
    .string "ピアシング{END}"

    .global gUnknown_08210DCC
gUnknown_08210DCC:
    .string "らいでんまる{END}"

    .global gUnknown_08210DD3
gUnknown_08210DD3:
    .string "ペネトレイタ-{END}"

    .global gUnknown_08210DDB
gUnknown_08210DDB:
    .string "いばらのムチ{END}"

    .global gUnknown_08210DE2
gUnknown_08210DE2:
    .string "ムチ{END}"

    .global gUnknown_08210DE5
gUnknown_08210DE5:
    .string "ダブルウイップ{END}"

    .global gUnknown_08210DED
gUnknown_08210DED:
    .string "ベナダンティ{END}"

    .global gUnknown_08210DF4
gUnknown_08210DF4:
    .string "ナインテイル{END}"

    .global gUnknown_08210DFB
gUnknown_08210DFB:
    .string "ノ-トゥング{END}"

    .global gUnknown_08210E02
gUnknown_08210E02:
    .string "こんごうぼう{END}"

    .global gUnknown_08210E09
gUnknown_08210E09:
    .string "クレセントソ-ド{END}"

    .global gUnknown_08210E12
gUnknown_08210E12:
    .string "ホ-リ-レイピア{END}"

    .global gUnknown_08210E1B
gUnknown_08210E1B:
    .string "バイガ-ソ-ド{END}"

    .global gUnknown_08210E23
gUnknown_08210E23:
    .string "スライサ-{END}"

    .global gUnknown_08210E29
gUnknown_08210E29:
    .string "ソルブレイド{END}"

    .global gUnknown_08210E30
gUnknown_08210E30:
    .string "ハンドナックル{END}"

    .global gUnknown_08210E38
gUnknown_08210E38:
    .string "リング{END}"

    .global gUnknown_08210E3C
gUnknown_08210E3C:
    .string "ワ-スリング{END}"

    .global gUnknown_08210E43
gUnknown_08210E43:
    .string "こんごうのけん{END}"

    .global gUnknown_08210E4B
gUnknown_08210E4B:
    .string "しこみドス{END}"

    .global gUnknown_08210E51
gUnknown_08210E51:
    .string "くびかりのムチ{END}"

    .global gUnknown_08210E59
gUnknown_08210E59:
    .string "フォ-ク{END}"

    .global gUnknown_08210E5E
gUnknown_08210E5E:
    .string "{END}"

    .global gUnknown_08210E5F
gUnknown_08210E5F:
    .string "{END}"

    .global gUnknown_08210E60
gUnknown_08210E60:
    .string "{END}"

    .global gUnknown_08210E61
gUnknown_08210E61:
    .string "ぬののふく{END}"

    .global gUnknown_08210E67
gUnknown_08210E67:
    .string "まどうしのロ-ブ{END}"

    .global gUnknown_08210E70
gUnknown_08210E70:
    .string "かわのレオタ-ド{END}"

    .global gUnknown_08210E79
gUnknown_08210E79:
    .string "かわのよろい{END}"

    .global gUnknown_08210E80
gUnknown_08210E80:
    .string "レンジャ-ス-ツ{END}"

    .global gUnknown_08210E89
gUnknown_08210E89:
    .string "サ-クレット{END}"

    .global gUnknown_08210E90
gUnknown_08210E90:
    .string "しんぴのかぶと{END}"

    .global gUnknown_08210E98
gUnknown_08210E98:
    .string "はちがね{END}"

    .global gUnknown_08210E9D
gUnknown_08210E9D:
    .string "リストバンド{END}"

    .global gUnknown_08210EA4
gUnknown_08210EA4:
    .string "てつのこう{END}"

    .global gUnknown_08210EAA
gUnknown_08210EAA:
    .string "シルクのてぶくろ{END}"

    .global gUnknown_08210EB3
gUnknown_08210EB3:
    .string "せいどうのたて{END}"

    .global gUnknown_08210EBB
gUnknown_08210EBB:
    .string "てつのたて{END}"

    .global gUnknown_08210EC1
gUnknown_08210EC1:
    .string "はんズボン{END}"

    .global gUnknown_08210EC7
gUnknown_08210EC7:
    .string "バックラ-{END}"

    .global gUnknown_08210ECD
gUnknown_08210ECD:
    .string "まもりのたて{END}"

    .global gUnknown_08210ED4
gUnknown_08210ED4:
    .string "みがわりのたて{END}"

    .global gUnknown_08210EDC
gUnknown_08210EDC:
    .string "せいどうのかぶと{END}"

    .global gUnknown_08210EE5
gUnknown_08210EE5:
    .string "ガラスのドミノ{END}"

    .global gUnknown_08210EED
gUnknown_08210EED:
    .string "きしのかぶと{END}"

    .global gUnknown_08210EF4
gUnknown_08210EF4:
    .string "しんくのスカ-フ{END}"

    .global gUnknown_08210EFD
gUnknown_08210EFD:
    .string "ロイヤルクラウン{END}"

    .global gUnknown_08210F06
gUnknown_08210F06:
    .string "こくようのかぶと{END}"

    .global gUnknown_08210F0F
gUnknown_08210F0F:
    .string "つきのマスク{END}"

    .global gUnknown_08210F16
gUnknown_08210F16:
    .string "くさりかたびら{END}"

    .global gUnknown_08210F1E
gUnknown_08210F1E:
    .string "てつのよろい{END}"

    .global gUnknown_08210F25
gUnknown_08210F25:
    .string "けんじゃのロ-ブ{END}"

    .global gUnknown_08210F2E
gUnknown_08210F2E:
    .string "てつのむねあて{END}"

    .global gUnknown_08210F36
gUnknown_08210F36:
    .string "はやてのふく{END}"

    .global gUnknown_08210F3D
gUnknown_08210F3D:
    .string "ブレスア-マ-{END}"

    .global gUnknown_08210F45
gUnknown_08210F45:
    .string "うみなりのロ-ブ{END}"

    .global gUnknown_08210F4E
gUnknown_08210F4E:
    .string "シルバ-ア-マ-{END}"

    .global gUnknown_08210F57
gUnknown_08210F57:
    .string "ひょうがのよろい{END}"

    .global gUnknown_08210F60
gUnknown_08210F60:
    .string "マグマのよろい{END}"

    .global gUnknown_08210F68
gUnknown_08210F68:
    .string "かぜのころも{END}"

    .global gUnknown_08210F6F
gUnknown_08210F6F:
    .string "だいちのよろい{END}"

    .global gUnknown_08210F77
gUnknown_08210F77:
    .string "ブレイブア-マ-{END}"

    .global gUnknown_08210F80
gUnknown_08210F80:
    .string "バンダナ{END}"

    .global gUnknown_08210F85
gUnknown_08210F85:
    .string "こんごうのよろい{END}"

    .global gUnknown_08210F8E
gUnknown_08210F8E:
    .string "にじのはごろも{END}"

    .global gUnknown_08210F96
gUnknown_08210F96:
    .string "ホ-リ-プレ-ト{END}"

    .global gUnknown_08210F9F
gUnknown_08210F9F:
    .string "クリムゾンガ-ブ{END}"

    .global gUnknown_08210FA8
gUnknown_08210FA8:
    .string "ドラゴンア-マ-{END}"

    .global gUnknown_08210FB1
gUnknown_08210FB1:
    .string "いのちのよろい{END}"

    .global gUnknown_08210FB9
gUnknown_08210FB9:
    .string "しのびしょうぞく{END}"

    .global gUnknown_08210FC2
gUnknown_08210FC2:
    .string "マンモのけがわ{END}"

    .global gUnknown_08210FCA
gUnknown_08210FCA:
    .string "ははなるころも{END}"

    .global gUnknown_08210FD2
gUnknown_08210FD2:
    .string "ラメラ-ア-マ-{END}"

    .global gUnknown_08210FDB
gUnknown_08210FDB:
    .string "はおうのよろい{END}"

    .global gUnknown_08210FE3
gUnknown_08210FE3:
    .string "ディアナのドレス{END}"

    .global gUnknown_08210FEC
gUnknown_08210FEC:
    .string "ちしきのガウン{END}"

    .global gUnknown_08210FF4
gUnknown_08210FF4:
    .string "はくぎんのたて{END}"

    .global gUnknown_08210FFC
gUnknown_08210FFC:
    .string "フレイムシ-ルド{END}"

    .global gUnknown_08211005
gUnknown_08211005:
    .string "アイスシ-ルド{END}"

    .global gUnknown_0821100D
gUnknown_0821100D:
    .string "こんごうのこう{END}"

    .global gUnknown_08211015
gUnknown_08211015:
    .string "こんごうのたて{END}"

    .global gUnknown_0821101D
gUnknown_0821101D:
    .string "きょじんのたて{END}"

    .global gUnknown_08211025
gUnknown_08211025:
    .string "ほしのたて{END}"

    .global gUnknown_0821102B
gUnknown_0821102B:
    .string "せいれいのたて{END}"

    .global gUnknown_08211033
gUnknown_08211033:
    .string "ドラゴンシ-ルド{END}"

    .global gUnknown_0821103C
gUnknown_0821103C:
    .string "ふうまのこう{END}"

    .global gUnknown_08211043
gUnknown_08211043:
    .string "マルスのたて{END}"

    .global gUnknown_0821104A
gUnknown_0821104A:
    .string "かがやきのかぶと{END}"

    .global gUnknown_08211053
gUnknown_08211053:
    .string "たいようのかめん{END}"

    .global gUnknown_0821105C
gUnknown_0821105C:
    .string "ぎんのティアラ{END}"

    .global gUnknown_08211064
gUnknown_08211064:
    .string "ドラゴンヘルム{END}"

    .global gUnknown_0821106C
gUnknown_0821106C:
    .string "はじゃのかんむり{END}"

    .global gUnknown_08211075
gUnknown_08211075:
    .string "せいしんのころも{END}"

    .global gUnknown_0821107E
gUnknown_0821107E:
    .string "いしよろい{END}"

    .global gUnknown_08211084
gUnknown_08211084:
    .string "きりさきのこて{END}"

    .global gUnknown_0821108C
gUnknown_0821108C:
    .string "いかずちのこて{END}"

    .global gUnknown_08211094
gUnknown_08211094:
    .string "ぶしんのこて{END}"

    .global gUnknown_0821109B
gUnknown_0821109B:
    .string "おうごんのよろい{END}"

    .global gUnknown_082110A4
gUnknown_082110A4:
    .string "やぶれずのよろい{END}"

    .global gUnknown_082110AD
gUnknown_082110AD:
    .string "ましょうのたて{END}"

    .global gUnknown_082110B5
gUnknown_082110B5:
    .string "ナフキン{END}"

    .global gUnknown_082110BA
gUnknown_082110BA:
    .string "おさら{END}"

    .align 2
    .global gUnknown_082110C0
gUnknown_082110C0:
    .word gUnknown_082109D6 @ 0 / 0x0
    .word gUnknown_082109D7 @ 1 / 0x1
    .word gUnknown_082109DC @ 2 / 0x2
    .word gUnknown_082109E2 @ 3 / 0x3
    .word gUnknown_082109EA @ 4 / 0x4
    .word gUnknown_082109F2 @ 5 / 0x5
    .word gUnknown_082109F8 @ 6 / 0x6
    .word gUnknown_082109FF @ 7 / 0x7
    .word gUnknown_08210A04 @ 8 / 0x8
    .word gUnknown_08210A0B @ 9 / 0x9
    .word gUnknown_08210A12 @ 10 / 0xA
    .word gUnknown_08210A19 @ 11 / 0xB
    .word gUnknown_08210A20 @ 12 / 0xC
    .word gUnknown_08210A26 @ 13 / 0xD
    .word gUnknown_08210A2E @ 14 / 0xE
    .word gUnknown_08210A37 @ 15 / 0xF
    .word gUnknown_08210A3E @ 16 / 0x10
    .word gUnknown_08210A43 @ 17 / 0x11
    .word gUnknown_08210A49 @ 18 / 0x12
    .word gUnknown_08210A51 @ 19 / 0x13
    .word gUnknown_08210A55 @ 20 / 0x14
    .word gUnknown_08210A5E @ 21 / 0x15
    .word gUnknown_08210A64 @ 22 / 0x16
    .word gUnknown_08210A6C @ 23 / 0x17
    .word gUnknown_08210A73 @ 24 / 0x18
    .word gUnknown_08210A77 @ 25 / 0x19
    .word gUnknown_08210A7E @ 26 / 0x1A
    .word gUnknown_08210A85 @ 27 / 0x1B
    .word gUnknown_08210A8A @ 28 / 0x1C
    .word gUnknown_08210A8F @ 29 / 0x1D
    .word gUnknown_08210A97 @ 30 / 0x1E
    .word gUnknown_08210A9E @ 31 / 0x1F
    .word gUnknown_08210AA2 @ 32 / 0x20
    .word gUnknown_08210AA5 @ 33 / 0x21
    .word gUnknown_08210AA9 @ 34 / 0x22
    .word gUnknown_08210AB0 @ 35 / 0x23
    .word gUnknown_08210AB4 @ 36 / 0x24
    .word gUnknown_08210AB7 @ 37 / 0x25
    .word gUnknown_08210ABD @ 38 / 0x26
    .word gUnknown_08210AC0 @ 39 / 0x27
    .word gUnknown_08210AC5 @ 40 / 0x28
    .word gUnknown_08210AC8 @ 41 / 0x29
    .word gUnknown_08210ACB @ 42 / 0x2A
    .word gUnknown_08210ACE @ 43 / 0x2B
    .word gUnknown_08210AD3 @ 44 / 0x2C
    .word gUnknown_08210AD6 @ 45 / 0x2D
    .word gUnknown_08210ADB @ 46 / 0x2E
    .word gUnknown_08210AE0 @ 47 / 0x2F
    .word gUnknown_08210AE3 @ 48 / 0x30
    .word gUnknown_08210AE7 @ 49 / 0x31
    .word gUnknown_08210AEB @ 50 / 0x32
    .word gUnknown_08210AF1 @ 51 / 0x33
    .word gUnknown_08210AF5 @ 52 / 0x34
    .word gUnknown_08210AFB @ 53 / 0x35
    .word gUnknown_08210B00 @ 54 / 0x36
    .word gUnknown_08210B08 @ 55 / 0x37
    .word gUnknown_08210B0D @ 56 / 0x38
    .word gUnknown_08210B14 @ 57 / 0x39
    .word gUnknown_08210B1B @ 58 / 0x3A
    .word gUnknown_08210B24 @ 59 / 0x3B
    .word gUnknown_08210B2B @ 60 / 0x3C
    .word gUnknown_08210B33 @ 61 / 0x3D
    .word gUnknown_08210B3C @ 62 / 0x3E
    .word gUnknown_08210B42 @ 63 / 0x3F
    .word gUnknown_08210B4A @ 64 / 0x40
    .word gUnknown_08210B52 @ 65 / 0x41
    .word gUnknown_08210B5A @ 66 / 0x42
    .word gUnknown_08210B62 @ 67 / 0x43
    .word gUnknown_08210B67 @ 68 / 0x44
    .word gUnknown_08210B6E @ 69 / 0x45
    .word gUnknown_08210B77 @ 70 / 0x46
    .word gUnknown_08210B7E @ 71 / 0x47
    .word gUnknown_08210B85 @ 72 / 0x48
    .word gUnknown_08210B8C @ 73 / 0x49
    .word gUnknown_08210B94 @ 74 / 0x4A
    .word gUnknown_08210B9D @ 75 / 0x4B
    .word gUnknown_08210BA5 @ 76 / 0x4C
    .word gUnknown_08210BAC @ 77 / 0x4D
    .word gUnknown_08210BB1 @ 78 / 0x4E
    .word gUnknown_08210BB9 @ 79 / 0x4F
    .word gUnknown_08210BBA @ 80 / 0x50
    .word gUnknown_08210BC1 @ 81 / 0x51
    .word gUnknown_08210BC2 @ 82 / 0x52
    .word gUnknown_08210BC3 @ 83 / 0x53
    .word gUnknown_08210BC6 @ 84 / 0x54
    .word gUnknown_08210BCB @ 85 / 0x55
    .word gUnknown_08210BD1 @ 86 / 0x56
    .word gUnknown_08210BD8 @ 87 / 0x57
    .word gUnknown_08210BDD @ 88 / 0x58
    .word gUnknown_08210BE6 @ 89 / 0x59
    .word gUnknown_08210BE7 @ 90 / 0x5A
    .word gUnknown_08210BE8 @ 91 / 0x5B
    .word gUnknown_08210BEF @ 92 / 0x5C
    .word gUnknown_08210BF6 @ 93 / 0x5D
    .word gUnknown_08210BFD @ 94 / 0x5E
    .word gUnknown_08210C03 @ 95 / 0x5F
    .word gUnknown_08210C08 @ 96 / 0x60
    .word gUnknown_08210C0D @ 97 / 0x61
    .word gUnknown_08210C14 @ 98 / 0x62
    .word gUnknown_08210C1D @ 99 / 0x63
    .word gUnknown_08210C23 @ 100 / 0x64
    .word gUnknown_08210C2A @ 101 / 0x65
    .word gUnknown_08210C33 @ 102 / 0x66
    .word gUnknown_08210C3C @ 103 / 0x67
    .word gUnknown_08210C41 @ 104 / 0x68
    .word gUnknown_08210C48 @ 105 / 0x69
    .word gUnknown_08210C50 @ 106 / 0x6A
    .word gUnknown_08210C56 @ 107 / 0x6B
    .word gUnknown_08210C5C @ 108 / 0x6C
    .word gUnknown_08210C63 @ 109 / 0x6D
    .word gUnknown_08210C6C @ 110 / 0x6E
    .word gUnknown_08210C75 @ 111 / 0x6F
    .word gUnknown_08210C7D @ 112 / 0x70
    .word gUnknown_08210C86 @ 113 / 0x71
    .word gUnknown_08210C8E @ 114 / 0x72
    .word gUnknown_08210C92 @ 115 / 0x73
    .word gUnknown_08210C9B @ 116 / 0x74
    .word gUnknown_08210CA3 @ 117 / 0x75
    .word gUnknown_08210CAC @ 118 / 0x76
    .word gUnknown_08210CB2 @ 119 / 0x77
    .word gUnknown_08210CBA @ 120 / 0x78
    .word gUnknown_08210CC3 @ 121 / 0x79
    .word gUnknown_08210CCC @ 122 / 0x7A
    .word gUnknown_08210CD4 @ 123 / 0x7B
    .word gUnknown_08210CDD @ 124 / 0x7C
    .word gUnknown_08210CE6 @ 125 / 0x7D
    .word gUnknown_08210CEE @ 126 / 0x7E
    .word gUnknown_08210CF6 @ 127 / 0x7F
    .word gUnknown_08210CFE @ 128 / 0x80
    .word gUnknown_08210D05 @ 129 / 0x81
    .word gUnknown_08210D0B @ 130 / 0x82
    .word gUnknown_08210D12 @ 131 / 0x83
    .word gUnknown_08210D19 @ 132 / 0x84
    .word gUnknown_08210D1E @ 133 / 0x85
    .word gUnknown_08210D27 @ 134 / 0x86
    .word gUnknown_08210D30 @ 135 / 0x87
    .word gUnknown_08210D38 @ 136 / 0x88
    .word gUnknown_08210D40 @ 137 / 0x89
    .word gUnknown_08210D48 @ 138 / 0x8A
    .word gUnknown_08210D4F @ 139 / 0x8B
    .word gUnknown_08210D58 @ 140 / 0x8C
    .word gUnknown_08210D5F @ 141 / 0x8D
    .word gUnknown_08210D67 @ 142 / 0x8E
    .word gUnknown_08210D70 @ 143 / 0x8F
    .word gUnknown_08210D79 @ 144 / 0x90
    .word gUnknown_08210D82 @ 145 / 0x91
    .word gUnknown_08210D8A @ 146 / 0x92
    .word gUnknown_08210D92 @ 147 / 0x93
    .word gUnknown_08210D9B @ 148 / 0x94
    .word gUnknown_08210DA2 @ 149 / 0x95
    .word gUnknown_08210DAA @ 150 / 0x96
    .word gUnknown_08210DB0 @ 151 / 0x97
    .word gUnknown_08210DB8 @ 152 / 0x98
    .word gUnknown_08210DBD @ 153 / 0x99
    .word gUnknown_08210DC6 @ 154 / 0x9A
    .word gUnknown_08210DCC @ 155 / 0x9B
    .word gUnknown_08210DD3 @ 156 / 0x9C
    .word gUnknown_08210DDB @ 157 / 0x9D
    .word gUnknown_08210DE2 @ 158 / 0x9E
    .word gUnknown_08210DE5 @ 159 / 0x9F
    .word gUnknown_08210DED @ 160 / 0xA0
    .word gUnknown_08210DF4 @ 161 / 0xA1
    .word gUnknown_08210DFB @ 162 / 0xA2
    .word gUnknown_08210E02 @ 163 / 0xA3
    .word gUnknown_08210E09 @ 164 / 0xA4
    .word gUnknown_08210E12 @ 165 / 0xA5
    .word gUnknown_08210E1B @ 166 / 0xA6
    .word gUnknown_08210E23 @ 167 / 0xA7
    .word gUnknown_08210E29 @ 168 / 0xA8
    .word gUnknown_08210E30 @ 169 / 0xA9
    .word gUnknown_08210E38 @ 170 / 0xAA
    .word gUnknown_08210E3C @ 171 / 0xAB
    .word gUnknown_08210E43 @ 172 / 0xAC
    .word gUnknown_08210E4B @ 173 / 0xAD
    .word gUnknown_08210E51 @ 174 / 0xAE
    .word gUnknown_08210E59 @ 175 / 0xAF
    .word gUnknown_08210E5E @ 176 / 0xB0
    .word gUnknown_08210E5F @ 177 / 0xB1
    .word gUnknown_08210E60 @ 178 / 0xB2
    .word gUnknown_08210E61 @ 179 / 0xB3
    .word gUnknown_08210E67 @ 180 / 0xB4
    .word gUnknown_08210E70 @ 181 / 0xB5
    .word gUnknown_08210E79 @ 182 / 0xB6
    .word gUnknown_08210E80 @ 183 / 0xB7
    .word gUnknown_08210E89 @ 184 / 0xB8
    .word gUnknown_08210E90 @ 185 / 0xB9
    .word gUnknown_08210E98 @ 186 / 0xBA
    .word gUnknown_08210E9D @ 187 / 0xBB
    .word gUnknown_08210EA4 @ 188 / 0xBC
    .word gUnknown_08210EAA @ 189 / 0xBD
    .word gUnknown_08210EB3 @ 190 / 0xBE
    .word gUnknown_08210EBB @ 191 / 0xBF
    .word gUnknown_08210EC1 @ 192 / 0xC0
    .word gUnknown_08210EC7 @ 193 / 0xC1
    .word gUnknown_08210ECD @ 194 / 0xC2
    .word gUnknown_08210ED4 @ 195 / 0xC3
    .word gUnknown_08210EDC @ 196 / 0xC4
    .word gUnknown_08210EE5 @ 197 / 0xC5
    .word gUnknown_08210EED @ 198 / 0xC6
    .word gUnknown_08210EF4 @ 199 / 0xC7
    .word gUnknown_08210EFD @ 200 / 0xC8
    .word gUnknown_08210F06 @ 201 / 0xC9
    .word gUnknown_08210F0F @ 202 / 0xCA
    .word gUnknown_08210F16 @ 203 / 0xCB
    .word gUnknown_08210F1E @ 204 / 0xCC
    .word gUnknown_08210F25 @ 205 / 0xCD
    .word gUnknown_08210F2E @ 206 / 0xCE
    .word gUnknown_08210F36 @ 207 / 0xCF
    .word gUnknown_08210F3D @ 208 / 0xD0
    .word gUnknown_08210F45 @ 209 / 0xD1
    .word gUnknown_08210F4E @ 210 / 0xD2
    .word gUnknown_08210F57 @ 211 / 0xD3
    .word gUnknown_08210F60 @ 212 / 0xD4
    .word gUnknown_08210F68 @ 213 / 0xD5
    .word gUnknown_08210F6F @ 214 / 0xD6
    .word gUnknown_08210F77 @ 215 / 0xD7
    .word gUnknown_08210F80 @ 216 / 0xD8
    .word gUnknown_08210F85 @ 217 / 0xD9
    .word gUnknown_08210F8E @ 218 / 0xDA
    .word gUnknown_08210F96 @ 219 / 0xDB
    .word gUnknown_08210F9F @ 220 / 0xDC
    .word gUnknown_08210FA8 @ 221 / 0xDD
    .word gUnknown_08210FB1 @ 222 / 0xDE
    .word gUnknown_08210FB9 @ 223 / 0xDF
    .word gUnknown_08210FC2 @ 224 / 0xE0
    .word gUnknown_08210FCA @ 225 / 0xE1
    .word gUnknown_08210FD2 @ 226 / 0xE2
    .word gUnknown_08210FDB @ 227 / 0xE3
    .word gUnknown_08210FE3 @ 228 / 0xE4
    .word gUnknown_08210FEC @ 229 / 0xE5
    .word gUnknown_08210FF4 @ 230 / 0xE6
    .word gUnknown_08210FFC @ 231 / 0xE7
    .word gUnknown_08211005 @ 232 / 0xE8
    .word gUnknown_0821100D @ 233 / 0xE9
    .word gUnknown_08211015 @ 234 / 0xEA
    .word gUnknown_0821101D @ 235 / 0xEB
    .word gUnknown_08211025 @ 236 / 0xEC
    .word gUnknown_0821102B @ 237 / 0xED
    .word gUnknown_08211033 @ 238 / 0xEE
    .word gUnknown_0821103C @ 239 / 0xEF
    .word gUnknown_08211043 @ 240 / 0xF0
    .word gUnknown_0821104A @ 241 / 0xF1
    .word gUnknown_08211053 @ 242 / 0xF2
    .word gUnknown_0821105C @ 243 / 0xF3
    .word gUnknown_08211064 @ 244 / 0xF4
    .word gUnknown_0821106C @ 245 / 0xF5
    .word gUnknown_08211075 @ 246 / 0xF6
    .word gUnknown_0821107E @ 247 / 0xF7
    .word gUnknown_08211084 @ 248 / 0xF8
    .word gUnknown_0821108C @ 249 / 0xF9
    .word gUnknown_08211094 @ 250 / 0xFA
    .word gUnknown_0821109B @ 251 / 0xFB
    .word gUnknown_082110A4 @ 252 / 0xFC
    .word gUnknown_082110AD @ 253 / 0xFD
    .word gUnknown_082110B5 @ 254 / 0xFE
    .word gUnknown_082110BA @ 255 / 0xFF
