    .global gUnknown_08213EC0
gUnknown_08213EC0:
    .string "{END}"

    .global gUnknown_08213EC1
gUnknown_08213EC1:
    .string "Drogen{END}"

    .global gUnknown_08213EC8
gUnknown_08213EC8:
    .string "Nanai{END}"

    .global gUnknown_08213ECE
gUnknown_08213ECE:
    .string "Winlan{END}"

    .global gUnknown_08213ED5
gUnknown_08213ED5:
    .string "Romero{END}"

    .global gUnknown_08213EDC
gUnknown_08213EDC:
    .string "Gust{END}"

    .global gUnknown_08213EE1
gUnknown_08213EE1:
    .string "Camlon{END}"

    .global gUnknown_08213EE8
gUnknown_08213EE8:
    .string "Nada{END}"

    .global gUnknown_08213EED
gUnknown_08213EED:
    .string "Tantar{END}"

    .global gUnknown_08213EF4
gUnknown_08213EF4:
    .string "Tuntar{END}"

    .global gUnknown_08213EFB
gUnknown_08213EFB:
    .string "Agua{END}"

    .global gUnknown_08213F00
gUnknown_08213F00:
    .string "Auria{END}"

    .global gUnknown_08213F06
gUnknown_08213F06:
    .string "Bleak{END}"

    .global gUnknown_08213F0C
gUnknown_08213F0C:
    .string "Arad{END}"

    .global gUnknown_08213F11
gUnknown_08213F11:
    .string "Spring{END}"

    .global gUnknown_08213F18
gUnknown_08213F18:
    .string "Tunlan{END}"

    .global gUnknown_08213F1F
gUnknown_08213F1F:
    .string "Gant{END}"

    .global gUnknown_08213F24
gUnknown_08213F24:
    .string "Scande{END}"

    .global gUnknown_08213F2B
gUnknown_08213F2B:
    .string "Carmen{END}"

    .global gUnknown_08213F32
gUnknown_08213F32:
    .string "Gramor{END}"

    .global gUnknown_08213F39
gUnknown_08213F39:
    .string "Wisdon{END}"

    .global gUnknown_08213F40
gUnknown_08213F40:
    .string "Karma{END}"

    .global gUnknown_08213F46
gUnknown_08213F46:
    .string "Prima{END}"

    .global gUnknown_08213F4C
gUnknown_08213F4C:
    .string "Krypt{END}"

    .global gUnknown_08213F52
gUnknown_08213F52:
    .string "Nabal{END}"

    .global gUnknown_08213F58
gUnknown_08213F58:
    .string "Tock{END}"

    .global gUnknown_08213F5D
gUnknown_08213F5D:
    .string "Spyre{END}"

    .global gUnknown_08213F63
gUnknown_08213F63:
    .string "Obelisk{END}"

    .global gUnknown_08213F6B
gUnknown_08213F6B:
    .string "Pagoda{END}"

    @Unreferenced string
    .global gUnknown_08213F72
gUnknown_08213F72:
    .string "{END}"

    @Unreferenced string
    .global gUnknown_08213F73
gUnknown_08213F73:
    .string "{END}"

    .align 2
    .global gUnknown_08213F74
gUnknown_08213F74:
    .word gUnknown_08213EC0 @ 0 / 0x0
    .word gUnknown_08213EC1 @ 1 / 0x1
    .word gUnknown_08213EC8 @ 2 / 0x2
    .word gUnknown_08213ECE @ 3 / 0x3
    .word gUnknown_08213ED5 @ 4 / 0x4
    .word gUnknown_08213EDC @ 5 / 0x5
    .word gUnknown_08213EE1 @ 6 / 0x6
    .word gUnknown_08213EE8 @ 7 / 0x7
    .word gUnknown_08213EED @ 8 / 0x8
    .word gUnknown_08213EF4 @ 9 / 0x9
    .word gUnknown_08213EFB @ 10 / 0xA
    .word gUnknown_08213F00 @ 11 / 0xB
    .word gUnknown_08213F06 @ 12 / 0xC
    .word gUnknown_08213F0C @ 13 / 0xD
    .word gUnknown_08213F11 @ 14 / 0xE
    .word gUnknown_08213F18 @ 15 / 0xF
    .word gUnknown_08213F1F @ 16 / 0x10
    .word gUnknown_08213F24 @ 17 / 0x11
    .word gUnknown_08213F2B @ 18 / 0x12
    .word gUnknown_08213F32 @ 19 / 0x13
    .word gUnknown_08213F39 @ 20 / 0x14
    .word gUnknown_08213F40 @ 21 / 0x15
    .word gUnknown_08213F46 @ 22 / 0x16
    .word gUnknown_08213F4C @ 23 / 0x17
    .word gUnknown_08213F52 @ 24 / 0x18
    .word gUnknown_08213F58 @ 25 / 0x19
    .word gUnknown_08213F5D @ 26 / 0x1A
    .word gUnknown_08213F63 @ 27 / 0x1B
    .word gUnknown_08213F6B @ 28 / 0x1C
