    .global gUnknown_08211E4C
gUnknown_08211E4C:
    .string "Frog{END}"

    .global gUnknown_08211E51
gUnknown_08211E51:
    .string "Knight{END}"

    .global gUnknown_08211E58
gUnknown_08211E58:
    .string "Wizard{END}"

    .global gUnknown_08211E5F
gUnknown_08211E5F:
    .string "Wizard{END}"

    .global gUnknown_08211E66
gUnknown_08211E66:
    .string "Wizard{END}"

    .global gUnknown_08211E6D
gUnknown_08211E6D:
    .string "Flea{END}"

    .global gUnknown_08211E72
gUnknown_08211E72:
    .string "Avian{END}"

    .global gUnknown_08211E78
gUnknown_08211E78:
    .string "Stool{END}"

    .global gUnknown_08211E7E
gUnknown_08211E7E:
    .string "Gloom{END}"

    .global gUnknown_08211E84
gUnknown_08211E84:
    .string "Beak{END}"

    .global gUnknown_08211E89
gUnknown_08211E89:
    .string "Creep{END}"

    .global gUnknown_08211E8F
gUnknown_08211E8F:
    .string "Zard{END}"

    .global gUnknown_08211E94
gUnknown_08211E94:
    .string "Morte{END}"

    .global gUnknown_08211E9A
gUnknown_08211E9A:
    .string "Mortea{END}"

    .global gUnknown_08211EA1
gUnknown_08211EA1:
    .string "Talon{END}"

    .global gUnknown_08211EA7
gUnknown_08211EA7:
    .string "Bain{END}"

    .global gUnknown_08211EAC
gUnknown_08211EAC:
    .string "General{END}"

    .global gUnknown_08211EB4
gUnknown_08211EB4:
    .string "Gremlin{END}"

    .global gUnknown_08211EBC
gUnknown_08211EBC:
    .string "Wisp{END}"

    .global gUnknown_08211EC1
gUnknown_08211EC1:
    .string "Pog{END}"

    .global gUnknown_08211EC5
gUnknown_08211EC5:
    .string "Zombie{END}"

    .global gUnknown_08211ECC
gUnknown_08211ECC:
    .string "Slime{END}"

    .global gUnknown_08211ED2
gUnknown_08211ED2:
    .string "S.Rider{END}"

    .global gUnknown_08211EDA
gUnknown_08211EDA:
    .string "Blurb{END}"

    .global gUnknown_08211EE0
gUnknown_08211EE0:
    .string "Lancer{END}"

    .global gUnknown_08211EE7
gUnknown_08211EE7:
    .string "Bowman{END}"

    .global gUnknown_08211EEE
gUnknown_08211EEE:
    .string "Ruga{END}"

    .global gUnknown_08211EF3
gUnknown_08211EF3:
    .string "WarHog{END}"

    .global gUnknown_08211EFA
gUnknown_08211EFA:
    .string "Ameblob{END}"

    .global gUnknown_08211F02
gUnknown_08211F02:
    .string "Bulla{END}"

    .global gUnknown_08211F08
gUnknown_08211F08:
    .string "Roach{END}"

    .global gUnknown_08211F0E
gUnknown_08211F0E:
    .string "G.Fly{END}"

    .global gUnknown_08211F14
gUnknown_08211F14:
    .string "EyeSpy{END}"

    .global gUnknown_08211F1B
gUnknown_08211F1B:
    .string "Octo{END}"

    .global gUnknown_08211F20
gUnknown_08211F20:
    .string "Squid{END}"

    .global gUnknown_08211F26
gUnknown_08211F26:
    .string "SandWorm{END}"

    .global gUnknown_08211F2F
gUnknown_08211F2F:
    .string "Cloud{END}"

    .global gUnknown_08211F35
gUnknown_08211F35:
    .string "Scorp{END}"

    .global gUnknown_08211F3B
gUnknown_08211F3B:
    .string "Mage{END}"

    .global gUnknown_08211F40
gUnknown_08211F40:
    .string "Prickle{END}"

    .global gUnknown_08211F48
gUnknown_08211F48:
    .string "Archer{END}"

    .global gUnknown_08211F4F
gUnknown_08211F4F:
    .string "Fly{END}"

    .global gUnknown_08211F53
gUnknown_08211F53:
    .string "SpearMan{END}"

    .global gUnknown_08211F5C
gUnknown_08211F5C:
    .string "Creon{END}"

    .global gUnknown_08211F62
gUnknown_08211F62:
    .string "Knight{END}"

    .global gUnknown_08211F69
gUnknown_08211F69:
    .string "Mothro{END}"

    .global gUnknown_08211F70
gUnknown_08211F70:
    .string "Mote{END}"

    .global gUnknown_08211F75
gUnknown_08211F75:
    .string "Soldier{END}"

    .global gUnknown_08211F7D
gUnknown_08211F7D:
    .string "GrimFowl{END}"

    .global gUnknown_08211F86
gUnknown_08211F86:
    .string "Pincher{END}"

    .global gUnknown_08211F8E
gUnknown_08211F8E:
    .string "SlimeX{END}"

    .global gUnknown_08211F95
gUnknown_08211F95:
    .string "Myst{END}"

    .global gUnknown_08211F9A
gUnknown_08211F9A:
    .string "R.Slime{END}"

    .global gUnknown_08211FA2
gUnknown_08211FA2:
    .string "Fishy{END}"

    .global gUnknown_08211FA8
gUnknown_08211FA8:
    .string "DogFish{END}"

    .global gUnknown_08211FB0
gUnknown_08211FB0:
    .string "Midget{END}"

    .global gUnknown_08211FB7
gUnknown_08211FB7:
    .string "Tronk{END}"

    .global gUnknown_08211FBD
gUnknown_08211FBD:
    .string "SandClod{END}"

    .global gUnknown_08211FC6
gUnknown_08211FC6:
    .string "Tentacle{END}"

    .global gUnknown_08211FCF
gUnknown_08211FCF:
    .string "M.Scorp{END}"

    .global gUnknown_08211FD7
gUnknown_08211FD7:
    .string "RugaX{END}"

    .global gUnknown_08211FDD
gUnknown_08211FDD:
    .string "LancerX{END}"

    .global gUnknown_08211FE5
gUnknown_08211FE5:
    .string "BowManX{END}"

    .global gUnknown_08211FED
gUnknown_08211FED:
    .string "Wraith{END}"

    .global gUnknown_08211FF4
gUnknown_08211FF4:
    .string "RugaX{END}"

    .global gUnknown_08211FFA
gUnknown_08211FFA:
    .string "FlowerX{END}"

    .global gUnknown_08212002
gUnknown_08212002:
    .string "HornToad{END}"

    .global gUnknown_0821200B
gUnknown_0821200B:
    .string "Mote{END}"

    .global gUnknown_08212010
gUnknown_08212010:
    .string "Cerl{END}"

    .global gUnknown_08212015
gUnknown_08212015:
    .string "Mothro{END}"

    .global gUnknown_0821201C
gUnknown_0821201C:
    .string "P.Bug{END}"

    .global gUnknown_08212022
gUnknown_08212022:
    .string "Chimera{END}"

    .global gUnknown_0821202A
gUnknown_0821202A:
    .string "Fungus{END}"

    .global gUnknown_08212031
gUnknown_08212031:
    .string "Chopper{END}"

    .global gUnknown_08212039
gUnknown_08212039:
    .string "K.Roach{END}"

    .global gUnknown_08212041
gUnknown_08212041:
    .string "Phoenix{END}"

    .global gUnknown_08212049
gUnknown_08212049:
    .string "Morteo{END}"

    .global gUnknown_08212050
gUnknown_08212050:
    .string "Sorcerer{END}"

    .global gUnknown_08212059
gUnknown_08212059:
    .string "Toad{END}"

    .global gUnknown_0821205E
gUnknown_0821205E:
    .string "Rogue{END}"

    .global gUnknown_08212064
gUnknown_08212064:
    .string "Goda{END}"

    .global gUnknown_08212069
gUnknown_08212069:
    .string "Zog{END}"

    .global gUnknown_0821206D
gUnknown_0821206D:
    .string "Jade{END}"

    .global gUnknown_08212072
gUnknown_08212072:
    .string "Goddess{END}"

    .global gUnknown_0821207A
gUnknown_0821207A:
    .string "Goddess{END}"

    .global gUnknown_08212082
gUnknown_08212082:
    .string "Sara{END}"

    .global gUnknown_08212087
gUnknown_08212087:
    .string "Warlock{END}"

    .global gUnknown_0821208F
gUnknown_0821208F:
    .string "Zoom{END}"

    .global gUnknown_08212094
gUnknown_08212094:
    .string "Gargoyle{END}"

    .global gUnknown_0821209D
gUnknown_0821209D:
    .string "G.Knight{END}"

    .global gUnknown_082120A6
gUnknown_082120A6:
    .string "Shadow{END}"

    .global gUnknown_082120AD
gUnknown_082120AD:
    .string "WraithX{END}"

    .global gUnknown_082120B5
gUnknown_082120B5:
    .string "Spider{END}"

    .global gUnknown_082120BC
gUnknown_082120BC:
    .string "Blaze{END}"

    .global gUnknown_082120C2
gUnknown_082120C2:
    .string "Golem{END}"

    .global gUnknown_082120C8
gUnknown_082120C8:
    .string "E.Chest{END}"

    .global gUnknown_082120D0
gUnknown_082120D0:
    .string "Goddess{END}"

    .global gUnknown_082120D8
gUnknown_082120D8:
    .string "D.Flea{END}"

    .global gUnknown_082120DF
gUnknown_082120DF:
    .string "Crab{END}"

    .global gUnknown_082120E4
gUnknown_082120E4:
    .string "Flower{END}"

    .global gUnknown_082120EB
gUnknown_082120EB:
    .string "G.Slime{END}"

    .global gUnknown_082120F3
gUnknown_082120F3:
    .string "M.Slime{END}"

    .global gUnknown_082120FB
gUnknown_082120FB:
    .string "Buzzer{END}"

    .global gUnknown_08212102
gUnknown_08212102:
    .string "Crawler{END}"

    .global gUnknown_0821210A
gUnknown_0821210A:
    .string "Ruga{END}"

    .global gUnknown_0821210F
gUnknown_0821210F:
    .string "Ronk{END}"

    .global gUnknown_08212114
gUnknown_08212114:
    .string "DogFishX{END}"

    .global gUnknown_0821211D
gUnknown_0821211D:
    .string "BlazeX{END}"

    .global gUnknown_08212124
gUnknown_08212124:
    .string "AmeblobX{END}"

    .global gUnknown_0821212D
gUnknown_0821212D:
    .string "Nautulis{END}"

    .global gUnknown_08212136
gUnknown_08212136:
    .string "Widow{END}"

    .global gUnknown_0821213C
gUnknown_0821213C:
    .string "M.Flea{END}"

    .global gUnknown_08212143
gUnknown_08212143:
    .string "CrawlerX{END}"

    .global gUnknown_0821214C
gUnknown_0821214C:
    .string "Mimic{END}"

    .global gUnknown_08212152
gUnknown_08212152:
    .string "WarHogX{END}"

    .global gUnknown_0821215A
gUnknown_0821215A:
    .string "FireHead{END}"

    .global gUnknown_08212163
gUnknown_08212163:
    .string "Bully{END}"

    .global gUnknown_08212169
gUnknown_08212169:
    .string "Claw{END}"

    .global gUnknown_0821216E
gUnknown_0821216E:
    .string "PincherX{END}"

    .global gUnknown_08212177
gUnknown_08212177:
    .string "CreonX{END}"

    .global gUnknown_0821217E
gUnknown_0821217E:
    .string "Bain{END}"

    .global gUnknown_08212183
gUnknown_08212183:
    .string "D.Rider{END}"

    .global gUnknown_0821218B
gUnknown_0821218B:
    .string "Ghoul{END}"

    .global gUnknown_08212191
gUnknown_08212191:
    .string "Cactus{END}"

    .global gUnknown_08212198
gUnknown_08212198:
    .string "CactusX{END}"

    .global gUnknown_082121A0
gUnknown_082121A0:
    .string "ICU{END}"

    .global gUnknown_082121A4
gUnknown_082121A4:
    .string "Entity{END}"

    .global gUnknown_082121AB
gUnknown_082121AB:
    .string "D.Knight{END}"

    .global gUnknown_082121B4
gUnknown_082121B4:
    .word gUnknown_08211E4C @ 0 / 0x0
    .word gUnknown_08211E51 @ 1 / 0x1
    .word gUnknown_08211E58 @ 2 / 0x2
    .word gUnknown_08211E5F @ 3 / 0x3
    .word gUnknown_08211E66 @ 4 / 0x4
    .word gUnknown_08211E6D @ 5 / 0x5
    .word gUnknown_08211E72 @ 6 / 0x6
    .word gUnknown_08211E78 @ 7 / 0x7
    .word gUnknown_08211E7E @ 8 / 0x8
    .word gUnknown_08211E84 @ 9 / 0x9
    .word gUnknown_08211E89 @ 10 / 0xA
    .word gUnknown_08211E8F @ 11 / 0xB
    .word gUnknown_08211E94 @ 12 / 0xC
    .word gUnknown_08211E9A @ 13 / 0xD
    .word gUnknown_08211EA1 @ 14 / 0xE
    .word gUnknown_08211EA7 @ 15 / 0xF
    .word gUnknown_08211EAC @ 16 / 0x10
    .word gUnknown_08211EB4 @ 17 / 0x11
    .word gUnknown_08211EBC @ 18 / 0x12
    .word gUnknown_08211EC1 @ 19 / 0x13
    .word gUnknown_08211EC5 @ 20 / 0x14
    .word gUnknown_08211ECC @ 21 / 0x15
    .word gUnknown_08211ED2 @ 22 / 0x16
    .word gUnknown_08211EDA @ 23 / 0x17
    .word gUnknown_08211EE0 @ 24 / 0x18
    .word gUnknown_08211EE7 @ 25 / 0x19
    .word gUnknown_08211EEE @ 26 / 0x1A
    .word gUnknown_08211EF3 @ 27 / 0x1B
    .word gUnknown_08211EFA @ 28 / 0x1C
    .word gUnknown_08211F02 @ 29 / 0x1D
    .word gUnknown_08211F08 @ 30 / 0x1E
    .word gUnknown_08211F0E @ 31 / 0x1F
    .word gUnknown_08211F14 @ 32 / 0x20
    .word gUnknown_08211F1B @ 33 / 0x21
    .word gUnknown_08211F20 @ 34 / 0x22
    .word gUnknown_08211F26 @ 35 / 0x23
    .word gUnknown_08211F2F @ 36 / 0x24
    .word gUnknown_08211F35 @ 37 / 0x25
    .word gUnknown_08211F3B @ 38 / 0x26
    .word gUnknown_08211F40 @ 39 / 0x27
    .word gUnknown_08211F48 @ 40 / 0x28
    .word gUnknown_08211F4F @ 41 / 0x29
    .word gUnknown_08211F53 @ 42 / 0x2A
    .word gUnknown_08211F5C @ 43 / 0x2B
    .word gUnknown_08211F62 @ 44 / 0x2C
    .word gUnknown_08211F69 @ 45 / 0x2D
    .word gUnknown_08211F70 @ 46 / 0x2E
    .word gUnknown_08211F75 @ 47 / 0x2F
    .word gUnknown_08211F7D @ 48 / 0x30
    .word gUnknown_08211F86 @ 49 / 0x31
    .word gUnknown_08211F8E @ 50 / 0x32
    .word gUnknown_08211F95 @ 51 / 0x33
    .word gUnknown_08211F9A @ 52 / 0x34
    .word gUnknown_08211FA2 @ 53 / 0x35
    .word gUnknown_08211FA8 @ 54 / 0x36
    .word gUnknown_08211FB0 @ 55 / 0x37
    .word gUnknown_08211FB7 @ 56 / 0x38
    .word gUnknown_08211FBD @ 57 / 0x39
    .word gUnknown_08211FC6 @ 58 / 0x3A
    .word gUnknown_08211FCF @ 59 / 0x3B
    .word gUnknown_08211FD7 @ 60 / 0x3C
    .word gUnknown_08211FDD @ 61 / 0x3D
    .word gUnknown_08211FE5 @ 62 / 0x3E
    .word gUnknown_08211FED @ 63 / 0x3F
    .word gUnknown_08211FF4 @ 64 / 0x40
    .word gUnknown_08211FFA @ 65 / 0x41
    .word gUnknown_08212002 @ 66 / 0x42
    .word gUnknown_0821200B @ 67 / 0x43
    .word gUnknown_08212010 @ 68 / 0x44
    .word gUnknown_08212015 @ 69 / 0x45
    .word gUnknown_0821201C @ 70 / 0x46
    .word gUnknown_08212022 @ 71 / 0x47
    .word gUnknown_0821202A @ 72 / 0x48
    .word gUnknown_08212031 @ 73 / 0x49
    .word gUnknown_08212039 @ 74 / 0x4A
    .word gUnknown_08212041 @ 75 / 0x4B
    .word gUnknown_08212049 @ 76 / 0x4C
    .word gUnknown_08212050 @ 77 / 0x4D
    .word gUnknown_08212059 @ 78 / 0x4E
    .word gUnknown_0821205E @ 79 / 0x4F
    .word gUnknown_08212064 @ 80 / 0x50
    .word gUnknown_08212069 @ 81 / 0x51
    .word gUnknown_0821206D @ 82 / 0x52
    .word gUnknown_08212072 @ 83 / 0x53
    .word gUnknown_0821207A @ 84 / 0x54
    .word gUnknown_08212082 @ 85 / 0x55
    .word gUnknown_08212087 @ 86 / 0x56
    .word gUnknown_0821208F @ 87 / 0x57
    .word gUnknown_08212094 @ 88 / 0x58
    .word gUnknown_0821209D @ 89 / 0x59
    .word gUnknown_082120A6 @ 90 / 0x5A
    .word gUnknown_082120AD @ 91 / 0x5B
    .word gUnknown_082120B5 @ 92 / 0x5C
    .word gUnknown_082120BC @ 93 / 0x5D
    .word gUnknown_082120C2 @ 94 / 0x5E
    .word gUnknown_082120C8 @ 95 / 0x5F
    .word gUnknown_082120D0 @ 96 / 0x60
    .word gUnknown_082120D8 @ 97 / 0x61
    .word gUnknown_082120DF @ 98 / 0x62
    .word gUnknown_082120E4 @ 99 / 0x63
    .word gUnknown_082120EB @ 100 / 0x64
    .word gUnknown_082120F3 @ 101 / 0x65
    .word gUnknown_082120FB @ 102 / 0x66
    .word gUnknown_08212102 @ 103 / 0x67
    .word gUnknown_0821210A @ 104 / 0x68
    .word gUnknown_0821210F @ 105 / 0x69
    .word gUnknown_08212114 @ 106 / 0x6A
    .word gUnknown_0821211D @ 107 / 0x6B
    .word gUnknown_08212124 @ 108 / 0x6C
    .word gUnknown_0821212D @ 109 / 0x6D
    .word gUnknown_08212136 @ 110 / 0x6E
    .word gUnknown_0821213C @ 111 / 0x6F
    .word gUnknown_08212143 @ 112 / 0x70
    .word gUnknown_0821214C @ 113 / 0x71
    .word gUnknown_08212152 @ 114 / 0x72
    .word gUnknown_0821215A @ 115 / 0x73
    .word gUnknown_08212163 @ 116 / 0x74
    .word gUnknown_08212169 @ 117 / 0x75
    .word gUnknown_0821216E @ 118 / 0x76
    .word gUnknown_08212177 @ 119 / 0x77
    .word gUnknown_0821217E @ 120 / 0x78
    .word gUnknown_08212183 @ 121 / 0x79
    .word gUnknown_0821218B @ 122 / 0x7A
    .word gUnknown_08212191 @ 123 / 0x7B
    .word gUnknown_08212198 @ 124 / 0x7C
    .word gUnknown_082121A0 @ 125 / 0x7D
    .word gUnknown_082121A4 @ 126 / 0x7E
    .word gUnknown_082121AB @ 127 / 0x7F
