    .global gUnknown_08211814
gUnknown_08211814:
    .string "When the Dragon Family was\n"
    .string "at the peak of its power,\n"
    .string "a goddess of desire appeared.\n"
    .string "\n"
    .string "The goddess, Tyr,\n"
    .string "granted wishes. The Dragons\n"
    .string "fought each other for\n"
    .string "her power.{END}"

    .global gUnknown_082118B7
gUnknown_082118B7:
    .string "Tyr encouraged the fighting\n"
    .string "and watched the war between\n"
    .string "the Dragons escalate.\n"
    .string "\n"
    .string "When the world was at\n"
    .string "the brink of destruction,\n"
    .string "a warrior stepped forward.{END}"

    .global gUnknown_08211951
gUnknown_08211951:
    .string "The warrior battled Tyr\n"
    .string "with his 7 companions and\n"
    .string "locked her up using 6 keys.\n"
    .string "\n"
    .string "These “Goddess keys“\n"
    .string "were scattered throughout\n"
    .string "the world and hidden away.{END}"

    .global gUnknown_082119EA
gUnknown_082119EA:
    .string "The Light Dragons balanced\n"
    .string "the power of the family\n"
    .string "and peace reigned again.{END}"

    .global gUnknown_08211A36
gUnknown_08211A36:
    .string "People live and die,\n"
    .string "as countless as the\n"
    .string "stars in the sky,\n"
    .string "as fleeting as foam\n"
    .string "in water{0xF7}{0xF7}{0xF7}{END}"

    .global gUnknown_08211A91
gUnknown_08211A91:
    .string "Why are we brought\n"
    .string "into the world,\n"
    .string "only to depart so\n"
    .string "quickly?{END}"

    .global gUnknown_08211ACF
gUnknown_08211ACF:
    .string "On a cosmic scale,\n"
    .string "our lives flash by in\n"
    .string "the blink of an eye.{END}"

    .global gUnknown_08211B0D
gUnknown_08211B0D:
    .string "The Dragon Clan built\n"
    .string "a mighty empire,\n"
    .string "then faded fast, like\n"
    .string "a falling star.{END}"

    .global gUnknown_08211B5A
gUnknown_08211B5A:
    .string "During their short reign,\n"
    .string "the Dragons fought\n"
    .string "meaningless battles\n"
    .string "in pursuit of empty\n"
    .string "dreams.{END}"

    .global gUnknown_08211BB7
gUnknown_08211BB7:
    .string "Now, an ominous force\n"
    .string "emerges and to\n"
    .string "repeat the cycle.{END}"

    .global gUnknown_08211BEE
gUnknown_08211BEE:
    .string "This new menace is\n"
    .string "the clan of Dark\n"
    .string "Dragons.{END}"

    .global gUnknown_08211C1B
gUnknown_08211C1B:
    .string "Forgetting that the\n"
    .string "Dragons once laid\n"
    .string "waste to the land{0xF7}{0xF7}{0xF7}{END}"

    .global gUnknown_08211C56
gUnknown_08211C56:
    .string "The Dark Dragon Clan\n"
    .string "again plunges into\n"
    .string "the world of chaos.{END}"

    .global gUnknown_08211C92
gUnknown_08211C92:
    .string "Using new powers,\n"
    .string "given by a mysterious\n"
    .string "goddess, the Dragons\n"
    .string "engage in global conquest.{END}"

    .global gUnknown_08211CEA
gUnknown_08211CEA:
    .string "Who is this dark power\n"
    .string "that grants evil\n"
    .string "wishes?{END}"

    .global gUnknown_08211D1A
gUnknown_08211D1A:
    .string "Will the Light Dragons\n"
    .string "emerge to bring\n"
    .string "peace to the world?{END}"

    .global gUnknown_08211D55
gUnknown_08211D55:
    .string "The Dark Dragons\n"
    .string "press on.{END}"

    .global gUnknown_08211D70
gUnknown_08211D70:
    .string "Before the world is\n"
    .string "theirs{0xF7}{0xF7}{0xF7}{END}"

    .global gUnknown_08211D8E
gUnknown_08211D8E:
    .string "Before the goddess is\n"
    .string "revived{0xF7}{0xF7}{0xF7}{END}"

    .global gUnknown_08211DAF
gUnknown_08211DAF:
    .string "The Light Dragons must\n"
    .string "fight back!{END}"

    .align 2
    .global gUnknown_08211DD4
gUnknown_08211DD4:
    .word gUnknown_08211814 @ 0 / 0x0
    .word gUnknown_082118B7 @ 1 / 0x1
    .word gUnknown_08211951 @ 2 / 0x2
    .word gUnknown_082119EA @ 3 / 0x3
    .word gUnknown_08211A36 @ 4 / 0x4
    .word gUnknown_08211A91 @ 5 / 0x5
    .word gUnknown_08211ACF @ 6 / 0x6
    .word gUnknown_08211B0D @ 7 / 0x7
    .word gUnknown_08211B5A @ 8 / 0x8
    .word gUnknown_08211BB7 @ 9 / 0x9
    .word gUnknown_08211BEE @ 10 / 0xA
    .word gUnknown_08211C1B @ 11 / 0xB
    .word gUnknown_08211C56 @ 12 / 0xC
    .word gUnknown_08211C92 @ 13 / 0xD
    .word gUnknown_08211CEA @ 14 / 0xE
    .word gUnknown_08211D1A @ 15 / 0xF
    .word gUnknown_08211D55 @ 16 / 0x10
    .word gUnknown_08211D70 @ 17 / 0x11
    .word gUnknown_08211D8E @ 18 / 0x12
    .word gUnknown_08211DAF @ 19 / 0x13
