    .global gUnknown_08212F4C
gUnknown_08212F4C:
    .string "70GP{END}"

    .global gUnknown_08212F51
gUnknown_08212F51:
    .string "150GP{END}"

    .global gUnknown_08212F57
gUnknown_08212F57:
    .string "300GP{END}"

    .global gUnknown_08212F5D
gUnknown_08212F5D:
    .string "650GP{END}"

    .global gUnknown_08212F63
gUnknown_08212F63:
    .string "900GP{END}"

    .global gUnknown_08212F69
gUnknown_08212F69:
    .string "1200GP{END}"

    .global gUnknown_08212F70
gUnknown_08212F70:
    .string "2000GP{END}"

    .global gUnknown_08212F77
gUnknown_08212F77:
    .string "3000GP{END}"

    .global gUnknown_08212F7E
gUnknown_08212F7E:
    .string "Herb{END}"

    .global gUnknown_08212F83
gUnknown_08212F83:
    .string "Cure{END}"

    .global gUnknown_08212F88
gUnknown_08212F88:
    .string "Antdt{END}"

    .global gUnknown_08212F8E
gUnknown_08212F8E:
    .string "Acorn{END}"

    .global gUnknown_08212F94
gUnknown_08212F94:
    .string "M.Drop{END}"

    .global gUnknown_08212F9B
gUnknown_08212F9B:
    .string "T.Drop{END}"

    .global gUnknown_08212FA2
gUnknown_08212FA2:
    .string "Charm{END}"

    .global gUnknown_08212FA8
gUnknown_08212FA8:
    .string "Life2{END}"

    .global gUnknown_08212FAE
gUnknown_08212FAE:
    .string "Mrbl1{END}"

    .global gUnknown_08212FB4
gUnknown_08212FB4:
    .string "Mrbl2{END}"

    .global gUnknown_08212FBA
gUnknown_08212FBA:
    .string "Mrbl3{END}"

    .global gUnknown_08212FC0
gUnknown_08212FC0:
    .string "Whskrs{END}"

    .global gUnknown_08212FC7
gUnknown_08212FC7:
    .string "Worm{END}"

    .global gUnknown_08212FCC
gUnknown_08212FCC:
    .string "Worm2{END}"

    .global gUnknown_08212FD2
gUnknown_08212FD2:
    .string "Shrimp{END}"

    .global gUnknown_08212FD9
gUnknown_08212FD9:
    .string "Urchin{END}"

    .global gUnknown_08212FE0
gUnknown_08212FE0:
    .string "Shell{END}"

    .global gUnknown_08212FE6
gUnknown_08212FE6:
    .string "Apple{END}"

    .global gUnknown_08212FEC
gUnknown_08212FEC:
    .string "ProtnA{END}"

    .global gUnknown_08212FF3
gUnknown_08212FF3:
    .string "Antler{END}"

    .global gUnknown_08212FFA
gUnknown_08212FFA:
    .string "Wmeat{END}"

    .global gUnknown_08213000
gUnknown_08213000:
    .string "Life{END}"

    .global gUnknown_08213005
gUnknown_08213005:
    .string "Nails{END}"

    .global gUnknown_0821300B
gUnknown_0821300B:
    .string "Meat{END}"

    .global gUnknown_08213010
gUnknown_08213010:
    .string "B.Stn{END}"

    .global gUnknown_08213016
gUnknown_08213016:
    .string "F.Stn{END}"

    .global gUnknown_0821301C
gUnknown_0821301C:
    .string "C.Stn{END}"

    .global gUnknown_08213022
gUnknown_08213022:
    .string "Smoke{END}"

    .global gUnknown_08213028
gUnknown_08213028:
    .string "DkKiss{END}"

    .global gUnknown_0821302F
gUnknown_0821302F:
    .string "Cure2{END}"

    .global gUnknown_08213035
gUnknown_08213035:
    .string "ProtnB{END}"

    .global gUnknown_0821303C
gUnknown_0821303C:
    .string "Sash{END}"

    .global gUnknown_08213041
gUnknown_08213041:
    .string "W.Ptn{END}"

    .global gUnknown_08213047
gUnknown_08213047:
    .string "S.Ptn{END}"

    .global gUnknown_0821304D
gUnknown_0821304D:
    .string "HrGlas{END}"

    .global gUnknown_08213054
gUnknown_08213054:
    .string "ExpBug{END}"

    .global gUnknown_0821305B
gUnknown_0821305B:
    .string "Slab{END}"

    .global gUnknown_08213060
gUnknown_08213060:
    .string "Lifter{END}"

    .global gUnknown_08213067
gUnknown_08213067:
    .string "E.Key{END}"

    .global gUnknown_0821306D
gUnknown_0821306D:
    .string "ClmWtr{END}"

    .global gUnknown_08213074
gUnknown_08213074:
    .string "Coach{END}"

    .global gUnknown_0821307A
gUnknown_0821307A:
    .string "Clog{END}"

    .global gUnknown_0821307F
gUnknown_0821307F:
    .string "A.Ptn{END}"

    .global gUnknown_08213085
gUnknown_08213085:
    .string "L.Ptn{END}"

    .global gUnknown_0821308B
gUnknown_0821308B:
    .string "V.Ptn{END}"

    .global gUnknown_08213091
gUnknown_08213091:
    .string "DrSoul{END}"

    .global gUnknown_08213098
gUnknown_08213098:
    .string "DrWarp{END}"

    .global gUnknown_0821309F
gUnknown_0821309F:
    .string "PlceBo{END}"

    .global gUnknown_082130A6
gUnknown_082130A6:
    .string "Remedy{END}"

    .global gUnknown_082130AD
gUnknown_082130AD:
    .string "WtrJr{END}"

    .global gUnknown_082130B3
gUnknown_082130B3:
    .string "Saw{END}"

    .global gUnknown_082130B7
gUnknown_082130B7:
    .string "Tablet{END}"

    .global gUnknown_082130BE
gUnknown_082130BE:
    .string "Ring{END}"

    .global gUnknown_082130C3
gUnknown_082130C3:
    .string "WtrJr'{END}"

    .global gUnknown_082130CA
gUnknown_082130CA:
    .string "KngKey{END}"

    .global gUnknown_082130D1
gUnknown_082130D1:
    .string "Paper{END}"

    .global gUnknown_082130D7
gUnknown_082130D7:
    .string "Oath{END}"

    .global gUnknown_082130DC
gUnknown_082130DC:
    .string "Pouch{END}"

    .global gUnknown_082130E2
gUnknown_082130E2:
    .string "GnPwdr{END}"

    .global gUnknown_082130E9
gUnknown_082130E9:
    .string "LtKey{END}"

    .global gUnknown_082130EF
gUnknown_082130EF:
    .string "DkKey{END}"

    .global gUnknown_082130F5
gUnknown_082130F5:
    .string "Mirror{END}"

    .global gUnknown_082130FC
gUnknown_082130FC:
    .string "Book{END}"

    .global gUnknown_08213101
gUnknown_08213101:
    .string "Srdine{END}"

    .global gUnknown_08213108
gUnknown_08213108:
    .string "Mackrl{END}"

    .global gUnknown_0821310F
gUnknown_0821310F:
    .string "Sole{END}"

    .global gUnknown_08213114
gUnknown_08213114:
    .string "Trout{END}"

    .global gUnknown_0821311A
gUnknown_0821311A:
    .string "C.Fsh{END}"

    .global gUnknown_08213120
gUnknown_08213120:
    .string "Snapr{END}"

    .global gUnknown_08213126
gUnknown_08213126:
    .string "Tuna{END}"

    .global gUnknown_0821312B
gUnknown_0821312B:
    .string "Puffer{END}"

    .global gUnknown_08213132
gUnknown_08213132:
    .string "Rod1{END}"

    .global gUnknown_08213137
gUnknown_08213137:
    .string "Rod2{END}"

    .global gUnknown_0821313C
gUnknown_0821313C:
    .string "Rod3{END}"

    .global gUnknown_08213141
gUnknown_08213141:
    .string "Rod4{END}"

    .global gUnknown_08213146
gUnknown_08213146:
    .string "Rod5{END}"

    .global gUnknown_0821314B
gUnknown_0821314B:
    .string "I.Ore{END}"

    .global gUnknown_08213151
gUnknown_08213151:
    .string "Key{END}"

    .global gUnknown_08213155
gUnknown_08213155:
    .string "Vitamn{END}"

    .global gUnknown_0821315C
gUnknown_0821315C:
    .string "Statue{END}"

    .global gUnknown_08213163
gUnknown_08213163:
    .string "OldEgg{END}"

    .global gUnknown_0821316A
gUnknown_0821316A:
    .string "Goods{END}"

    .global gUnknown_08213170
gUnknown_08213170:
    .string "Egg{END}"

    .global gUnknown_08213174
gUnknown_08213174:
    .string "Sphere{END}"

    .global gUnknown_0821317B
gUnknown_0821317B:
    .string "Gills{END}"

    .global gUnknown_08213181
gUnknown_08213181:
    .string "G.Bar{END}"

    .global gUnknown_08213187
gUnknown_08213187:
    .string "Icicle{END}"

    .global gUnknown_0821318E
gUnknown_0821318E:
    .string "Fife{END}"

    .global gUnknown_08213193
gUnknown_08213193:
    .string "Pass{END}"

    .global gUnknown_08213198
gUnknown_08213198:
    .string "B.Part{END}"

    .global gUnknown_0821319F
gUnknown_0821319F:
    .string "Parts{END}"

    .global gUnknown_082131A5
gUnknown_082131A5:
    .string "D.Hrt{END}"

    .global gUnknown_082131AB
gUnknown_082131AB:
    .string "Map{END}"

    .global gUnknown_082131AF
gUnknown_082131AF:
    .string "List{END}"

    .global gUnknown_082131B4
gUnknown_082131B4:
    .string "Wtzit{END}"

    .global gUnknown_082131BA
gUnknown_082131BA:
    .string "Note1{END}"

    .global gUnknown_082131C0
gUnknown_082131C0:
    .string "Note2{END}"

    .global gUnknown_082131C6
gUnknown_082131C6:
    .string "I.Claw{END}"

    .global gUnknown_082131CD
gUnknown_082131CD:
    .string "TmKey{END}"

    .global gUnknown_082131D3
gUnknown_082131D3:
    .string "B.Rang{END}"

    .global gUnknown_082131DA
gUnknown_082131DA:
    .string "SkyKey{END}"

    .global gUnknown_082131E1
gUnknown_082131E1:
    .string "Cowl{END}"

    .global gUnknown_082131E6
gUnknown_082131E6:
    .string "Bolster{END}"

    .global gUnknown_082131EE
gUnknown_082131EE:
    .string "Maestro{END}"

    .global gUnknown_082131F6
gUnknown_082131F6:
    .string "G.Fly{END}"

    .global gUnknown_082131FC
gUnknown_082131FC:
    .string "Oil{END}"

    .global gUnknown_08213200
gUnknown_08213200:
    .string "M.Cura{END}"

    .global gUnknown_08213207
gUnknown_08213207:
    .string "Melon{END}"

    .global gUnknown_0821320D
gUnknown_0821320D:
    .string "Fruit{END}"

    .global gUnknown_08213213
gUnknown_08213213:
    .string "P.Fish{END}"

    .global gUnknown_0821321A
gUnknown_0821321A:
    .string "Root{END}"

    .global gUnknown_0821321F
gUnknown_0821321F:
    .string "C.Nut{END}"

    .global gUnknown_08213225
gUnknown_08213225:
    .string "W.Ant{END}"

    .global gUnknown_0821322B
gUnknown_0821322B:
    .string "Tonic{END}"

    .global gUnknown_08213231
gUnknown_08213231:
    .string "Herb  X9{END}"

    .global gUnknown_0821323A
gUnknown_0821323A:
    .string "Antd  X9{END}"

    .global gUnknown_08213243
gUnknown_08213243:
    .string "Drop  X9{END}"

    .global gUnknown_0821324C
gUnknown_0821324C:
    .string "Chrm  X9{END}"

    .global gUnknown_08213255
gUnknown_08213255:
    .string "Cure  X9{END}"

    .global gUnknown_0821325E
gUnknown_0821325E:
    .string "Acrn  X9{END}"

    @Unreferenced string
    .global gUnknown_08213267
gUnknown_08213267:
    .string "{END}"

    .global gUnknown_08213268
gUnknown_08213268:
    .word gUnknown_08212F4C @ 0 / 0x0
    .word gUnknown_08212F51 @ 1 / 0x1
    .word gUnknown_08212F57 @ 2 / 0x2
    .word gUnknown_08212F5D @ 3 / 0x3
    .word gUnknown_08212F63 @ 4 / 0x4
    .word gUnknown_08212F69 @ 5 / 0x5
    .word gUnknown_08212F70 @ 6 / 0x6
    .word gUnknown_08212F77 @ 7 / 0x7
    .word gUnknown_08212F7E @ 8 / 0x8
    .word gUnknown_08212F83 @ 9 / 0x9
    .word gUnknown_08212F88 @ 10 / 0xA
    .word gUnknown_08212F8E @ 11 / 0xB
    .word gUnknown_08212F94 @ 12 / 0xC
    .word gUnknown_08212F9B @ 13 / 0xD
    .word gUnknown_08212FA2 @ 14 / 0xE
    .word gUnknown_08212FA8 @ 15 / 0xF
    .word gUnknown_08212FAE @ 16 / 0x10
    .word gUnknown_08212FB4 @ 17 / 0x11
    .word gUnknown_08212FBA @ 18 / 0x12
    .word gUnknown_08212FC0 @ 19 / 0x13
    .word gUnknown_08212FC7 @ 20 / 0x14
    .word gUnknown_08212FCC @ 21 / 0x15
    .word gUnknown_08212FD2 @ 22 / 0x16
    .word gUnknown_08212FD9 @ 23 / 0x17
    .word gUnknown_08212FE0 @ 24 / 0x18
    .word gUnknown_08212FE6 @ 25 / 0x19
    .word gUnknown_08212FEC @ 26 / 0x1A
    .word gUnknown_08212FF3 @ 27 / 0x1B
    .word gUnknown_08212FFA @ 28 / 0x1C
    .word gUnknown_08213000 @ 29 / 0x1D
    .word gUnknown_08213005 @ 30 / 0x1E
    .word gUnknown_0821300B @ 31 / 0x1F
    .word gUnknown_08213010 @ 32 / 0x20
    .word gUnknown_08213016 @ 33 / 0x21
    .word gUnknown_0821301C @ 34 / 0x22
    .word gUnknown_08213022 @ 35 / 0x23
    .word gUnknown_08213028 @ 36 / 0x24
    .word gUnknown_0821302F @ 37 / 0x25
    .word gUnknown_08213035 @ 38 / 0x26
    .word gUnknown_0821303C @ 39 / 0x27
    .word gUnknown_08213041 @ 40 / 0x28
    .word gUnknown_08213047 @ 41 / 0x29
    .word gUnknown_0821304D @ 42 / 0x2A
    .word gUnknown_08213054 @ 43 / 0x2B
    .word gUnknown_0821305B @ 44 / 0x2C
    .word gUnknown_08213060 @ 45 / 0x2D
    .word gUnknown_08213067 @ 46 / 0x2E
    .word gUnknown_0821306D @ 47 / 0x2F
    .word gUnknown_08213074 @ 48 / 0x30
    .word gUnknown_0821307A @ 49 / 0x31
    .word gUnknown_0821307F @ 50 / 0x32
    .word gUnknown_08213085 @ 51 / 0x33
    .word gUnknown_0821308B @ 52 / 0x34
    .word gUnknown_08213091 @ 53 / 0x35
    .word gUnknown_08213098 @ 54 / 0x36
    .word gUnknown_0821309F @ 55 / 0x37
    .word gUnknown_082130A6 @ 56 / 0x38
    .word gUnknown_082130AD @ 57 / 0x39
    .word gUnknown_082130B3 @ 58 / 0x3A
    .word gUnknown_082130B7 @ 59 / 0x3B
    .word gUnknown_082130BE @ 60 / 0x3C
    .word gUnknown_082130C3 @ 61 / 0x3D
    .word gUnknown_082130CA @ 62 / 0x3E
    .word gUnknown_082130D1 @ 63 / 0x3F
    .word gUnknown_082130D7 @ 64 / 0x40
    .word gUnknown_082130DC @ 65 / 0x41
    .word gUnknown_082130E2 @ 66 / 0x42
    .word gUnknown_082130E9 @ 67 / 0x43
    .word gUnknown_082130EF @ 68 / 0x44
    .word gUnknown_082130F5 @ 69 / 0x45
    .word gUnknown_082130FC @ 70 / 0x46
    .word gUnknown_08213101 @ 71 / 0x47
    .word gUnknown_08213108 @ 72 / 0x48
    .word gUnknown_0821310F @ 73 / 0x49
    .word gUnknown_08213114 @ 74 / 0x4A
    .word gUnknown_0821311A @ 75 / 0x4B
    .word gUnknown_08213120 @ 76 / 0x4C
    .word gUnknown_08213126 @ 77 / 0x4D
    .word gUnknown_0821312B @ 78 / 0x4E
    .word gUnknown_08213132 @ 79 / 0x4F
    .word gUnknown_08213137 @ 80 / 0x50
    .word gUnknown_0821313C @ 81 / 0x51
    .word gUnknown_08213141 @ 82 / 0x52
    .word gUnknown_08213146 @ 83 / 0x53
    .word gUnknown_0821314B @ 84 / 0x54
    .word gUnknown_08213151 @ 85 / 0x55
    .word gUnknown_08213155 @ 86 / 0x56
    .word gUnknown_0821315C @ 87 / 0x57
    .word gUnknown_08213163 @ 88 / 0x58
    .word gUnknown_0821316A @ 89 / 0x59
    .word gUnknown_08213170 @ 90 / 0x5A
    .word gUnknown_08213174 @ 91 / 0x5B
    .word gUnknown_0821317B @ 92 / 0x5C
    .word gUnknown_08213181 @ 93 / 0x5D
    .word gUnknown_08213187 @ 94 / 0x5E
    .word gUnknown_0821318E @ 95 / 0x5F
    .word gUnknown_08213193 @ 96 / 0x60
    .word gUnknown_08213198 @ 97 / 0x61
    .word gUnknown_0821319F @ 98 / 0x62
    .word gUnknown_082131A5 @ 99 / 0x63
    .word gUnknown_082131AB @ 100 / 0x64
    .word gUnknown_082131AF @ 101 / 0x65
    .word gUnknown_082131B4 @ 102 / 0x66
    .word gUnknown_082131BA @ 103 / 0x67
    .word gUnknown_082131C0 @ 104 / 0x68
    .word gUnknown_082131C6 @ 105 / 0x69
    .word gUnknown_082131CD @ 106 / 0x6A
    .word gUnknown_082131D3 @ 107 / 0x6B
    .word gUnknown_082131DA @ 108 / 0x6C
    .word gUnknown_082131E1 @ 109 / 0x6D
    .word gUnknown_082131E6 @ 110 / 0x6E
    .word gUnknown_082131EE @ 111 / 0x6F
    .word gUnknown_082131F6 @ 112 / 0x70
    .word gUnknown_082131FC @ 113 / 0x71
    .word gUnknown_08213200 @ 114 / 0x72
    .word gUnknown_08213207 @ 115 / 0x73
    .word gUnknown_0821320D @ 116 / 0x74
    .word gUnknown_08213213 @ 117 / 0x75
    .word gUnknown_0821321A @ 118 / 0x76
    .word gUnknown_0821321F @ 119 / 0x77
    .word gUnknown_08213225 @ 120 / 0x78
    .word gUnknown_0821322B @ 121 / 0x79
    .word gUnknown_08213231 @ 122 / 0x7A
    .word gUnknown_0821323A @ 123 / 0x7B
    .word gUnknown_08213243 @ 124 / 0x7C
    .word gUnknown_0821324C @ 125 / 0x7D
    .word gUnknown_08213255 @ 126 / 0x7E
    .word gUnknown_0821325E @ 127 / 0x7F
