    .global gUnknown_08212C04
gUnknown_08212C04:
    .string "Where?{END}"

    .global gUnknown_08212C0B
gUnknown_08212C0B:
    .string "Drogen{END}"

    .global gUnknown_08212C12
gUnknown_08212C12:
    .string "Nanai{END}"

    .global gUnknown_08212C18
gUnknown_08212C18:
    .string "Winlan{END}"

    .global gUnknown_08212C1F
gUnknown_08212C1F:
    .string "Romero{END}"

    .global gUnknown_08212C26
gUnknown_08212C26:
    .string "Gust{END}"

    .global gUnknown_08212C2B
gUnknown_08212C2B:
    .string "Camlon{END}"

    .global gUnknown_08212C32
gUnknown_08212C32:
    .string "Nada{END}"

    .global gUnknown_08212C37
gUnknown_08212C37:
    .string "Tantar{END}"

    .global gUnknown_08212C3E
gUnknown_08212C3E:
    .string "Tuntar{END}"

    .global gUnknown_08212C45
gUnknown_08212C45:
    .string "Agua{END}"

    .global gUnknown_08212C4A
gUnknown_08212C4A:
    .string "Auria{END}"

    .global gUnknown_08212C50
gUnknown_08212C50:
    .string "Bleak{END}"

    .global gUnknown_08212C56
gUnknown_08212C56:
    .string "Arad{END}"

    .global gUnknown_08212C5B
gUnknown_08212C5B:
    .string "Spring{END}"

    .global gUnknown_08212C62
gUnknown_08212C62:
    .string "Tunlan{END}"

    .global gUnknown_08212C69
gUnknown_08212C69:
    .string "Gant{END}"

    .global gUnknown_08212C6E
gUnknown_08212C6E:
    .string "Scande{END}"

    .global gUnknown_08212C75
gUnknown_08212C75:
    .string "Carmen{END}"

    .global gUnknown_08212C7C
gUnknown_08212C7C:
    .string "Gramor{END}"

    .global gUnknown_08212C83
gUnknown_08212C83:
    .string "Wisdon{END}"

    .global gUnknown_08212C8A
gUnknown_08212C8A:
    .string "Karma{END}"

    .global gUnknown_08212C90
gUnknown_08212C90:
    .string "Prima{END}"

    .global gUnknown_08212C96
gUnknown_08212C96:
    .string "Krypt{END}"

    .global gUnknown_08212C9C
gUnknown_08212C9C:
    .string "Nabal{END}"

    .global gUnknown_08212CA2
gUnknown_08212CA2:
    .string "Tock{END}"

    .global gUnknown_08212CA7
gUnknown_08212CA7:
    .string "Spyre{END}"

    .global gUnknown_08212CAD
gUnknown_08212CAD:
    .string "Obelisk{END}"

    .global gUnknown_08212CB5
gUnknown_08212CB5:
    .string "Pagoda{END}"

    .global gUnknown_08212CBC
gUnknown_08212CBC:
    .string "Dragon Shrne{END}"

    .global gUnknown_08212CC9
gUnknown_08212CC9:
    .string "Dragon Tmple{END}"

    .global gUnknown_08212CD6
gUnknown_08212CD6:
    .string "Ramui Woods{END}"

    .global gUnknown_08212CE2
gUnknown_08212CE2:
    .string "Aura Cave{END}"

    .global gUnknown_08212CEC
gUnknown_08212CEC:
    .string "Lament Woods{END}"

    .global gUnknown_08212CF9
gUnknown_08212CF9:
    .string "Gaia Temple{END}"

    .global gUnknown_08212D05
gUnknown_08212D05:
    .string "Lake Cave{END}"

    .global gUnknown_08212D0F
gUnknown_08212D0F:
    .string "Lake Shrine{END}"

    .global gUnknown_08212D1B
gUnknown_08212D1B:
    .string "Cape Cave{END}"

    .global gUnknown_08212D25
gUnknown_08212D25:
    .string "Ease Cave{END}"

    .global gUnknown_08212D2F
gUnknown_08212D2F:
    .string "GrimFowl Wds{END}"

    .global gUnknown_08212D3C
gUnknown_08212D3C:
    .string "Dark D. Fort{END}"

    .global gUnknown_08212D49
gUnknown_08212D49:
    .string "Secret Base{END}"

    .global gUnknown_08212D55
gUnknown_08212D55:
    .string "The Giant{END}"

    .global gUnknown_08212D5F
gUnknown_08212D5F:
    .string "Dark D. Ship{END}"

    .global gUnknown_08212D6C
gUnknown_08212D6C:
    .string "L & D Cave{END}"

    .global gUnknown_08212D77
gUnknown_08212D77:
    .string "Hidden Fort{END}"

    .global gUnknown_08212D83
gUnknown_08212D83:
    .string "L & D Tower{END}"

    .global gUnknown_08212D8F
gUnknown_08212D8F:
    .string "Sea Volcano{END}"

    .global gUnknown_08212D9B
gUnknown_08212D9B:
    .string "Devil Tower{END}"

    .global gUnknown_08212DA7
gUnknown_08212DA7:
    .string "Wilderness{END}"

    .global gUnknown_08212DB2
gUnknown_08212DB2:
    .string "Mare Tower{END}"

    .global gUnknown_08212DBD
gUnknown_08212DBD:
    .string "Fairy Woods{END}"

    .global gUnknown_08212DC9
gUnknown_08212DC9:
    .string "Mare Town{END}"

    .global gUnknown_08212DD3
gUnknown_08212DD3:
    .string "Lab.{END}"

    .global gUnknown_08212DD8
gUnknown_08212DD8:
    .string "Mouse Hole{END}"

    .global gUnknown_08212DE3
gUnknown_08212DE3:
    .string "Frog Cave{END}"

    .global gUnknown_08212DED
gUnknown_08212DED:
    .string "South Cave{END}"

    .global gUnknown_08212DF8
gUnknown_08212DF8:
    .string "South Castle{END}"

    .global gUnknown_08212E05
gUnknown_08212E05:
    .string "Dream Town{END}"

    .global gUnknown_08212E10
gUnknown_08212E10:
    .string "W-Man Home{END}"

    .global gUnknown_08212E1B
gUnknown_08212E1B:
    .string "I-Woman Home{END}"

    .global gUnknown_08212E28
gUnknown_08212E28:
    .string "Desert Cave{END}"

    .global gUnknown_08212E34
gUnknown_08212E34:
    .string "Winter Cave{END}"

    .global gUnknown_08212E40
gUnknown_08212E40:
    .string "Hidden Room{END}"

    .global gUnknown_08212E4C
gUnknown_08212E4C:
    .word gUnknown_08212C04 @ 0 / 0x0
    .word gUnknown_08212C0B @ 1 / 0x1
    .word gUnknown_08212C12 @ 2 / 0x2
    .word gUnknown_08212C18 @ 3 / 0x3
    .word gUnknown_08212C1F @ 4 / 0x4
    .word gUnknown_08212C26 @ 5 / 0x5
    .word gUnknown_08212C2B @ 6 / 0x6
    .word gUnknown_08212C32 @ 7 / 0x7
    .word gUnknown_08212C37 @ 8 / 0x8
    .word gUnknown_08212C3E @ 9 / 0x9
    .word gUnknown_08212C45 @ 10 / 0xA
    .word gUnknown_08212C4A @ 11 / 0xB
    .word gUnknown_08212C50 @ 12 / 0xC
    .word gUnknown_08212C56 @ 13 / 0xD
    .word gUnknown_08212C5B @ 14 / 0xE
    .word gUnknown_08212C62 @ 15 / 0xF
    .word gUnknown_08212C69 @ 16 / 0x10
    .word gUnknown_08212C6E @ 17 / 0x11
    .word gUnknown_08212C75 @ 18 / 0x12
    .word gUnknown_08212C7C @ 19 / 0x13
    .word gUnknown_08212C83 @ 20 / 0x14
    .word gUnknown_08212C8A @ 21 / 0x15
    .word gUnknown_08212C90 @ 22 / 0x16
    .word gUnknown_08212C96 @ 23 / 0x17
    .word gUnknown_08212C9C @ 24 / 0x18
    .word gUnknown_08212CA2 @ 25 / 0x19
    .word gUnknown_08212CA7 @ 26 / 0x1A
    .word gUnknown_08212CAD @ 27 / 0x1B
    .word gUnknown_08212CB5 @ 28 / 0x1C
    .word gUnknown_08212CBC @ 29 / 0x1D
    .word gUnknown_08212CC9 @ 30 / 0x1E
    .word gUnknown_08212CD6 @ 31 / 0x1F
    .word gUnknown_08212CE2 @ 32 / 0x20
    .word gUnknown_08212CEC @ 33 / 0x21
    .word gUnknown_08212CF9 @ 34 / 0x22
    .word gUnknown_08212D05 @ 35 / 0x23
    .word gUnknown_08212D0F @ 36 / 0x24
    .word gUnknown_08212D1B @ 37 / 0x25
    .word gUnknown_08212D25 @ 38 / 0x26
    .word gUnknown_08212D2F @ 39 / 0x27
    .word gUnknown_08212D3C @ 40 / 0x28
    .word gUnknown_08212D49 @ 41 / 0x29
    .word gUnknown_08212D55 @ 42 / 0x2A
    .word gUnknown_08212D5F @ 43 / 0x2B
    .word gUnknown_08212D6C @ 44 / 0x2C
    .word gUnknown_08212D77 @ 45 / 0x2D
    .word gUnknown_08212D83 @ 46 / 0x2E
    .word gUnknown_08212D8F @ 47 / 0x2F
    .word gUnknown_08212D9B @ 48 / 0x30
    .word gUnknown_08212DA7 @ 49 / 0x31
    .word gUnknown_08212DB2 @ 50 / 0x32
    .word gUnknown_08212DBD @ 51 / 0x33
    .word gUnknown_08212DC9 @ 52 / 0x34
    .word gUnknown_08212DD3 @ 53 / 0x35
    .word gUnknown_08212DD8 @ 54 / 0x36
    .word gUnknown_08212DE3 @ 55 / 0x37
    .word gUnknown_08212DED @ 56 / 0x38
    .word gUnknown_08212DF8 @ 57 / 0x39
    .word gUnknown_08212E05 @ 58 / 0x3A
    .word gUnknown_08212E10 @ 59 / 0x3B
    .word gUnknown_08212E1B @ 60 / 0x3C
    .word gUnknown_08212E28 @ 61 / 0x3D
    .word gUnknown_08212E34 @ 62 / 0x3E
    .word gUnknown_08212E40 @ 63 / 0x3F
