    .global gUnknown_08213FE8
gUnknown_08213FE8:
    .string "Cura1{END}"

    .global gUnknown_08213FEE
gUnknown_08213FEE:
    .string "Fort{END}"

    .global gUnknown_08213FF3
gUnknown_08213FF3:
    .string "Idle{END}"

    .global gUnknown_08213FF8
gUnknown_08213FF8:
    .string "Lk-Up{END}"

    .global gUnknown_08213FFE
gUnknown_08213FFE:
    .string "Atk-Up{END}"

    .global gUnknown_08214005
gUnknown_08214005:
    .string "Cura2{END}"

    .global gUnknown_0821400B
gUnknown_0821400B:
    .string "Hold{END}"

    .global gUnknown_08214010
gUnknown_08214010:
    .string "Ag-Up{END}"

    .global gUnknown_08214016
gUnknown_08214016:
    .string "Zom1{END}"

    .global gUnknown_0821401B
gUnknown_0821401B:
    .string "Cura3{END}"

    .global gUnknown_08214021
gUnknown_08214021:
    .string "Renew{END}"

    .global gUnknown_08214027
gUnknown_08214027:
    .string "Heal{END}"

    .global gUnknown_0821402C
gUnknown_0821402C:
    .string "Shield{END}"

    .global gUnknown_08214033
gUnknown_08214033:
    .string "Cura4{END}"

    .global gUnknown_08214039
gUnknown_08214039:
    .string "Zom2{END}"

    .global gUnknown_0821403E
gUnknown_0821403E:
    .string "FortX{END}"

    .global gUnknown_08214044
gUnknown_08214044:
    .string "Hush{END}"

    .global gUnknown_08214049
gUnknown_08214049:
    .string "Dispel{END}"

    .global gUnknown_08214050
gUnknown_08214050:
    .string "RenewX{END}"

    .global gUnknown_08214057
gUnknown_08214057:
    .string "CuraX{END}"

    .global gUnknown_0821405D
gUnknown_0821405D:
    .string "Wall{END}"

    .global gUnknown_08214062
gUnknown_08214062:
    .string "ZomX{END}"

    .global gUnknown_08214067
gUnknown_08214067:
    .string "Flare{END}"

    .global gUnknown_0821406D
gUnknown_0821406D:
    .string "Spark{END}"

    .global gUnknown_08214073
gUnknown_08214073:
    .string "Cold{END}"

    .global gUnknown_08214078
gUnknown_08214078:
    .string "3.5{END}"

    .global gUnknown_0821407C
gUnknown_0821407C:
    .string "Para{END}"

    .global gUnknown_08214081
gUnknown_08214081:
    .string "Sap{END}"

    .global gUnknown_08214085
gUnknown_08214085:
    .string "Rub{END}"

    .global gUnknown_08214089
gUnknown_08214089:
    .string "Flame{END}"

    .global gUnknown_0821408F
gUnknown_0821408F:
    .string "Fry{END}"

    .global gUnknown_08214093
gUnknown_08214093:
    .string "Frost{END}"

    .global gUnknown_08214099
gUnknown_08214099:
    .string "5.5{END}"

    .global gUnknown_0821409D
gUnknown_0821409D:
    .string "F.Ball{END}"

    .global gUnknown_082140A4
gUnknown_082140A4:
    .string "LStorm{END}"

    .global gUnknown_082140AB
gUnknown_082140AB:
    .string "Chill{END}"

    .global gUnknown_082140B1
gUnknown_082140B1:
    .string "9.5{END}"

    .global gUnknown_082140B5
gUnknown_082140B5:
    .string "Gale{END}"

    .global gUnknown_082140BA
gUnknown_082140BA:
    .string "Ice{END}"

    .global gUnknown_082140BE
gUnknown_082140BE:
    .string "Char{END}"

    .global gUnknown_082140C3
gUnknown_082140C3:
    .string "IceX{END}"

    .global gUnknown_082140C8
gUnknown_082140C8:
    .string "FireX{END}"

    .global gUnknown_082140CE
gUnknown_082140CE:
    .string "BoltX{END}"

    .global gUnknown_082140D4
gUnknown_082140D4:
    .string "Drain{END}"

    .global gUnknown_082140DA
gUnknown_082140DA:
    .string "???1{END}"

    .global gUnknown_082140DF
gUnknown_082140DF:
    .string "Comet{END}"

    .global gUnknown_082140E5
gUnknown_082140E5:
    .string "???2{END}"

    .global gUnknown_082140EA
gUnknown_082140EA:
    .string "???3{END}"

    .global gUnknown_082140EF
gUnknown_082140EF:
    .string "???4{END}"

    .global gUnknown_082140F4
gUnknown_082140F4:
    .string "???5{END}"

    .global gUnknown_082140F9
gUnknown_082140F9:
    .string "???6{END}"

    .global gUnknown_082140FE
gUnknown_082140FE:
    .string "???7{END}"

    .global gUnknown_08214103
gUnknown_08214103:
    .string "Cura1{END}"

    .global gUnknown_08214109
gUnknown_08214109:
    .string "RenewX{END}"

    .global gUnknown_08214110
gUnknown_08214110:
    .string "Edd{END}"

    .global gUnknown_08214114
gUnknown_08214114:
    .string "EddX{END}"

    .global gUnknown_08214119
gUnknown_08214119:
    .string "Eco{END}"

    .global gUnknown_0821411D
gUnknown_0821411D:
    .string "EcoX{END}"

    .global gUnknown_08214122
gUnknown_08214122:
    .string "???8{END}"

    .global gUnknown_08214127
gUnknown_08214127:
    .string "???9{END}"

    .global gUnknown_0821412C
gUnknown_0821412C:
    .string "???10{END}"

    .global gUnknown_08214132
gUnknown_08214132:
    .string "???12{END}"

    .global gUnknown_08214138
gUnknown_08214138:
    .string "???13{END}"

    .global gUnknown_0821413E
gUnknown_0821413E:
    .string "???14{END}"

    .global gUnknown_08214144
gUnknown_08214144:
    .string "???15{END}"

    .global gUnknown_0821414A
gUnknown_0821414A:
    .string "???16{END}"

    .global gUnknown_08214150
gUnknown_08214150:
    .string "???17{END}"

    .global gUnknown_08214156
gUnknown_08214156:
    .string "ZomX{END}"

    .global gUnknown_0821415B
gUnknown_0821415B:
    .string "???18{END}"

    .global gUnknown_08214161
gUnknown_08214161:
    .string "???19{END}"

    .global gUnknown_08214167
gUnknown_08214167:
    .string "Bomb{END}"

    .global gUnknown_0821416C
gUnknown_0821416C:
    .string "Boom{END}"

    .global gUnknown_08214171
gUnknown_08214171:
    .string "Warp{END}"

    .global gUnknown_08214176
gUnknown_08214176:
    .string "Flee{END}"

    .global gUnknown_0821417B
gUnknown_0821417B:
    .string "Blast{END}"

    .global gUnknown_08214181
gUnknown_08214181:
    .string "Exit{END}"

    .global gUnknown_08214186
gUnknown_08214186:
    .string "Nova{END}"

    .global gUnknown_0821418B
gUnknown_0821418B:
    .string "NovaX{END}"

    .global gUnknown_08214191
gUnknown_08214191:
    .string "???20{END}"

    .global gUnknown_08214197
gUnknown_08214197:
    .string "???21{END}"

    .align 2
    .global gUnknown_082141A0
gUnknown_082141A0:
    .word gUnknown_08213FE8 @ 0 / 0x0
    .word gUnknown_08213FEE @ 1 / 0x1
    .word gUnknown_08213FF3 @ 2 / 0x2
    .word gUnknown_08213FF8 @ 3 / 0x3
    .word gUnknown_08213FFE @ 4 / 0x4
    .word gUnknown_08214005 @ 5 / 0x5
    .word gUnknown_0821400B @ 6 / 0x6
    .word gUnknown_08214010 @ 7 / 0x7
    .word gUnknown_08214016 @ 8 / 0x8
    .word gUnknown_0821401B @ 9 / 0x9
    .word gUnknown_08214021 @ 10 / 0xA
    .word gUnknown_08214027 @ 11 / 0xB
    .word gUnknown_0821402C @ 12 / 0xC
    .word gUnknown_08214033 @ 13 / 0xD
    .word gUnknown_08214039 @ 14 / 0xE
    .word gUnknown_0821403E @ 15 / 0xF
    .word gUnknown_08214044 @ 16 / 0x10
    .word gUnknown_08214049 @ 17 / 0x11
    .word gUnknown_08214050 @ 18 / 0x12
    .word gUnknown_08214057 @ 19 / 0x13
    .word gUnknown_0821405D @ 20 / 0x14
    .word gUnknown_08214062 @ 21 / 0x15
    .word gUnknown_08214067 @ 22 / 0x16
    .word gUnknown_0821406D @ 23 / 0x17
    .word gUnknown_08214073 @ 24 / 0x18
    .word gUnknown_08214078 @ 25 / 0x19
    .word gUnknown_0821407C @ 26 / 0x1A
    .word gUnknown_08214081 @ 27 / 0x1B
    .word gUnknown_08214085 @ 28 / 0x1C
    .word gUnknown_08214089 @ 29 / 0x1D
    .word gUnknown_0821408F @ 30 / 0x1E
    .word gUnknown_08214093 @ 31 / 0x1F
    .word gUnknown_08214099 @ 32 / 0x20
    .word gUnknown_0821409D @ 33 / 0x21
    .word gUnknown_082140A4 @ 34 / 0x22
    .word gUnknown_082140AB @ 35 / 0x23
    .word gUnknown_082140B1 @ 36 / 0x24
    .word gUnknown_082140B5 @ 37 / 0x25
    .word gUnknown_082140BA @ 38 / 0x26
    .word gUnknown_082140BE @ 39 / 0x27
    .word gUnknown_082140C3 @ 40 / 0x28
    .word gUnknown_082140C8 @ 41 / 0x29
    .word gUnknown_082140CE @ 42 / 0x2A
    .word gUnknown_082140D4 @ 43 / 0x2B
    .word gUnknown_082140DA @ 44 / 0x2C
    .word gUnknown_082140DF @ 45 / 0x2D
    .word gUnknown_082140E5 @ 46 / 0x2E
    .word gUnknown_082140EA @ 47 / 0x2F
    .word gUnknown_082140EF @ 48 / 0x30
    .word gUnknown_082140F4 @ 49 / 0x31
    .word gUnknown_082140F9 @ 50 / 0x32
    .word gUnknown_082140FE @ 51 / 0x33
    .word gUnknown_08214103 @ 52 / 0x34
    .word gUnknown_08214109 @ 53 / 0x35
    .word gUnknown_08214110 @ 54 / 0x36
    .word gUnknown_08214114 @ 55 / 0x37
    .word gUnknown_08214119 @ 56 / 0x38
    .word gUnknown_0821411D @ 57 / 0x39
    .word gUnknown_08214122 @ 58 / 0x3A
    .word gUnknown_08214127 @ 59 / 0x3B
    .word gUnknown_0821412C @ 60 / 0x3C
    .word gUnknown_08214132 @ 61 / 0x3D
    .word gUnknown_08214138 @ 62 / 0x3E
    .word gUnknown_0821413E @ 63 / 0x3F
    .word gUnknown_08214144 @ 64 / 0x40
    .word gUnknown_0821414A @ 65 / 0x41
    .word gUnknown_08214150 @ 66 / 0x42
    .word gUnknown_08214156 @ 67 / 0x43
    .word gUnknown_0821415B @ 68 / 0x44
    .word gUnknown_08214161 @ 69 / 0x45
    .word gUnknown_08214167 @ 70 / 0x46
    .word gUnknown_0821416C @ 71 / 0x47
    .word gUnknown_08214171 @ 72 / 0x48
    .word gUnknown_08214176 @ 73 / 0x49
    .word gUnknown_0821417B @ 74 / 0x4A
    .word gUnknown_08214181 @ 75 / 0x4B
    .word gUnknown_08214186 @ 76 / 0x4C
    .word gUnknown_0821418B @ 77 / 0x4D
    .word gUnknown_08214191 @ 78 / 0x4E
    .word gUnknown_08214197 @ 79 / 0x4F
