    .global gUnknown_082123B4
gUnknown_082123B4:
    .string "Recovers HP by 50pts.{END}"

    .global gUnknown_082123CA
gUnknown_082123CA:
    .string "Briefly ups defense power.{END}"

    .global gUnknown_082123E5
gUnknown_082123E5:
    .string "Slows enemy down.{END}"

    .global gUnknown_082123F7
gUnknown_082123F7:
    .string "Briefly ups luck.{END}"

    .global gUnknown_08212409
gUnknown_08212409:
    .string "Briefly ups attack power.{END}"

    .global gUnknown_08212423
gUnknown_08212423:
    .string "Recovers HP by 100pts.{END}"

    .global gUnknown_0821243A
gUnknown_0821243A:
    .string "Holds enemy's move.{END}"

    .global gUnknown_0821244E
gUnknown_0821244E:
    .string "Briefly ups agility.{END}"

    .global gUnknown_08212463
gUnknown_08212463:
    .string "Angel LV1. Single enemy.{END}"

    .global gUnknown_0821247C
gUnknown_0821247C:
    .string "Recovers HP by 250pts.{END}"

    .global gUnknown_08212493
gUnknown_08212493:
    .string "Cures “Stun“ state HP1.{END}"

    .global gUnknown_082124AB
gUnknown_082124AB:
    .string "Cures any abnormal status.{END}"

    .global gUnknown_082124C6
gUnknown_082124C6:
    .string "Lessens damage by magic.{END}"

    .global gUnknown_082124DF
gUnknown_082124DF:
    .string "Recovers HP fully.{END}"

    .global gUnknown_082124F2
gUnknown_082124F2:
    .string "Angel LV2. Single enemy.{END}"

    .global gUnknown_0821250B
gUnknown_0821250B:
    .string "Ups party's defense power.{END}"

    .global gUnknown_08212526
gUnknown_08212526:
    .string "Briefly seals enemy's magic.{END}"

    .global gUnknown_08212543
gUnknown_08212543:
    .string "Voids enemy's magic once.{END}"

    .global gUnknown_0821255D
gUnknown_0821255D:
    .string "Cures “Stun“ state fully.{END}"

    .global gUnknown_08212577
gUnknown_08212577:
    .string "Recovers party HP by 250pts.{END}"

    .global gUnknown_08212594
gUnknown_08212594:
    .string "Reflects enemy's magic once.{END}"

    .global gUnknown_082125B1
gUnknown_082125B1:
    .string "Angel LV3. Enemy group.{END}"

    .global gUnknown_082125C9
gUnknown_082125C9:
    .string "Fire LV1. Single enemy.{END}"

    .global gUnknown_082125E1
gUnknown_082125E1:
    .string "Thunder LV1. Single enemy.{END}"

    .global gUnknown_082125FC
gUnknown_082125FC:
    .string "Ice LV1. Single enemy.{END}"

    .global gUnknown_08212613
gUnknown_08212613:
    .string "Quake LV1. Enemy group.{END}"

    .global gUnknown_0821262B
gUnknown_0821262B:
    .string "Stops enemy's time.{END}"

    .global gUnknown_0821263F
gUnknown_0821263F:
    .string "Absorbs enemy's HP.{END}"

    .global gUnknown_08212653
gUnknown_08212653:
    .string "Death penalty. Single enemy.{END}"

    .global gUnknown_08212670
gUnknown_08212670:
    .string "Fire LV2. Single enemy.{END}"

    .global gUnknown_08212688
gUnknown_08212688:
    .string "Thunder LV2. Single enemy.{END}"

    .global gUnknown_082126A3
gUnknown_082126A3:
    .string "Ice LV2. Single enemy.{END}"

    .global gUnknown_082126BA
gUnknown_082126BA:
    .string "Quake LV2. Enemy group.{END}"

    .global gUnknown_082126D2
gUnknown_082126D2:
    .string "Fire LV3. Single enemy.{END}"

    .global gUnknown_082126EA
gUnknown_082126EA:
    .string "Thunder LV4. Enemy group.{END}"

    .global gUnknown_08212704
gUnknown_08212704:
    .string "Ice LV3. Enemy group.{END}"

    .global gUnknown_0821271A
gUnknown_0821271A:
    .string "Quake LV3. Enemy group.{END}"

    .global gUnknown_08212732
gUnknown_08212732:
    .string "Thunder LV5. Enemy group.{END}"

    .global gUnknown_0821274C
gUnknown_0821274C:
    .string "Ice LV4. Enemy group.{END}"

    .global gUnknown_08212762
gUnknown_08212762:
    .string "Fire LV5. Enemy group.{END}"

    .global gUnknown_08212779
gUnknown_08212779:
    .string "Ice LV5. Single enemy.{END}"

    .global gUnknown_08212790
gUnknown_08212790:
    .string "Fire LV4. Single enemy.{END}"

    .global gUnknown_082127A8
gUnknown_082127A8:
    .string "Thunder LV3. Single enemy.{END}"

    .global gUnknown_082127C3
gUnknown_082127C3:
    .string "Absorbs enemy's AP.{END}"

    .global gUnknown_082127D7
gUnknown_082127D7:
    .string "Dummy{END}"

    .global gUnknown_082127DD
gUnknown_082127DD:
    .string "Meteor storm. Enemy group.{END}"

    .global gUnknown_082127F8
gUnknown_082127F8:
    .string "Dummy{END}"

    .global gUnknown_082127FE
gUnknown_082127FE:
    .string "Dummy{END}"

    .global gUnknown_08212804
gUnknown_08212804:
    .string "Dummy{END}"

    .global gUnknown_0821280A
gUnknown_0821280A:
    .string "Dummy{END}"

    .global gUnknown_08212810
gUnknown_08212810:
    .string "Dummy{END}"

    .global gUnknown_08212816
gUnknown_08212816:
    .string "Dummy{END}"

    .global gUnknown_0821281C
gUnknown_0821281C:
    .string "Dummy{END}"

    .global gUnknown_08212822
gUnknown_08212822:
    .string "Cures “Stun“ state fully.{END}"

    .global gUnknown_0821283C
gUnknown_0821283C:
    .string "Used under water in battle.{END}"

    .global gUnknown_08212858
gUnknown_08212858:
    .string "Used under water in battle.{END}"

    .global gUnknown_08212874
gUnknown_08212874:
    .string "Used under water in battle.{END}"

    .global gUnknown_08212890
gUnknown_08212890:
    .string "Used under water in battle.{END}"

    .global gUnknown_082128AC
gUnknown_082128AC:
    .string "Dummy{END}"

    .global gUnknown_082128B2
gUnknown_082128B2:
    .string "Dummy{END}"

    .global gUnknown_082128B8
gUnknown_082128B8:
    .string "Dummy{END}"

    .global gUnknown_082128BE
gUnknown_082128BE:
    .string "Dummy{END}"

    .global gUnknown_082128C4
gUnknown_082128C4:
    .string "Dummy{END}"

    .global gUnknown_082128CA
gUnknown_082128CA:
    .string "Dummy{END}"

    .global gUnknown_082128D0
gUnknown_082128D0:
    .string "Dummy{END}"

    .global gUnknown_082128D6
gUnknown_082128D6:
    .string "Dummy{END}"

    .global gUnknown_082128DC
gUnknown_082128DC:
    .string "Dummy{END}"

    .global gUnknown_082128E2
gUnknown_082128E2:
    .string "Angel LV3. Enemy group.{END}"

    .global gUnknown_082128FA
gUnknown_082128FA:
    .string "Dummy{END}"

    .global gUnknown_08212900
gUnknown_08212900:
    .string "Dummy{END}"

    .global gUnknown_08212906
gUnknown_08212906:
    .string "Explosion LV1. Single enemy.{END}"

    .global gUnknown_08212923
gUnknown_08212923:
    .string "Explosion LV2. Enemy group.{END}"

    .global gUnknown_0821293F
gUnknown_0821293F:
    .string "Warps to a town.{END}"

    .global gUnknown_08212950
gUnknown_08212950:
    .string "Escapes from battle.{END}"

    .global gUnknown_08212965
gUnknown_08212965:
    .string "Explosion LV3. Single enemy.{END}"

    .global gUnknown_08212982
gUnknown_08212982:
    .string "Escapes from a dungeon.{END}"

    .global gUnknown_0821299A
gUnknown_0821299A:
    .string "Explosion LV4. Enemy group.{END}"

    .global gUnknown_082129B6
gUnknown_082129B6:
    .string "Explosion LV5. Single enemy.{END}"

    .global gUnknown_082129D3
gUnknown_082129D3:
    .string "Dummy{END}"

    .global gUnknown_082129D9
gUnknown_082129D9:
    .string "Dummy{END}"

    .global gUnknown_082129DF
gUnknown_082129DF:
    .string "Digs to escape from battle.{END}"

    .global gUnknown_082129FB
gUnknown_082129FB:
    .string "Used in battle.{END}"

    .global gUnknown_08212A0B
gUnknown_08212A0B:
    .string "Characters fuse together.{END}"

    .global gUnknown_08212A25
gUnknown_08212A25:
    .string "Available under water.{END}"

    .global gUnknown_08212A3C
gUnknown_08212A3C:
    .string "Available on the ground.{END}"

    .global gUnknown_08212A55
gUnknown_08212A55:
    .string "Characters fuse together.{END}"

    .global gUnknown_08212A6F
gUnknown_08212A6F:
    .string "Releases fused characters.{END}"

    .global gUnknown_08212A8A
gUnknown_08212A8A:
    .string "Returns to human form.{END}"

    @Unreferenced string
    .global gUnknown_08212AA1
gUnknown_08212AA1:
    .string "{END}"

    @Unreferenced string
    .global gUnknown_08212AA2
gUnknown_08212AA2:
    .string "{END}"

    @Unreferenced string
    .global gUnknown_08212AA3
gUnknown_08212AA3:
    .string "{END}"

    .global gUnknown_08212AA4
gUnknown_08212AA4:
    .word gUnknown_082123B4 @ 0 / 0x0
    .word gUnknown_082123CA @ 1 / 0x1
    .word gUnknown_082123E5 @ 2 / 0x2
    .word gUnknown_082123F7 @ 3 / 0x3
    .word gUnknown_08212409 @ 4 / 0x4
    .word gUnknown_08212423 @ 5 / 0x5
    .word gUnknown_0821243A @ 6 / 0x6
    .word gUnknown_0821244E @ 7 / 0x7
    .word gUnknown_08212463 @ 8 / 0x8
    .word gUnknown_0821247C @ 9 / 0x9
    .word gUnknown_08212493 @ 10 / 0xA
    .word gUnknown_082124AB @ 11 / 0xB
    .word gUnknown_082124C6 @ 12 / 0xC
    .word gUnknown_082124DF @ 13 / 0xD
    .word gUnknown_082124F2 @ 14 / 0xE
    .word gUnknown_0821250B @ 15 / 0xF
    .word gUnknown_08212526 @ 16 / 0x10
    .word gUnknown_08212543 @ 17 / 0x11
    .word gUnknown_0821255D @ 18 / 0x12
    .word gUnknown_08212577 @ 19 / 0x13
    .word gUnknown_08212594 @ 20 / 0x14
    .word gUnknown_082125B1 @ 21 / 0x15
    .word gUnknown_082125C9 @ 22 / 0x16
    .word gUnknown_082125E1 @ 23 / 0x17
    .word gUnknown_082125FC @ 24 / 0x18
    .word gUnknown_08212613 @ 25 / 0x19
    .word gUnknown_0821262B @ 26 / 0x1A
    .word gUnknown_0821263F @ 27 / 0x1B
    .word gUnknown_08212653 @ 28 / 0x1C
    .word gUnknown_08212670 @ 29 / 0x1D
    .word gUnknown_08212688 @ 30 / 0x1E
    .word gUnknown_082126A3 @ 31 / 0x1F
    .word gUnknown_082126BA @ 32 / 0x20
    .word gUnknown_082126D2 @ 33 / 0x21
    .word gUnknown_082126EA @ 34 / 0x22
    .word gUnknown_08212704 @ 35 / 0x23
    .word gUnknown_0821271A @ 36 / 0x24
    .word gUnknown_08212732 @ 37 / 0x25
    .word gUnknown_0821274C @ 38 / 0x26
    .word gUnknown_08212762 @ 39 / 0x27
    .word gUnknown_08212779 @ 40 / 0x28
    .word gUnknown_08212790 @ 41 / 0x29
    .word gUnknown_082127A8 @ 42 / 0x2A
    .word gUnknown_082127C3 @ 43 / 0x2B
    .word gUnknown_082127D7 @ 44 / 0x2C
    .word gUnknown_082127DD @ 45 / 0x2D
    .word gUnknown_082127F8 @ 46 / 0x2E
    .word gUnknown_082127FE @ 47 / 0x2F
    .word gUnknown_08212804 @ 48 / 0x30
    .word gUnknown_0821280A @ 49 / 0x31
    .word gUnknown_08212810 @ 50 / 0x32
    .word gUnknown_08212816 @ 51 / 0x33
    .word gUnknown_0821281C @ 52 / 0x34
    .word gUnknown_08212822 @ 53 / 0x35
    .word gUnknown_0821283C @ 54 / 0x36
    .word gUnknown_08212858 @ 55 / 0x37
    .word gUnknown_08212874 @ 56 / 0x38
    .word gUnknown_08212890 @ 57 / 0x39
    .word gUnknown_082128AC @ 58 / 0x3A
    .word gUnknown_082128B2 @ 59 / 0x3B
    .word gUnknown_082128B8 @ 60 / 0x3C
    .word gUnknown_082128BE @ 61 / 0x3D
    .word gUnknown_082128C4 @ 62 / 0x3E
    .word gUnknown_082128CA @ 63 / 0x3F
    .word gUnknown_082128D0 @ 64 / 0x40
    .word gUnknown_082128D6 @ 65 / 0x41
    .word gUnknown_082128DC @ 66 / 0x42
    .word gUnknown_082128E2 @ 67 / 0x43
    .word gUnknown_082128FA @ 68 / 0x44
    .word gUnknown_08212900 @ 69 / 0x45
    .word gUnknown_08212906 @ 70 / 0x46
    .word gUnknown_08212923 @ 71 / 0x47
    .word gUnknown_0821293F @ 72 / 0x48
    .word gUnknown_08212950 @ 73 / 0x49
    .word gUnknown_08212965 @ 74 / 0x4A
    .word gUnknown_08212982 @ 75 / 0x4B
    .word gUnknown_0821299A @ 76 / 0x4C
    .word gUnknown_082129B6 @ 77 / 0x4D
    .word gUnknown_082129D3 @ 78 / 0x4E
    .word gUnknown_082129D9 @ 79 / 0x4F
    .word gUnknown_082129DF @ 80 / 0x50
    .word gUnknown_082129FB @ 81 / 0x51
    .word gUnknown_08212A0B @ 82 / 0x52
    .word gUnknown_08212A25 @ 83 / 0x53
    .word gUnknown_08212A3C @ 84 / 0x54
    .word gUnknown_08212A55 @ 85 / 0x55
    .word gUnknown_08212A6F @ 86 / 0x56
    .word gUnknown_08212A8A @ 87 / 0x57
