    .global gUnknown_08213468
gUnknown_08213468:
    .string "Dirk{END}"

    .global gUnknown_0821346D
gUnknown_0821346D:
    .string "BronzSD{END}"

    .global gUnknown_08213475
gUnknown_08213475:
    .string "Sabre{END}"

    .global gUnknown_0821347B
gUnknown_0821347B:
    .string "Scythe{END}"

    .global gUnknown_08213482
gUnknown_08213482:
    .string "LongSD{END}"

    .global gUnknown_08213489
gUnknown_08213489:
    .string "DragonSD{END}"

    .global gUnknown_08213492
gUnknown_08213492:
    .string "PowerSD{END}"

    .global gUnknown_0821349A
gUnknown_0821349A:
    .string "WingSD{END}"

    .global gUnknown_082134A1
gUnknown_082134A1:
    .string "EmporSD{END}"

    .global gUnknown_082134A9
gUnknown_082134A9:
    .string "BrokenSD{END}"

    .global gUnknown_082134B2
gUnknown_082134B2:
    .string "Dummy{END}"

    .global gUnknown_082134B8
gUnknown_082134B8:
    .string "FlameSD{END}"

    .global gUnknown_082134C0
gUnknown_082134C0:
    .string "Sickle{END}"

    .global gUnknown_082134C7
gUnknown_082134C7:
    .string "BroadSD{END}"

    .global gUnknown_082134CF
gUnknown_082134CF:
    .string "MystSD{END}"

    .global gUnknown_082134D6
gUnknown_082134D6:
    .string "S.Arms{END}"

    .global gUnknown_082134DD
gUnknown_082134DD:
    .string "ShortRP{END}"

    .global gUnknown_082134E5
gUnknown_082134E5:
    .string "Rapier{END}"

    .global gUnknown_082134EC
gUnknown_082134EC:
    .string "IronRP{END}"

    .global gUnknown_082134F3
gUnknown_082134F3:
    .string "PoisonRP{END}"

    .global gUnknown_082134FC
gUnknown_082134FC:
    .string "LightRP{END}"

    .global gUnknown_08213504
gUnknown_08213504:
    .string "Dummy{END}"

    .global gUnknown_0821350A
gUnknown_0821350A:
    .string "FlameRP{END}"

    .global gUnknown_08213512
gUnknown_08213512:
    .string "WingRP{END}"

    .global gUnknown_08213519
gUnknown_08213519:
    .string "BronzRP{END}"

    .global gUnknown_08213521
gUnknown_08213521:
    .string "EvilRP{END}"

    .global gUnknown_08213528
gUnknown_08213528:
    .string "ThundrRP{END}"

    .global gUnknown_08213531
gUnknown_08213531:
    .string "Dummy{END}"

    .global gUnknown_08213537
gUnknown_08213537:
    .string "LoyalRP{END}"

    .global gUnknown_0821353F
gUnknown_0821353F:
    .string "PowerRP{END}"

    .global gUnknown_08213547
gUnknown_08213547:
    .string "IronHR{END}"

    .global gUnknown_0821354E
gUnknown_0821354E:
    .string "SpineHR{END}"

    .global gUnknown_08213556
gUnknown_08213556:
    .string "Club{END}"

    .global gUnknown_0821355B
gUnknown_0821355B:
    .string "GiantHR{END}"

    .global gUnknown_08213563
gUnknown_08213563:
    .string "FlameHR{END}"

    .global gUnknown_0821356B
gUnknown_0821356B:
    .string "Dummy{END}"

    .global gUnknown_08213571
gUnknown_08213571:
    .string "RageHR{END}"

    .global gUnknown_08213578
gUnknown_08213578:
    .string "Dummy{END}"

    .global gUnknown_0821357E
gUnknown_0821357E:
    .string "Mallet{END}"

    .global gUnknown_08213585
gUnknown_08213585:
    .string "StarHR{END}"

    .global gUnknown_0821358C
gUnknown_0821358C:
    .string "Stick{END}"

    .global gUnknown_08213592
gUnknown_08213592:
    .string "Cane{END}"

    .global gUnknown_08213597
gUnknown_08213597:
    .string "BoneCN{END}"

    .global gUnknown_0821359E
gUnknown_0821359E:
    .string "EvilCN{END}"

    .global gUnknown_082135A5
gUnknown_082135A5:
    .string "Dummy{END}"

    .global gUnknown_082135AB
gUnknown_082135AB:
    .string "IcyCN{END}"

    .global gUnknown_082135B1
gUnknown_082135B1:
    .string "Dummy{END}"

    .global gUnknown_082135B7
gUnknown_082135B7:
    .string "GlowCN{END}"

    .global gUnknown_082135BE
gUnknown_082135BE:
    .string "Dummy{END}"

    .global gUnknown_082135C4
gUnknown_082135C4:
    .string "Pole{END}"

    .global gUnknown_082135C9
gUnknown_082135C9:
    .string "Pike{END}"

    .global gUnknown_082135CE
gUnknown_082135CE:
    .string "Javelin{END}"

    .global gUnknown_082135D6
gUnknown_082135D6:
    .string "OldSP{END}"

    .global gUnknown_082135DC
gUnknown_082135DC:
    .string "HeroSP{END}"

    .global gUnknown_082135E3
gUnknown_082135E3:
    .string "Trident{END}"

    .global gUnknown_082135EB
gUnknown_082135EB:
    .string "Dummy{END}"

    .global gUnknown_082135F1
gUnknown_082135F1:
    .string "Sleeper{END}"

    .global gUnknown_082135F9
gUnknown_082135F9:
    .string "Dummy{END}"

    .global gUnknown_082135FF
gUnknown_082135FF:
    .string "DigCW{END}"

    .global gUnknown_08213605
gUnknown_08213605:
    .string "RustCW{END}"

    .global gUnknown_0821360C
gUnknown_0821360C:
    .string "IronCW{END}"

    .global gUnknown_08213613
gUnknown_08213613:
    .string "IcyCW{END}"

    .global gUnknown_08213619
gUnknown_08213619:
    .string "Dummy{END}"

    .global gUnknown_0821361F
gUnknown_0821361F:
    .string "MystCW{END}"

    .global gUnknown_08213626
gUnknown_08213626:
    .string "Dummy{END}"

    .global gUnknown_0821362C
gUnknown_0821362C:
    .string "ThrowDR{END}"

    .global gUnknown_08213634
gUnknown_08213634:
    .string "Dagger{END}"

    .global gUnknown_0821363B
gUnknown_0821363B:
    .string "Dart{END}"

    .global gUnknown_08213640
gUnknown_08213640:
    .string "Tri-DR{END}"

    .global gUnknown_08213647
gUnknown_08213647:
    .string "PowerDR{END}"

    .global gUnknown_0821364F
gUnknown_0821364F:
    .string "FlameDR{END}"

    .global gUnknown_08213657
gUnknown_08213657:
    .string "SilverDR{END}"

    .global gUnknown_08213660
gUnknown_08213660:
    .string "Dummy{END}"

    .global gUnknown_08213666
gUnknown_08213666:
    .string "Dummy{END}"

    .global gUnknown_0821366C
gUnknown_0821366C:
    .string "IcyDR{END}"

    .global gUnknown_08213672
gUnknown_08213672:
    .string "Dummy{END}"

    .global gUnknown_08213678
gUnknown_08213678:
    .string "DarkDR{END}"

    .global gUnknown_0821367F
gUnknown_0821367F:
    .string "Dummy{END}"

    .global gUnknown_08213685
gUnknown_08213685:
    .string "BronzBW{END}"

    .global gUnknown_0821368D
gUnknown_0821368D:
    .string "ShortBW{END}"

    .global gUnknown_08213695
gUnknown_08213695:
    .string "LongBW{END}"

    .global gUnknown_0821369C
gUnknown_0821369C:
    .string "SteelBW{END}"

    .global gUnknown_082136A4
gUnknown_082136A4:
    .string "PoisonBW{END}"

    .global gUnknown_082136AD
gUnknown_082136AD:
    .string "SharpBW{END}"

    .global gUnknown_082136B5
gUnknown_082136B5:
    .string "MoonBW{END}"

    .global gUnknown_082136BC
gUnknown_082136BC:
    .string "JadeBW{END}"

    .global gUnknown_082136C3
gUnknown_082136C3:
    .string "Tri-BW{END}"

    .global gUnknown_082136CA
gUnknown_082136CA:
    .string "Dummy{END}"

    .global gUnknown_082136D0
gUnknown_082136D0:
    .string "Dummy{END}"

    .global gUnknown_082136D6
gUnknown_082136D6:
    .string "Dummy{END}"

    .global gUnknown_082136DC
gUnknown_082136DC:
    .string "DwarfBW{END}"

    .global gUnknown_082136E4
gUnknown_082136E4:
    .string "HeroBW{END}"

    .global gUnknown_082136EB
gUnknown_082136EB:
    .string "Dummy{END}"

    .global gUnknown_082136F1
gUnknown_082136F1:
    .string "B.Rang{END}"

    .global gUnknown_082136F8
gUnknown_082136F8:
    .string "Foil{END}"

    .global gUnknown_082136FD
gUnknown_082136FD:
    .string "Tri-Rang{END}"

    .align 2
    .global gUnknown_08213708
gUnknown_08213708:
    .word gUnknown_08213468 @ 0 / 0x0
    .word gUnknown_0821346D @ 1 / 0x1
    .word gUnknown_08213475 @ 2 / 0x2
    .word gUnknown_0821347B @ 3 / 0x3
    .word gUnknown_08213482 @ 4 / 0x4
    .word gUnknown_08213489 @ 5 / 0x5
    .word gUnknown_08213492 @ 6 / 0x6
    .word gUnknown_0821349A @ 7 / 0x7
    .word gUnknown_082134A1 @ 8 / 0x8
    .word gUnknown_082134A9 @ 9 / 0x9
    .word gUnknown_082134B2 @ 10 / 0xA
    .word gUnknown_082134B8 @ 11 / 0xB
    .word gUnknown_082134C0 @ 12 / 0xC
    .word gUnknown_082134C7 @ 13 / 0xD
    .word gUnknown_082134CF @ 14 / 0xE
    .word gUnknown_082134D6 @ 15 / 0xF
    .word gUnknown_082134DD @ 16 / 0x10
    .word gUnknown_082134E5 @ 17 / 0x11
    .word gUnknown_082134EC @ 18 / 0x12
    .word gUnknown_082134F3 @ 19 / 0x13
    .word gUnknown_082134FC @ 20 / 0x14
    .word gUnknown_08213504 @ 21 / 0x15
    .word gUnknown_0821350A @ 22 / 0x16
    .word gUnknown_08213512 @ 23 / 0x17
    .word gUnknown_08213519 @ 24 / 0x18
    .word gUnknown_08213521 @ 25 / 0x19
    .word gUnknown_08213528 @ 26 / 0x1A
    .word gUnknown_08213531 @ 27 / 0x1B
    .word gUnknown_08213537 @ 28 / 0x1C
    .word gUnknown_0821353F @ 29 / 0x1D
    .word gUnknown_08213547 @ 30 / 0x1E
    .word gUnknown_0821354E @ 31 / 0x1F
    .word gUnknown_08213556 @ 32 / 0x20
    .word gUnknown_0821355B @ 33 / 0x21
    .word gUnknown_08213563 @ 34 / 0x22
    .word gUnknown_0821356B @ 35 / 0x23
    .word gUnknown_08213571 @ 36 / 0x24
    .word gUnknown_08213578 @ 37 / 0x25
    .word gUnknown_0821357E @ 38 / 0x26
    .word gUnknown_08213585 @ 39 / 0x27
    .word gUnknown_0821358C @ 40 / 0x28
    .word gUnknown_08213592 @ 41 / 0x29
    .word gUnknown_08213597 @ 42 / 0x2A
    .word gUnknown_0821359E @ 43 / 0x2B
    .word gUnknown_082135A5 @ 44 / 0x2C
    .word gUnknown_082135AB @ 45 / 0x2D
    .word gUnknown_082135B1 @ 46 / 0x2E
    .word gUnknown_082135B7 @ 47 / 0x2F
    .word gUnknown_082135BE @ 48 / 0x30
    .word gUnknown_082135C4 @ 49 / 0x31
    .word gUnknown_082135C9 @ 50 / 0x32
    .word gUnknown_082135CE @ 51 / 0x33
    .word gUnknown_082135D6 @ 52 / 0x34
    .word gUnknown_082135DC @ 53 / 0x35
    .word gUnknown_082135E3 @ 54 / 0x36
    .word gUnknown_082135EB @ 55 / 0x37
    .word gUnknown_082135F1 @ 56 / 0x38
    .word gUnknown_082135F9 @ 57 / 0x39
    .word gUnknown_082135FF @ 58 / 0x3A
    .word gUnknown_08213605 @ 59 / 0x3B
    .word gUnknown_0821360C @ 60 / 0x3C
    .word gUnknown_08213613 @ 61 / 0x3D
    .word gUnknown_08213619 @ 62 / 0x3E
    .word gUnknown_0821361F @ 63 / 0x3F
    .word gUnknown_08213626 @ 64 / 0x40
    .word gUnknown_0821362C @ 65 / 0x41
    .word gUnknown_08213634 @ 66 / 0x42
    .word gUnknown_0821363B @ 67 / 0x43
    .word gUnknown_08213640 @ 68 / 0x44
    .word gUnknown_08213647 @ 69 / 0x45
    .word gUnknown_0821364F @ 70 / 0x46
    .word gUnknown_08213657 @ 71 / 0x47
    .word gUnknown_08213660 @ 72 / 0x48
    .word gUnknown_08213666 @ 73 / 0x49
    .word gUnknown_0821366C @ 74 / 0x4A
    .word gUnknown_08213672 @ 75 / 0x4B
    .word gUnknown_08213678 @ 76 / 0x4C
    .word gUnknown_0821367F @ 77 / 0x4D
    .word gUnknown_08213685 @ 78 / 0x4E
    .word gUnknown_0821368D @ 79 / 0x4F
    .word gUnknown_08213695 @ 80 / 0x50
    .word gUnknown_0821369C @ 81 / 0x51
    .word gUnknown_082136A4 @ 82 / 0x52
    .word gUnknown_082136AD @ 83 / 0x53
    .word gUnknown_082136B5 @ 84 / 0x54
    .word gUnknown_082136BC @ 85 / 0x55
    .word gUnknown_082136C3 @ 86 / 0x56
    .word gUnknown_082136CA @ 87 / 0x57
    .word gUnknown_082136D0 @ 88 / 0x58
    .word gUnknown_082136D6 @ 89 / 0x59
    .word gUnknown_082136DC @ 90 / 0x5A
    .word gUnknown_082136E4 @ 91 / 0x5B
    .word gUnknown_082136EB @ 92 / 0x5C
    .word gUnknown_082136F1 @ 93 / 0x5D
    .word gUnknown_082136F8 @ 94 / 0x5E
    .word gUnknown_082136FD @ 95 / 0x5F
