    .align 2
    .global gUnknown_082E60B4
gUnknown_082E60B4:
@ Item 000 / 0x000 - 70GP
    .string "70ゼニ-"	@name
    .fill   3, 1, 0	@filler
    .byte   80	@unk9
    .hword  70	@cost
    .byte   0	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 001 / 0x001 - 150GP
    .string "150ゼニ-"	@name
    .fill   2, 1, 0	@filler
    .byte   80	@unk9
    .hword  150	@cost
    .byte   0	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 002 / 0x002 - 300GP
    .string "300ゼニ-"	@name
    .fill   2, 1, 0	@filler
    .byte   80	@unk9
    .hword  300	@cost
    .byte   0	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 003 / 0x003 - 650GP
    .string "650ゼニ-"	@name
    .fill   2, 1, 0	@filler
    .byte   80	@unk9
    .hword  650	@cost
    .byte   0	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 004 / 0x004 - 900GP
    .string "900ゼニ-"	@name
    .fill   2, 1, 0	@filler
    .byte   80	@unk9
    .hword  0	@cost
    .byte   0	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 005 / 0x005 - 1200GP
    .string "1200ゼニ-"	@name
    .fill   1, 1, 0	@filler
    .byte   80	@unk9
    .hword  1200	@cost
    .byte   0	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 006 / 0x006 - 2000GP
    .string "2000ゼニ-"	@name
    .fill   1, 1, 0	@filler
    .byte   80	@unk9
    .hword  2000	@cost
    .byte   0	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 007 / 0x007 - 3000GP
    .string "3000ゼニ-"	@name
    .fill   1, 1, 0	@filler
    .byte   80	@unk9
    .hword  3000	@cost
    .byte   0	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 008 / 0x008 - Herb
    .string "やくそう"	@name
    .fill   4, 1, 0	@filler
    .byte   16	@unk9
    .hword  10	@cost
    .byte   0	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 009 / 0x009 - Cure
    .string "リフルエキス"	@name
    .fill   2, 1, 0	@filler
    .byte   16	@unk9
    .hword  2000	@cost
    .byte   0	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 010 / 0x00A - Antdt
    .string "どくけし"	@name
    .fill   4, 1, 0	@filler
    .byte   16	@unk9
    .hword  15	@cost
    .byte   70	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 011 / 0x00B - Acorn
    .string "ちりょくのみ"	@name
    .fill   2, 1, 0	@filler
    .byte   16	@unk9
    .hword  30	@cost
    .byte   19	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 012 / 0x00C - M.Drop
    .string "つきのしずく"	@name
    .fill   2, 1, 0	@filler
    .byte   16	@unk9
    .hword  10000	@cost
    .byte   98	@unkC
    .byte   0	@unkD
    .byte   7	@flags

@ Item 013 / 0x00D - T.Drop
    .string "ベムのなみだ"	@name
    .fill   2, 1, 0	@filler
    .byte   16	@unk9
    .hword  20	@cost
    .byte   2	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 014 / 0x00E - Charm
    .string "おふだ"	@name
    .fill   5, 1, 0	@filler
    .byte   16	@unk9
    .hword  150	@cost
    .byte   7	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 015 / 0x00F - Life2
    .string "ばんのうやく"	@name
    .fill   2, 1, 0	@filler
    .byte   16	@unk9
    .hword  1000	@cost
    .byte   16	@unkC
    .byte   0	@unkD
    .byte   6	@flags

@ Item 016 / 0x010 - Mrbl1
    .string "かいしんたん"	@name
    .fill   2, 1, 0	@filler
    .byte   48	@unk9
    .hword  1000	@cost
    .byte   56	@unkC
    .byte   0	@unkD
    .byte   16	@flags

@ Item 017 / 0x011 - Mrbl2
    .string "かいしんせき"	@name
    .fill   2, 1, 0	@filler
    .byte   52	@unk9
    .hword  10000	@cost
    .byte   56	@unkC
    .byte   0	@unkD
    .byte   16	@flags

@ Item 018 / 0x012 - Mrbl3
    .string "まもりけむり"	@name
    .fill   2, 1, 0	@filler
    .byte   80	@unk9
    .hword  10	@cost
    .byte   57	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 019 / 0x013 - Whskrs
    .string "はずれ"	@name
    .fill   5, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   88	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 020 / 0x014 - Worm
    .string "みみず"	@name
    .fill   5, 1, 0	@filler
    .byte   97	@unk9
    .hword  50	@cost
    .byte   102	@unkC
    .byte   127	@unkD
    .byte   0	@flags

@ Item 021 / 0x015 - Worm2
    .string "ごかい"	@name
    .fill   5, 1, 0	@filler
    .byte   97	@unk9
    .hword  100	@cost
    .byte   102	@unkC
    .byte   127	@unkD
    .byte   0	@flags

@ Item 022 / 0x016 - Shrimp
    .string "えび"	@name
    .fill   6, 1, 0	@filler
    .byte   97	@unk9
    .hword  200	@cost
    .byte   102	@unkC
    .byte   127	@unkD
    .byte   0	@flags

@ Item 023 / 0x017 - Urchin
    .string "うに"	@name
    .fill   6, 1, 0	@filler
    .byte   97	@unk9
    .hword  300	@cost
    .byte   102	@unkC
    .byte   127	@unkD
    .byte   0	@flags

@ Item 024 / 0x018 - Shell
    .string "さざえ"	@name
    .fill   5, 1, 0	@filler
    .byte   97	@unk9
    .hword  500	@cost
    .byte   102	@unkC
    .byte   127	@unkD
    .byte   0	@flags

@ Item 025 / 0x019 - Apple
    .string "りんご"	@name
    .fill   5, 1, 0	@filler
    .byte   16	@unk9
    .hword  100	@cost
    .byte   0	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 026 / 0x01A - ProtnA
    .string "パロテイン"	@name
    .fill   3, 1, 0	@filler
    .byte   48	@unk9
    .hword  300	@cost
    .byte   60	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 027 / 0x01B - Antler
    .string "しかのつの"	@name
    .fill   3, 1, 0	@filler
    .byte   16	@unk9
    .hword  100	@cost
    .byte   70	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 028 / 0x01C - Wmeat
    .string "やきとり"	@name
    .fill   4, 1, 0	@filler
    .byte   16	@unk9
    .hword  800	@cost
    .byte   59	@unkC
    .byte   0	@unkD
    .byte   3	@flags

@ Item 029 / 0x01D - Life
    .string "きつけやく"	@name
    .fill   3, 1, 0	@filler
    .byte   16	@unk9
    .hword  500	@cost
    .byte   69	@unkC
    .byte   0	@unkD
    .byte   14	@flags

@ Item 030 / 0x01E - Nails
    .string "はずれ"	@name
    .fill   5, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   88	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 031 / 0x01F - Meat
    .string "げんしにく"	@name
    .fill   3, 1, 0	@filler
    .byte   16	@unk9
    .hword  100	@cost
    .byte   59	@unkC
    .byte   0	@unkD
    .byte   3	@flags

@ Item 032 / 0x020 - B.Stn
    .string "サンダ-スト-ン"	@name
    .byte   48	@unk9
    .hword  20	@cost
    .byte   161	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 033 / 0x021 - F.Stn
    .string "ファイアスト-ン"	@name
    .byte   48	@unk9
    .hword  20	@cost
    .byte   161	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 034 / 0x022 - C.Stn
    .string "つめたいいし"	@name
    .fill   2, 1, 0	@filler
    .byte   48	@unk9
    .hword  40	@cost
    .byte   161	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 035 / 0x023 - Smoke
    .string "えんまく"	@name
    .fill   4, 1, 0	@filler
    .byte   48	@unk9
    .hword  100	@cost
    .byte   161	@unkC
    .byte   0	@unkD
    .byte   1	@flags

@ Item 036 / 0x024 - DkKiss
    .string "だてんしのキス"	@name
    .fill   1, 1, 0	@filler
    .byte   48	@unk9
    .hword  200	@cost
    .byte   161	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 037 / 0x025 - Cure2
    .string "リフラルエキス"	@name
    .fill   1, 1, 0	@filler
    .byte   16	@unk9
    .hword  3250	@cost
    .byte   59	@unkC
    .byte   0	@unkD
    .byte   3	@flags

@ Item 038 / 0x026 - ProtnB
    .string "アブナイくすり"	@name
    .fill   1, 1, 0	@filler
    .byte   48	@unk9
    .hword  300	@cost
    .byte   161	@unkC
    .byte   2	@unkD
    .byte   2	@flags

@ Item 039 / 0x027 - Sash
    .string "ゆうきのベルト"	@name
    .fill   1, 1, 0	@filler
    .byte   96	@unk9
    .hword  10	@cost
    .byte   67	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 040 / 0x028 - W.Ptn
    .string "みそのもと"	@name
    .fill   3, 1, 0	@filler
    .byte   80	@unk9
    .hword  10	@cost
    .byte   64	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 041 / 0x029 - S.Ptn
    .string "ぶしんのたましい"	@name
    .byte   80	@unk9
    .hword  10	@cost
    .byte   65	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 042 / 0x02A - HrGlas
    .string "すなどけい"	@name
    .fill   3, 1, 0	@filler
    .byte   208	@unk9
    .hword  0	@cost
    .byte   62	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 043 / 0x02B - ExpBug
    .string "はずれ"	@name
    .fill   5, 1, 0	@filler
    .byte   80	@unk9
    .hword  10	@cost
    .byte   88	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 044 / 0x02C - Slab
    .string "こけむすせきばん"	@name
    .byte   240	@unk9
    .hword  0	@cost
    .byte   11	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 045 / 0x02D - Lifter
    .string "とうぞくのうで"	@name
    .fill   1, 1, 0	@filler
    .byte   96	@unk9
    .hword  0	@cost
    .byte   67	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 046 / 0x02E - E.Key
    .string "だいちのかぎ"	@name
    .fill   2, 1, 0	@filler
    .byte   176	@unk9
    .hword  0	@cost
    .byte   9	@unkC
    .byte   0	@unkD
    .byte   129	@flags

@ Item 047 / 0x02F - ClmWtr
    .string "やすらぎのみず"	@name
    .fill   1, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   88	@unkC
    .byte   0	@unkD
    .byte   3	@flags

@ Item 048 / 0x030 - Coach
    .string "まほうのばしゃ"	@name
    .fill   1, 1, 0	@filler
    .byte   224	@unk9
    .hword  0	@cost
    .byte   164	@unkC
    .byte   239	@unkD
    .byte   0	@flags

@ Item 049 / 0x031 - Clog
    .string "そっこうのくつ"	@name
    .fill   1, 1, 0	@filler
    .byte   224	@unk9
    .hword  0	@cost
    .byte   61	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 050 / 0x032 - A.Ptn
    .string "すばやくそう"	@name
    .fill   2, 1, 0	@filler
    .byte   80	@unk9
    .hword  20	@cost
    .byte   74	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 051 / 0x033 - L.Ptn
    .string "ラッきのえだ"	@name
    .fill   2, 1, 0	@filler
    .byte   80	@unk9
    .hword  10	@cost
    .byte   76	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 052 / 0x034 - V.Ptn
    .string "スタミナのもと"	@name
    .fill   1, 1, 0	@filler
    .byte   80	@unk9
    .hword  10	@cost
    .byte   78	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 053 / 0x035 - DrSoul
    .string "りゅうのたましい"	@name
    .byte   224	@unk9
    .hword  0	@cost
    .byte   88	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 054 / 0x036 - DrWarp
    .string "どこでもドア"	@name
    .fill   2, 1, 0	@filler
    .byte   208	@unk9
    .hword  0	@cost
    .byte   88	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 055 / 0x037 - PlceBo
    .string "はずれ"	@name
    .fill   5, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   88	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 056 / 0x038 - Remedy
    .string "げどくやく"	@name
    .fill   3, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   88	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 057 / 0x039 - WtrJr
    .string "クラインのつぼ"	@name
    .fill   1, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   71	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 058 / 0x03A - Saw
    .string "のこぎり"	@name
    .fill   4, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   88	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 059 / 0x03B - Tablet
    .string "なぞのせきばん"	@name
    .fill   1, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   89	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 060 / 0x03C - Ring
    .string "ゆうしゃのゆびわ"	@name
    .byte   224	@unk9
    .hword  0	@cost
    .byte   170	@unkC
    .byte   127	@unkD
    .byte   128	@flags

@ Item 061 / 0x03D - WtrJr'
    .string "クラインのつぼ!"	@name
    .byte   144	@unk9
    .hword  0	@cost
    .byte   91	@unkC
    .byte   0	@unkD
    .byte   135	@flags

@ Item 062 / 0x03E - KngKey
    .string "おうのかぎ"	@name
    .fill   3, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   92	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 063 / 0x03F - Paper
    .string "はずれ"	@name
    .fill   5, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   88	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 064 / 0x040 - Oath
    .string "はずれ"	@name
    .fill   5, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   88	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 065 / 0x041 - Pouch
    .string "ひもつきさいふ"	@name
    .fill   1, 1, 0	@filler
    .byte   112	@unk9
    .hword  1000	@cost
    .byte   95	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 066 / 0x042 - GnPwdr
    .string "とくせいばくやく"	@name
    .byte   240	@unk9
    .hword  0	@cost
    .byte   96	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 067 / 0x043 - LtKey
    .string "ひかりのかぎ"	@name
    .fill   2, 1, 0	@filler
    .byte   208	@unk9
    .hword  0	@cost
    .byte   9	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 068 / 0x044 - DkKey
    .string "やみのかぎ"	@name
    .fill   3, 1, 0	@filler
    .byte   208	@unk9
    .hword  0	@cost
    .byte   9	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 069 / 0x045 - Mirror
    .string "よみのかがみ"	@name
    .fill   2, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   97	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 070 / 0x046 - Book
    .string "ひでんのしょ"	@name
    .fill   2, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   171	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 071 / 0x047 - Srdine
    .string "たんけんいわし"	@name
    .fill   1, 1, 0	@filler
    .byte   16	@unk9
    .hword  50	@cost
    .byte   0	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 072 / 0x048 - Mackrl
    .string "かぶとあじ"	@name
    .fill   3, 1, 0	@filler
    .byte   16	@unk9
    .hword  100	@cost
    .byte   70	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 073 / 0x049 - Sole
    .string "シ-ルドがれい"	@name
    .fill   1, 1, 0	@filler
    .byte   16	@unk9
    .hword  250	@cost
    .byte   0	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 074 / 0x04A - Trout
    .string "こばんがつお"	@name
    .fill   2, 1, 0	@filler
    .byte   16	@unk9
    .hword  500	@cost
    .byte   81	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 075 / 0x04B - C.Fsh
    .string "いっかくはまち"	@name
    .fill   1, 1, 0	@filler
    .byte   16	@unk9
    .hword  750	@cost
    .byte   103	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 076 / 0x04C - Snapr
    .string "おおこがねだい"	@name
    .fill   1, 1, 0	@filler
    .byte   16	@unk9
    .hword  1000	@cost
    .byte   103	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 077 / 0x04D - Tuna
    .string "りゅうぐうまぐろ"	@name
    .byte   16	@unk9
    .hword  2000	@cost
    .byte   103	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 078 / 0x04E - Puffer
    .string "かっちゅうふぐ"	@name
    .fill   1, 1, 0	@filler
    .byte   80	@unk9
    .hword  5000	@cost
    .byte   104	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 079 / 0x04F - Rod1
    .string "つりざお"	@name
    .fill   4, 1, 0	@filler
    .byte   96	@unk9
    .hword  1000	@cost
    .byte   106	@unkC
    .byte   127	@unkD
    .byte   0	@flags

@ Item 080 / 0x050 - Rod2
    .string "さおデラックス"	@name
    .fill   1, 1, 0	@filler
    .byte   96	@unk9
    .hword  2000	@cost
    .byte   106	@unkC
    .byte   127	@unkD
    .byte   0	@flags

@ Item 081 / 0x051 - Rod3
    .string "つりきちのさお"	@name
    .fill   1, 1, 0	@filler
    .byte   96	@unk9
    .hword  5000	@cost
    .byte   106	@unkC
    .byte   127	@unkD
    .byte   0	@flags

@ Item 082 / 0x052 - Rod4
    .string "すごいさお"	@name
    .fill   3, 1, 0	@filler
    .byte   96	@unk9
    .hword  10000	@cost
    .byte   106	@unkC
    .byte   127	@unkD
    .byte   0	@flags

@ Item 083 / 0x053 - Rod5
    .string "たくみのさお"	@name
    .fill   2, 1, 0	@filler
    .byte   224	@unk9
    .hword  0	@cost
    .byte   63	@unkC
    .byte   127	@unkD
    .byte   0	@flags

@ Item 084 / 0x054 - I.Ore
    .string "てっこうせき"	@name
    .fill   2, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   107	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 085 / 0x055 - Key
    .string "ほこらのかぎ"	@name
    .fill   2, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   111	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 086 / 0x056 - Vitamn
    .string "ふつかよいぐすり"	@name
    .byte   16	@unk9
    .hword  500	@cost
    .byte   88	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 087 / 0x057 - Statue
    .string "しゅごしんぞう"	@name
    .fill   1, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   113	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 088 / 0x058 - OldEgg
    .string "ふるいタマゴ"	@name
    .fill   2, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   114	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 089 / 0x059 - Goods
    .string "しょうひん"	@name
    .fill   3, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   115	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 090 / 0x05A - Egg
    .string "おおきなタマゴ"	@name
    .fill   1, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   116	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 091 / 0x05B - Sphere
    .string "しょうにんだま"	@name
    .fill   1, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   117	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 092 / 0x05C - Gills
    .string "つけえら"	@name
    .fill   4, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   118	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 093 / 0x05D - G.Bar
    .string "きんののべぼう"	@name
    .fill   1, 1, 0	@filler
    .byte   112	@unk9
    .hword  50000	@cost
    .byte   66	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 094 / 0x05E - Icicle
    .string "こおりのせんす"	@name
    .fill   1, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   148	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 095 / 0x05F - Fife
    .string "とうぞくのふえ"	@name
    .fill   1, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   149	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 096 / 0x060 - Pass
    .string "つうこうしょ"	@name
    .fill   2, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   243	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 097 / 0x061 - B.Part
    .string "こわれたぶひん"	@name
    .fill   1, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   150	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 098 / 0x062 - Parts
    .string "そうちのぶひん"	@name
    .fill   1, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   162	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 099 / 0x063 - D.Hrt
    .string "ドラゴン.ソウル"	@name
    .byte   176	@unk9
    .hword  0	@cost
    .byte   163	@unkC
    .byte   0	@unkD
    .byte   129	@flags

@ Item 100 / 0x064 - Map
    .string "まほうのちず"	@name
    .fill   2, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   80	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 101 / 0x065 - List
    .string "いちらんひょう"	@name
    .fill   1, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   108	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 102 / 0x066 - Wtzit
    .string "へんなもの"	@name
    .fill   3, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   67	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 103 / 0x067 - Note1
    .string "おじじのてがみ"	@name
    .fill   1, 1, 0	@filler
    .byte   208	@unk9
    .hword  0	@cost
    .byte   143	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 104 / 0x068 - Note2
    .string "おばばのてがみ"	@name
    .fill   1, 1, 0	@filler
    .byte   208	@unk9
    .hword  0	@cost
    .byte   90	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 105 / 0x069 - I.Claw
    .string "はがんのつめ"	@name
    .fill   2, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   93	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 106 / 0x06A - TmKey
    .string "ときのかぎ"	@name
    .fill   3, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   9	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 107 / 0x06B - B.Rang
    .string "ふるいブ-メラン"	@name
    .byte   240	@unk9
    .hword  0	@cost
    .byte   112	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 108 / 0x06C - SkyKey
    .string "てんのかぎ"	@name
    .fill   3, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   9	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 109 / 0x06D - Cowl
    .string "ききみみずきん"	@name
    .fill   1, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   151	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 110 / 0x06E - Bolster
    .string "セラピのまくら"	@name
    .fill   1, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   152	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 111 / 0x06F - Maestro
    .string "めいじんのふえ"	@name
    .fill   1, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   153	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 112 / 0x070 - G.Fly
    .string "きんばえ"	@name
    .fill   4, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   88	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 113 / 0x071 - Oil
    .string "かえるのしる"	@name
    .fill   2, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   110	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 114 / 0x072 - M.Cura
    .string "ネズミのくすり"	@name
    .fill   1, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   242	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 115 / 0x073 - Melon
    .string "マックスメロン"	@name
    .fill   1, 1, 0	@filler
    .byte   16	@unk9
    .hword  100	@cost
    .byte   0	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 116 / 0x074 - Fruit
    .string "ホリディのみ"	@name
    .fill   2, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   253	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 117 / 0x075 - P.Fish
    .string "どフグ"	@name
    .fill   5, 1, 0	@filler
    .byte   80	@unk9
    .hword  10	@cost
    .byte   110	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 118 / 0x076 - Root
    .string "ホリのねっこ"	@name
    .fill   2, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   110	@unkC
    .byte   0	@unkD
    .byte   128	@flags

@ Item 119 / 0x077 - C.Nut
    .string "わだヤシのみ"	@name
    .fill   2, 1, 0	@filler
    .byte   16	@unk9
    .hword  10	@cost
    .byte   110	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 120 / 0x078 - W.Ant
    .string "しろしかのつの"	@name
    .fill   1, 1, 0	@filler
    .byte   16	@unk9
    .hword  3000	@cost
    .byte   19	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 121 / 0x079 - Tonic
    .string "オリザニン"	@name
    .fill   3, 1, 0	@filler
    .byte   240	@unk9
    .hword  0	@cost
    .byte   242	@unkC
    .byte   0	@unkD
    .byte   0	@flags

@ Item 122 / 0x07A - Herb  X9
    .string "やくそう  X9"	@name
    .byte   16	@unk9
    .hword  90	@cost
    .byte   0	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 123 / 0x07B - Antd  X9
    .string "どくけし  X9"	@name
    .byte   16	@unk9
    .hword  135	@cost
    .byte   70	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 124 / 0x07C - Drop  X9
    .string "ベムのなみだX9"	@name
    .byte   16	@unk9
    .hword  180	@cost
    .byte   2	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 125 / 0x07D - Chrm  X9
    .string "おふだ   X9"	@name
    .byte   16	@unk9
    .hword  1350	@cost
    .byte   7	@unkC
    .byte   0	@unkD
    .byte   2	@flags

@ Item 126 / 0x07E - Cure  X9
    .string "きつけやく X9"	@name
    .byte   16	@unk9
    .hword  4500	@cost
    .byte   16	@unkC
    .byte   0	@unkD
    .byte   6	@flags

@ Item 127 / 0x07F - Acrn  X9
    .string "ちりょくのみX9"	@name
    .byte   16	@unk9
    .hword  270	@cost
    .byte   19	@unkC
    .byte   0	@unkD
    .byte   2	@flags

